// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: activities.sql

package database

import (
	"context"
)

const countUserActivities = `-- name: CountUserActivities :one
SELECT COUNT(*)
FROM activities a
WHERE a.user_id = ?1 AND a.created_at >= date('now', '-30 days')
`

func (q *Queries) CountUserActivities(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUserActivities, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createActivity = `-- name: CreateActivity :one
INSERT INTO activities (
    id, user_id, type, target_id, target_name
) VALUES (
    ?1, ?2, ?3, ?4, ?5
)
RETURNING id, user_id, type, target_id, created_at, target_name
`

type CreateActivityParams struct {
	ID         string  `json:"id"`
	UserID     string  `json:"user_id"`
	Type       string  `json:"type"`
	TargetID   string  `json:"target_id"`
	TargetName *string `json:"target_name"`
}

func (q *Queries) CreateActivity(ctx context.Context, arg CreateActivityParams) (Activity, error) {
	row := q.db.QueryRowContext(ctx, createActivity,
		arg.ID,
		arg.UserID,
		arg.Type,
		arg.TargetID,
		arg.TargetName,
	)
	var i Activity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.TargetID,
		&i.CreatedAt,
		&i.TargetName,
	)
	return i, err
}

const listAllActivities = `-- name: ListAllActivities :many
SELECT a.id, a.user_id, a.type, a.target_id, a.created_at, a.target_name, CAST(CASE WHEN u.private = 1 THEN 'Anonym' ELSE u.name END AS TEXT) as user_name
FROM activities a
JOIN users u ON a.user_id = u.id
WHERE a.created_at >= date('now', '-30 days')
ORDER BY a.created_at DESC
LIMIT ?2 OFFSET ?1
`

type ListAllActivitiesParams struct {
	Offset int64 `json:"offset"`
	Limit  int64 `json:"limit"`
}

type ListAllActivitiesRow struct {
	ID         string  `json:"id"`
	UserID     string  `json:"user_id"`
	Type       string  `json:"type"`
	TargetID   string  `json:"target_id"`
	CreatedAt  string  `json:"created_at"`
	TargetName *string `json:"target_name"`
	UserName   string  `json:"user_name"`
}

func (q *Queries) ListAllActivities(ctx context.Context, arg ListAllActivitiesParams) ([]ListAllActivitiesRow, error) {
	rows, err := q.db.QueryContext(ctx, listAllActivities, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllActivitiesRow
	for rows.Next() {
		var i ListAllActivitiesRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.TargetID,
			&i.CreatedAt,
			&i.TargetName,
			&i.UserName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserActivities = `-- name: ListUserActivities :many
SELECT a.id, a.user_id, a.type, a.target_id, a.created_at, a.target_name, CAST(CASE WHEN u.private = 1 THEN 'Anonym' ELSE u.name END AS TEXT) as user_name
FROM activities a
JOIN users u ON a.user_id = u.id
WHERE a.user_id = ?1 AND a.created_at >= date('now', '-30 days')
ORDER BY a.created_at DESC
LIMIT ?3 OFFSET ?2
`

type ListUserActivitiesParams struct {
	UserID string `json:"user_id"`
	Offset int64  `json:"offset"`
	Limit  int64  `json:"limit"`
}

type ListUserActivitiesRow struct {
	ID         string  `json:"id"`
	UserID     string  `json:"user_id"`
	Type       string  `json:"type"`
	TargetID   string  `json:"target_id"`
	CreatedAt  string  `json:"created_at"`
	TargetName *string `json:"target_name"`
	UserName   string  `json:"user_name"`
}

func (q *Queries) ListUserActivities(ctx context.Context, arg ListUserActivitiesParams) ([]ListUserActivitiesRow, error) {
	rows, err := q.db.QueryContext(ctx, listUserActivities, arg.UserID, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserActivitiesRow
	for rows.Next() {
		var i ListUserActivitiesRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.TargetID,
			&i.CreatedAt,
			&i.TargetName,
			&i.UserName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
