// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: archive.sql

package database

import (
	"context"
)

const clearLatestFlagByGroupId = `-- name: ClearLatestFlagByGroupId :exec
UPDATE archive SET is_latest = 0 WHERE group_id = ?1
`

func (q *Queries) ClearLatestFlagByGroupId(ctx context.Context, groupID int64) error {
	_, err := q.db.ExecContext(ctx, clearLatestFlagByGroupId, groupID)
	return err
}

const createArchiveEntry = `-- name: CreateArchiveEntry :one
INSERT INTO archive (
  id, group_id, user_id, module_id, version, exam_date,
  comment, edit_version, is_latest, access_key,
  mime_type, nbytes, checksum
) VALUES (
  ?1, ?2, ?3, ?4, ?5, ?6,
  ?7, ?8, ?9, ?10,
  ?11, ?12, ?13
) RETURNING id, group_id, user_id, module_id, version, exam_date, comment, edit_version, is_latest, access_key, mime_type, nbytes, checksum, created_at, updated_at, deleted_at
`

type CreateArchiveEntryParams struct {
	ID          int64   `json:"id"`
	GroupID     int64   `json:"group_id"`
	UserID      int64   `json:"user_id"`
	ModuleID    int64   `json:"module_id"`
	Version     string  `json:"version"`
	ExamDate    string  `json:"exam_date"`
	Comment     *string `json:"comment"`
	EditVersion int64   `json:"edit_version"`
	IsLatest    int64   `json:"is_latest"`
	AccessKey   string  `json:"access_key"`
	MimeType    string  `json:"mime_type"`
	Nbytes      int64   `json:"nbytes"`
	Checksum    string  `json:"checksum"`
}

func (q *Queries) CreateArchiveEntry(ctx context.Context, arg CreateArchiveEntryParams) (Archive, error) {
	row := q.db.QueryRowContext(ctx, createArchiveEntry,
		arg.ID,
		arg.GroupID,
		arg.UserID,
		arg.ModuleID,
		arg.Version,
		arg.ExamDate,
		arg.Comment,
		arg.EditVersion,
		arg.IsLatest,
		arg.AccessKey,
		arg.MimeType,
		arg.Nbytes,
		arg.Checksum,
	)
	var i Archive
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.UserID,
		&i.ModuleID,
		&i.Version,
		&i.ExamDate,
		&i.Comment,
		&i.EditVersion,
		&i.IsLatest,
		&i.AccessKey,
		&i.MimeType,
		&i.Nbytes,
		&i.Checksum,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteArchiveEntry = `-- name: DeleteArchiveEntry :exec
UPDATE archive SET deleted_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now'), is_latest = 0 WHERE id = ?1
`

func (q *Queries) DeleteArchiveEntry(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteArchiveEntry, id)
	return err
}

const getArchiveEntry = `-- name: GetArchiveEntry :one
SELECT id, group_id, user_id, module_id, version, exam_date, comment, edit_version, is_latest, access_key, mime_type, nbytes, checksum, created_at, updated_at, deleted_at FROM archive WHERE id = ?1 AND deleted_at IS NULL LIMIT 1
`

func (q *Queries) GetArchiveEntry(ctx context.Context, id int64) (Archive, error) {
	row := q.db.QueryRowContext(ctx, getArchiveEntry, id)
	var i Archive
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.UserID,
		&i.ModuleID,
		&i.Version,
		&i.ExamDate,
		&i.Comment,
		&i.EditVersion,
		&i.IsLatest,
		&i.AccessKey,
		&i.MimeType,
		&i.Nbytes,
		&i.Checksum,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getArchiveEntryByMetadata = `-- name: GetArchiveEntryByMetadata :one
SELECT id, group_id, user_id, module_id, version, exam_date, comment, edit_version, is_latest, access_key, mime_type, nbytes, checksum, created_at, updated_at, deleted_at FROM archive 
WHERE module_id = ?1 
  AND version = ?2 
  AND exam_date = ?3 
  AND deleted_at IS NULL 
LIMIT 1
`

type GetArchiveEntryByMetadataParams struct {
	ModuleID int64  `json:"module_id"`
	Version  string `json:"version"`
	ExamDate string `json:"exam_date"`
}

func (q *Queries) GetArchiveEntryByMetadata(ctx context.Context, arg GetArchiveEntryByMetadataParams) (Archive, error) {
	row := q.db.QueryRowContext(ctx, getArchiveEntryByMetadata, arg.ModuleID, arg.Version, arg.ExamDate)
	var i Archive
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.UserID,
		&i.ModuleID,
		&i.Version,
		&i.ExamDate,
		&i.Comment,
		&i.EditVersion,
		&i.IsLatest,
		&i.AccessKey,
		&i.MimeType,
		&i.Nbytes,
		&i.Checksum,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getArchiveEntryDetails = `-- name: GetArchiveEntryDetails :one
SELECT a.id, a.group_id, a.user_id, a.module_id, a.version, a.exam_date, a.comment, a.edit_version, a.is_latest, a.access_key, a.mime_type, a.nbytes, a.checksum, a.created_at, a.updated_at, a.deleted_at,
       m.name as module_name, m.program_id,
       CAST(CASE WHEN u.private = 1 THEN 'Anonym' ELSE u.name END AS TEXT) as uploader_name
FROM archive a
JOIN modules m ON a.module_id = m.id
JOIN users u ON a.user_id = u.id
WHERE a.id = ?1 AND a.deleted_at IS NULL LIMIT 1
`

type GetArchiveEntryDetailsRow struct {
	ID           int64   `json:"id"`
	GroupID      int64   `json:"group_id"`
	UserID       int64   `json:"user_id"`
	ModuleID     int64   `json:"module_id"`
	Version      string  `json:"version"`
	ExamDate     string  `json:"exam_date"`
	Comment      *string `json:"comment"`
	EditVersion  int64   `json:"edit_version"`
	IsLatest     int64   `json:"is_latest"`
	AccessKey    string  `json:"access_key"`
	MimeType     string  `json:"mime_type"`
	Nbytes       int64   `json:"nbytes"`
	Checksum     string  `json:"checksum"`
	CreatedAt    string  `json:"created_at"`
	UpdatedAt    string  `json:"updated_at"`
	DeletedAt    *string `json:"deleted_at"`
	ModuleName   string  `json:"module_name"`
	ProgramID    int64   `json:"program_id"`
	UploaderName string  `json:"uploader_name"`
}

func (q *Queries) GetArchiveEntryDetails(ctx context.Context, id int64) (GetArchiveEntryDetailsRow, error) {
	row := q.db.QueryRowContext(ctx, getArchiveEntryDetails, id)
	var i GetArchiveEntryDetailsRow
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.UserID,
		&i.ModuleID,
		&i.Version,
		&i.ExamDate,
		&i.Comment,
		&i.EditVersion,
		&i.IsLatest,
		&i.AccessKey,
		&i.MimeType,
		&i.Nbytes,
		&i.Checksum,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ModuleName,
		&i.ProgramID,
		&i.UploaderName,
	)
	return i, err
}

const getLatestByGroupId = `-- name: GetLatestByGroupId :one
SELECT id, group_id, user_id, module_id, version, exam_date, comment, edit_version, is_latest, access_key, mime_type, nbytes, checksum, created_at, updated_at, deleted_at FROM archive WHERE group_id = ?1 AND is_latest = 1 AND deleted_at IS NULL LIMIT 1
`

func (q *Queries) GetLatestByGroupId(ctx context.Context, groupID int64) (Archive, error) {
	row := q.db.QueryRowContext(ctx, getLatestByGroupId, groupID)
	var i Archive
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.UserID,
		&i.ModuleID,
		&i.Version,
		&i.ExamDate,
		&i.Comment,
		&i.EditVersion,
		&i.IsLatest,
		&i.AccessKey,
		&i.MimeType,
		&i.Nbytes,
		&i.Checksum,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listArchiveEntries = `-- name: ListArchiveEntries :many
SELECT a.id, a.group_id, a.user_id, a.module_id, a.version, a.exam_date, a.comment, a.edit_version, a.is_latest, a.access_key, a.mime_type, a.nbytes, a.checksum, a.created_at, a.updated_at, a.deleted_at,
       m.name as module_name, m.program_id,
       CAST(CASE WHEN u.private = 1 THEN 'Anonym' ELSE u.name END AS TEXT) as uploader_name
FROM archive a
JOIN modules m ON a.module_id = m.id
JOIN users u ON a.user_id = u.id
WHERE (?1 IS NULL OR m.program_id = ?1)
  AND (?2 IS NULL OR a.version = ?2)
  AND (?3 IS NULL OR a.module_id = ?3)
  AND a.is_latest = 1
  AND a.deleted_at IS NULL
ORDER BY a.exam_date DESC
`

type ListArchiveEntriesParams struct {
	ProgramID interface{} `json:"program_id"`
	Version   interface{} `json:"version"`
	ModuleID  interface{} `json:"module_id"`
}

type ListArchiveEntriesRow struct {
	ID           int64   `json:"id"`
	GroupID      int64   `json:"group_id"`
	UserID       int64   `json:"user_id"`
	ModuleID     int64   `json:"module_id"`
	Version      string  `json:"version"`
	ExamDate     string  `json:"exam_date"`
	Comment      *string `json:"comment"`
	EditVersion  int64   `json:"edit_version"`
	IsLatest     int64   `json:"is_latest"`
	AccessKey    string  `json:"access_key"`
	MimeType     string  `json:"mime_type"`
	Nbytes       int64   `json:"nbytes"`
	Checksum     string  `json:"checksum"`
	CreatedAt    string  `json:"created_at"`
	UpdatedAt    string  `json:"updated_at"`
	DeletedAt    *string `json:"deleted_at"`
	ModuleName   string  `json:"module_name"`
	ProgramID    int64   `json:"program_id"`
	UploaderName string  `json:"uploader_name"`
}

func (q *Queries) ListArchiveEntries(ctx context.Context, arg ListArchiveEntriesParams) ([]ListArchiveEntriesRow, error) {
	rows, err := q.db.QueryContext(ctx, listArchiveEntries, arg.ProgramID, arg.Version, arg.ModuleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListArchiveEntriesRow
	for rows.Next() {
		var i ListArchiveEntriesRow
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.UserID,
			&i.ModuleID,
			&i.Version,
			&i.ExamDate,
			&i.Comment,
			&i.EditVersion,
			&i.IsLatest,
			&i.AccessKey,
			&i.MimeType,
			&i.Nbytes,
			&i.Checksum,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.ModuleName,
			&i.ProgramID,
			&i.UploaderName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArchiveVersions = `-- name: ListArchiveVersions :many
SELECT a.id, a.group_id, a.user_id, a.module_id, a.version, a.exam_date, a.comment, a.edit_version, a.is_latest, a.access_key, a.mime_type, a.nbytes, a.checksum, a.created_at, a.updated_at, a.deleted_at,
       CAST(CASE WHEN u.private = 1 THEN 'Anonym' ELSE u.name END AS TEXT) as uploader_name
FROM archive a
JOIN users u ON a.user_id = u.id
WHERE a.group_id = ?1 AND a.deleted_at IS NULL
ORDER BY a.edit_version DESC
`

type ListArchiveVersionsRow struct {
	ID           int64   `json:"id"`
	GroupID      int64   `json:"group_id"`
	UserID       int64   `json:"user_id"`
	ModuleID     int64   `json:"module_id"`
	Version      string  `json:"version"`
	ExamDate     string  `json:"exam_date"`
	Comment      *string `json:"comment"`
	EditVersion  int64   `json:"edit_version"`
	IsLatest     int64   `json:"is_latest"`
	AccessKey    string  `json:"access_key"`
	MimeType     string  `json:"mime_type"`
	Nbytes       int64   `json:"nbytes"`
	Checksum     string  `json:"checksum"`
	CreatedAt    string  `json:"created_at"`
	UpdatedAt    string  `json:"updated_at"`
	DeletedAt    *string `json:"deleted_at"`
	UploaderName string  `json:"uploader_name"`
}

func (q *Queries) ListArchiveVersions(ctx context.Context, groupID int64) ([]ListArchiveVersionsRow, error) {
	rows, err := q.db.QueryContext(ctx, listArchiveVersions, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListArchiveVersionsRow
	for rows.Next() {
		var i ListArchiveVersionsRow
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.UserID,
			&i.ModuleID,
			&i.Version,
			&i.ExamDate,
			&i.Comment,
			&i.EditVersion,
			&i.IsLatest,
			&i.AccessKey,
			&i.MimeType,
			&i.Nbytes,
			&i.Checksum,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.UploaderName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const promoteLatestInGroup = `-- name: PromoteLatestInGroup :exec
UPDATE archive SET is_latest = 1 
WHERE id = (
    SELECT a2.id FROM archive a2
    WHERE a2.group_id = ?1 AND a2.deleted_at IS NULL 
    ORDER BY a2.edit_version DESC LIMIT 1
)
`

func (q *Queries) PromoteLatestInGroup(ctx context.Context, groupID int64) error {
	_, err := q.db.ExecContext(ctx, promoteLatestInGroup, groupID)
	return err
}

const searchArchive = `-- name: SearchArchive :many
SELECT a.id, a.group_id, a.user_id, a.module_id, a.version, a.exam_date, a.comment, a.edit_version, a.is_latest, a.access_key, a.mime_type, a.nbytes, a.checksum, a.created_at, a.updated_at, a.deleted_at,
       m.name as module_name, m.program_id,
       CAST(CASE WHEN u.private = 1 THEN 'Anonym' ELSE u.name END AS TEXT) as uploader_name
FROM archive a
JOIN modules m ON a.module_id = m.id
JOIN users u ON a.user_id = u.id
WHERE a.is_latest = 1 AND a.deleted_at IS NULL
  AND (m.name LIKE '%' || ?1 || '%'
       OR m.alias LIKE '%' || ?1 || '%'
       OR a.comment LIKE '%' || ?1 || '%')
ORDER BY a.exam_date DESC
LIMIT 20
`

type SearchArchiveRow struct {
	ID           int64   `json:"id"`
	GroupID      int64   `json:"group_id"`
	UserID       int64   `json:"user_id"`
	ModuleID     int64   `json:"module_id"`
	Version      string  `json:"version"`
	ExamDate     string  `json:"exam_date"`
	Comment      *string `json:"comment"`
	EditVersion  int64   `json:"edit_version"`
	IsLatest     int64   `json:"is_latest"`
	AccessKey    string  `json:"access_key"`
	MimeType     string  `json:"mime_type"`
	Nbytes       int64   `json:"nbytes"`
	Checksum     string  `json:"checksum"`
	CreatedAt    string  `json:"created_at"`
	UpdatedAt    string  `json:"updated_at"`
	DeletedAt    *string `json:"deleted_at"`
	ModuleName   string  `json:"module_name"`
	ProgramID    int64   `json:"program_id"`
	UploaderName string  `json:"uploader_name"`
}

func (q *Queries) SearchArchive(ctx context.Context, query *string) ([]SearchArchiveRow, error) {
	rows, err := q.db.QueryContext(ctx, searchArchive, query)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchArchiveRow
	for rows.Next() {
		var i SearchArchiveRow
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.UserID,
			&i.ModuleID,
			&i.Version,
			&i.ExamDate,
			&i.Comment,
			&i.EditVersion,
			&i.IsLatest,
			&i.AccessKey,
			&i.MimeType,
			&i.Nbytes,
			&i.Checksum,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.ModuleName,
			&i.ProgramID,
			&i.UploaderName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
