// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: discussions.sql

package database

import (
	"context"
)

const addLinkToPost = `-- name: AddLinkToPost :one
INSERT INTO discussion_post_links (post_id, url, label) VALUES (?1, ?2, ?3) RETURNING id, post_id, url, label
`

type AddLinkToPostParams struct {
	PostID int64   `json:"post_id"`
	Url    string  `json:"url"`
	Label  *string `json:"label"`
}

func (q *Queries) AddLinkToPost(ctx context.Context, arg AddLinkToPostParams) (DiscussionPostLink, error) {
	row := q.db.QueryRowContext(ctx, addLinkToPost, arg.PostID, arg.Url, arg.Label)
	var i DiscussionPostLink
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.Url,
		&i.Label,
	)
	return i, err
}

const addProgramToPost = `-- name: AddProgramToPost :exec
INSERT INTO discussion_post_programs (post_id, program_id) VALUES (?1, ?2)
`

type AddProgramToPostParams struct {
	PostID    int64 `json:"post_id"`
	ProgramID int64 `json:"program_id"`
}

func (q *Queries) AddProgramToPost(ctx context.Context, arg AddProgramToPostParams) error {
	_, err := q.db.ExecContext(ctx, addProgramToPost, arg.PostID, arg.ProgramID)
	return err
}

const addTagToPost = `-- name: AddTagToPost :exec
INSERT INTO discussion_post_tags (post_id, tag) VALUES (?1, ?2)
`

type AddTagToPostParams struct {
	PostID int64  `json:"post_id"`
	Tag    string `json:"tag"`
}

func (q *Queries) AddTagToPost(ctx context.Context, arg AddTagToPostParams) error {
	_, err := q.db.ExecContext(ctx, addTagToPost, arg.PostID, arg.Tag)
	return err
}

const clearPostLinks = `-- name: ClearPostLinks :exec
DELETE FROM discussion_post_links WHERE post_id = ?1
`

func (q *Queries) ClearPostLinks(ctx context.Context, postID int64) error {
	_, err := q.db.ExecContext(ctx, clearPostLinks, postID)
	return err
}

const clearPostPrograms = `-- name: ClearPostPrograms :exec
DELETE FROM discussion_post_programs WHERE post_id = ?1
`

func (q *Queries) ClearPostPrograms(ctx context.Context, postID int64) error {
	_, err := q.db.ExecContext(ctx, clearPostPrograms, postID)
	return err
}

const clearPostTags = `-- name: ClearPostTags :exec
DELETE FROM discussion_post_tags WHERE post_id = ?1
`

func (q *Queries) ClearPostTags(ctx context.Context, postID int64) error {
	_, err := q.db.ExecContext(ctx, clearPostTags, postID)
	return err
}

const countDiscussionPosts = `-- name: CountDiscussionPosts :one
SELECT COUNT(*) FROM discussion_posts p
WHERE (?1 IS NULL OR p.type = ?1)
  AND (?2 IS NULL OR (lower(p.title) LIKE '%' || lower(?2) || '%' OR lower(p.body) LIKE '%' || lower(?2) || '%'))
  AND p.deleted_at IS NULL
  AND (?3 IS NULL OR p.id IN (SELECT post_id FROM discussion_post_programs WHERE program_id = ?3))
`

type CountDiscussionPostsParams struct {
	Type      interface{} `json:"type"`
	Query     interface{} `json:"query"`
	ProgramID interface{} `json:"program_id"`
}

func (q *Queries) CountDiscussionPosts(ctx context.Context, arg CountDiscussionPostsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countDiscussionPosts, arg.Type, arg.Query, arg.ProgramID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDiscussionComment = `-- name: CreateDiscussionComment :one
INSERT INTO discussion_comments (
    id, post_id, user_id, parent_id, text
) VALUES (
    ?1, ?2, ?3, ?4, ?5
)
RETURNING id, post_id, user_id, parent_id, text, created_at, updated_at, deleted_at
`

type CreateDiscussionCommentParams struct {
	ID       int64  `json:"id"`
	PostID   int64  `json:"post_id"`
	UserID   int64  `json:"user_id"`
	ParentID *int64 `json:"parent_id"`
	Text     string `json:"text"`
}

func (q *Queries) CreateDiscussionComment(ctx context.Context, arg CreateDiscussionCommentParams) (DiscussionComment, error) {
	row := q.db.QueryRowContext(ctx, createDiscussionComment,
		arg.ID,
		arg.PostID,
		arg.UserID,
		arg.ParentID,
		arg.Text,
	)
	var i DiscussionComment
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.UserID,
		&i.ParentID,
		&i.Text,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createDiscussionPost = `-- name: CreateDiscussionPost :one
INSERT INTO discussion_posts (
    id, title, body, user_id, type, pinned, event_date, location, image_url
) VALUES (
    ?1, ?2, ?3, ?4,
    COALESCE(?5, 'discussion'),
    COALESCE(?6, 0),
    ?7,
    ?8,
    ?9
)
RETURNING id, title, body, user_id, pinned, type, event_date, location, image_url, created_at, updated_at, deleted_at
`

type CreateDiscussionPostParams struct {
	ID        int64       `json:"id"`
	Title     string      `json:"title"`
	Body      string      `json:"body"`
	UserID    int64       `json:"user_id"`
	Type      interface{} `json:"type"`
	Pinned    interface{} `json:"pinned"`
	EventDate *string     `json:"event_date"`
	Location  *string     `json:"location"`
	ImageUrl  *string     `json:"image_url"`
}

func (q *Queries) CreateDiscussionPost(ctx context.Context, arg CreateDiscussionPostParams) (DiscussionPost, error) {
	row := q.db.QueryRowContext(ctx, createDiscussionPost,
		arg.ID,
		arg.Title,
		arg.Body,
		arg.UserID,
		arg.Type,
		arg.Pinned,
		arg.EventDate,
		arg.Location,
		arg.ImageUrl,
	)
	var i DiscussionPost
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Body,
		&i.UserID,
		&i.Pinned,
		&i.Type,
		&i.EventDate,
		&i.Location,
		&i.ImageUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteDiscussionComment = `-- name: DeleteDiscussionComment :exec
UPDATE discussion_comments
SET deleted_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
WHERE id = ?1
`

func (q *Queries) DeleteDiscussionComment(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteDiscussionComment, id)
	return err
}

const deleteDiscussionPost = `-- name: DeleteDiscussionPost :exec
UPDATE discussion_posts
SET deleted_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
WHERE id = ?1
`

func (q *Queries) DeleteDiscussionPost(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteDiscussionPost, id)
	return err
}

const getDiscussionComment = `-- name: GetDiscussionComment :one
SELECT id, post_id, user_id, parent_id, text, created_at, updated_at, deleted_at FROM discussion_comments WHERE id = ?1 AND deleted_at IS NULL LIMIT 1
`

func (q *Queries) GetDiscussionComment(ctx context.Context, id int64) (DiscussionComment, error) {
	row := q.db.QueryRowContext(ctx, getDiscussionComment, id)
	var i DiscussionComment
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.UserID,
		&i.ParentID,
		&i.Text,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getDiscussionPost = `-- name: GetDiscussionPost :one
SELECT p.id, p.title, p.body, p.user_id, p.pinned, p.type, p.event_date, p.location, p.image_url, p.created_at, p.updated_at, p.deleted_at,
       CAST(CASE WHEN u.private = 1 THEN 'Anonym' ELSE u.name END AS TEXT) as user_name,
       CAST(CASE WHEN u.private = 1 THEN '' ELSE COALESCE(u.avatar_url, '') END AS TEXT) as user_avatar_url,
       (SELECT COUNT(*) FROM discussion_comments WHERE post_id = p.id AND deleted_at IS NULL) as comment_count,
       (SELECT CAST(COALESCE(SUM(vote), 0) AS INTEGER) FROM discussion_votes WHERE discussion_votes.post_id = p.id) as votes,
       CAST(COALESCE((SELECT vote FROM discussion_votes WHERE discussion_votes.post_id = p.id AND discussion_votes.user_id = ?1), 0) AS INTEGER) as user_vote
FROM discussion_posts p
JOIN users u ON p.user_id = u.id
WHERE p.id = ?2 AND p.deleted_at IS NULL
LIMIT 1
`

type GetDiscussionPostParams struct {
	CurrentUserID *int64 `json:"current_user_id"`
	ID            int64  `json:"id"`
}

type GetDiscussionPostRow struct {
	ID            int64   `json:"id"`
	Title         string  `json:"title"`
	Body          string  `json:"body"`
	UserID        int64   `json:"user_id"`
	Pinned        int64   `json:"pinned"`
	Type          string  `json:"type"`
	EventDate     *string `json:"event_date"`
	Location      *string `json:"location"`
	ImageUrl      *string `json:"image_url"`
	CreatedAt     string  `json:"created_at"`
	UpdatedAt     string  `json:"updated_at"`
	DeletedAt     *string `json:"deleted_at"`
	UserName      string  `json:"user_name"`
	UserAvatarUrl string  `json:"user_avatar_url"`
	CommentCount  int64   `json:"comment_count"`
	Votes         int64   `json:"votes"`
	UserVote      int64   `json:"user_vote"`
}

func (q *Queries) GetDiscussionPost(ctx context.Context, arg GetDiscussionPostParams) (GetDiscussionPostRow, error) {
	row := q.db.QueryRowContext(ctx, getDiscussionPost, arg.CurrentUserID, arg.ID)
	var i GetDiscussionPostRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Body,
		&i.UserID,
		&i.Pinned,
		&i.Type,
		&i.EventDate,
		&i.Location,
		&i.ImageUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.UserName,
		&i.UserAvatarUrl,
		&i.CommentCount,
		&i.Votes,
		&i.UserVote,
	)
	return i, err
}

const getPostLinks = `-- name: GetPostLinks :many
SELECT id, post_id, url, label FROM discussion_post_links WHERE post_id = ?1
`

func (q *Queries) GetPostLinks(ctx context.Context, postID int64) ([]DiscussionPostLink, error) {
	rows, err := q.db.QueryContext(ctx, getPostLinks, postID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DiscussionPostLink
	for rows.Next() {
		var i DiscussionPostLink
		if err := rows.Scan(
			&i.ID,
			&i.PostID,
			&i.Url,
			&i.Label,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPostPrograms = `-- name: GetPostPrograms :many
SELECT p.id, p.name FROM programs p
JOIN discussion_post_programs dpp ON p.id = dpp.program_id
WHERE dpp.post_id = ?1
`

type GetPostProgramsRow struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

func (q *Queries) GetPostPrograms(ctx context.Context, postID int64) ([]GetPostProgramsRow, error) {
	rows, err := q.db.QueryContext(ctx, getPostPrograms, postID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPostProgramsRow
	for rows.Next() {
		var i GetPostProgramsRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPostTags = `-- name: GetPostTags :many
SELECT tag FROM discussion_post_tags WHERE post_id = ?1
`

func (q *Queries) GetPostTags(ctx context.Context, postID int64) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getPostTags, postID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var tag string
		if err := rows.Scan(&tag); err != nil {
			return nil, err
		}
		items = append(items, tag)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDiscussionComments = `-- name: ListDiscussionComments :many
SELECT c.id, c.post_id, c.user_id, c.parent_id, c.text, c.created_at, c.updated_at, c.deleted_at,
       CAST(CASE WHEN u.private = 1 THEN 'Anonym' ELSE u.name END AS TEXT) as user_name,
       CAST(CASE WHEN u.private = 1 THEN '' ELSE COALESCE(u.avatar_url, '') END AS TEXT) as user_avatar_url,
       (SELECT CAST(COALESCE(SUM(vote), 0) AS INTEGER) FROM discussion_comment_votes v WHERE v.comment_id = c.id) as votes,
       CAST(COALESCE((SELECT vote FROM discussion_comment_votes v WHERE v.comment_id = c.id AND v.user_id = ?1), 0) AS INTEGER) as user_vote
FROM discussion_comments c
JOIN users u ON c.user_id = u.id
WHERE c.post_id = ?2 AND c.deleted_at IS NULL
ORDER BY c.created_at ASC
`

type ListDiscussionCommentsParams struct {
	CurrentUserID *int64 `json:"current_user_id"`
	PostID        int64  `json:"post_id"`
}

type ListDiscussionCommentsRow struct {
	ID            int64   `json:"id"`
	PostID        int64   `json:"post_id"`
	UserID        int64   `json:"user_id"`
	ParentID      *int64  `json:"parent_id"`
	Text          string  `json:"text"`
	CreatedAt     string  `json:"created_at"`
	UpdatedAt     string  `json:"updated_at"`
	DeletedAt     *string `json:"deleted_at"`
	UserName      string  `json:"user_name"`
	UserAvatarUrl string  `json:"user_avatar_url"`
	Votes         int64   `json:"votes"`
	UserVote      int64   `json:"user_vote"`
}

func (q *Queries) ListDiscussionComments(ctx context.Context, arg ListDiscussionCommentsParams) ([]ListDiscussionCommentsRow, error) {
	rows, err := q.db.QueryContext(ctx, listDiscussionComments, arg.CurrentUserID, arg.PostID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDiscussionCommentsRow
	for rows.Next() {
		var i ListDiscussionCommentsRow
		if err := rows.Scan(
			&i.ID,
			&i.PostID,
			&i.UserID,
			&i.ParentID,
			&i.Text,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.UserName,
			&i.UserAvatarUrl,
			&i.Votes,
			&i.UserVote,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDiscussionPosts = `-- name: ListDiscussionPosts :many
SELECT p.id, p.title, p.body, p.user_id, p.pinned, p.type, p.event_date, p.location, p.image_url, p.created_at, p.updated_at, p.deleted_at,
       CAST(CASE WHEN u.private = 1 THEN 'Anonym' ELSE u.name END AS TEXT) as user_name,
       CAST(CASE WHEN u.private = 1 THEN '' ELSE COALESCE(u.avatar_url, '') END AS TEXT) as user_avatar_url,
       (SELECT COUNT(*) FROM discussion_comments WHERE post_id = p.id AND deleted_at IS NULL) as comment_count,
       (SELECT CAST(COALESCE(SUM(v.vote), 0) AS INTEGER) FROM discussion_votes v WHERE v.post_id = p.id) as votes,
       CAST(COALESCE((SELECT v.vote FROM discussion_votes v WHERE v.post_id = p.id AND v.user_id = ?1), 0) AS INTEGER) as user_vote
FROM discussion_posts p
JOIN users u ON p.user_id = u.id
WHERE (?2 IS NULL OR p.type = ?2)
  AND (?3 IS NULL OR (lower(p.title) LIKE '%' || lower(?3) || '%' OR lower(p.body) LIKE '%' || lower(?3) || '%'))
  AND p.deleted_at IS NULL
  AND (?4 IS NULL OR p.id IN (SELECT post_id FROM discussion_post_programs WHERE program_id = ?4))
ORDER BY
    p.pinned DESC,
    p.created_at DESC
LIMIT ?6 OFFSET ?5
`

type ListDiscussionPostsParams struct {
	CurrentUserID *int64      `json:"current_user_id"`
	Type          interface{} `json:"type"`
	Query         interface{} `json:"query"`
	ProgramID     interface{} `json:"program_id"`
	Offset        int64       `json:"offset"`
	Limit         int64       `json:"limit"`
}

type ListDiscussionPostsRow struct {
	ID            int64   `json:"id"`
	Title         string  `json:"title"`
	Body          string  `json:"body"`
	UserID        int64   `json:"user_id"`
	Pinned        int64   `json:"pinned"`
	Type          string  `json:"type"`
	EventDate     *string `json:"event_date"`
	Location      *string `json:"location"`
	ImageUrl      *string `json:"image_url"`
	CreatedAt     string  `json:"created_at"`
	UpdatedAt     string  `json:"updated_at"`
	DeletedAt     *string `json:"deleted_at"`
	UserName      string  `json:"user_name"`
	UserAvatarUrl string  `json:"user_avatar_url"`
	CommentCount  int64   `json:"comment_count"`
	Votes         int64   `json:"votes"`
	UserVote      int64   `json:"user_vote"`
}

func (q *Queries) ListDiscussionPosts(ctx context.Context, arg ListDiscussionPostsParams) ([]ListDiscussionPostsRow, error) {
	rows, err := q.db.QueryContext(ctx, listDiscussionPosts,
		arg.CurrentUserID,
		arg.Type,
		arg.Query,
		arg.ProgramID,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDiscussionPostsRow
	for rows.Next() {
		var i ListDiscussionPostsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Body,
			&i.UserID,
			&i.Pinned,
			&i.Type,
			&i.EventDate,
			&i.Location,
			&i.ImageUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.UserName,
			&i.UserAvatarUrl,
			&i.CommentCount,
			&i.Votes,
			&i.UserVote,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDiscussionPostsTop = `-- name: ListDiscussionPostsTop :many
SELECT p.id, p.title, p.body, p.user_id, p.pinned, p.type, p.event_date, p.location, p.image_url, p.created_at, p.updated_at, p.deleted_at,
       CAST(CASE WHEN u.private = 1 THEN 'Anonym' ELSE u.name END AS TEXT) as user_name,
       CAST(CASE WHEN u.private = 1 THEN '' ELSE COALESCE(u.avatar_url, '') END AS TEXT) as user_avatar_url,
       (SELECT COUNT(*) FROM discussion_comments WHERE post_id = p.id AND deleted_at IS NULL) as comment_count,
       (SELECT CAST(COALESCE(SUM(v.vote), 0) AS INTEGER) FROM discussion_votes v WHERE v.post_id = p.id) as votes,
       CAST(COALESCE((SELECT v.vote FROM discussion_votes v WHERE v.post_id = p.id AND v.user_id = ?1), 0) AS INTEGER) as user_vote
FROM discussion_posts p
JOIN users u ON p.user_id = u.id
WHERE (?2 IS NULL OR p.type = ?2)
  AND (?3 IS NULL OR (lower(p.title) LIKE '%' || lower(?3) || '%' OR lower(p.body) LIKE '%' || lower(?3) || '%'))
  AND p.deleted_at IS NULL
  AND (?4 IS NULL OR p.id IN (SELECT post_id FROM discussion_post_programs WHERE program_id = ?4))
ORDER BY
    p.pinned DESC,
    votes DESC,
    p.created_at DESC
LIMIT ?6 OFFSET ?5
`

type ListDiscussionPostsTopParams struct {
	CurrentUserID *int64      `json:"current_user_id"`
	Type          interface{} `json:"type"`
	Query         interface{} `json:"query"`
	ProgramID     interface{} `json:"program_id"`
	Offset        int64       `json:"offset"`
	Limit         int64       `json:"limit"`
}

type ListDiscussionPostsTopRow struct {
	ID            int64   `json:"id"`
	Title         string  `json:"title"`
	Body          string  `json:"body"`
	UserID        int64   `json:"user_id"`
	Pinned        int64   `json:"pinned"`
	Type          string  `json:"type"`
	EventDate     *string `json:"event_date"`
	Location      *string `json:"location"`
	ImageUrl      *string `json:"image_url"`
	CreatedAt     string  `json:"created_at"`
	UpdatedAt     string  `json:"updated_at"`
	DeletedAt     *string `json:"deleted_at"`
	UserName      string  `json:"user_name"`
	UserAvatarUrl string  `json:"user_avatar_url"`
	CommentCount  int64   `json:"comment_count"`
	Votes         int64   `json:"votes"`
	UserVote      int64   `json:"user_vote"`
}

func (q *Queries) ListDiscussionPostsTop(ctx context.Context, arg ListDiscussionPostsTopParams) ([]ListDiscussionPostsTopRow, error) {
	rows, err := q.db.QueryContext(ctx, listDiscussionPostsTop,
		arg.CurrentUserID,
		arg.Type,
		arg.Query,
		arg.ProgramID,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDiscussionPostsTopRow
	for rows.Next() {
		var i ListDiscussionPostsTopRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Body,
			&i.UserID,
			&i.Pinned,
			&i.Type,
			&i.EventDate,
			&i.Location,
			&i.ImageUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.UserName,
			&i.UserAvatarUrl,
			&i.CommentCount,
			&i.Votes,
			&i.UserVote,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchDiscussionPosts = `-- name: SearchDiscussionPosts :many
SELECT p.id, p.title, p.body, p.user_id, p.pinned, p.type, p.event_date, p.location, p.image_url, p.created_at, p.updated_at, p.deleted_at,
       CAST(CASE WHEN u.private = 1 THEN 'Anonym' ELSE u.name END AS TEXT) as user_name,
       CAST(CASE WHEN u.private = 1 THEN '' ELSE COALESCE(u.avatar_url, '') END AS TEXT) as user_avatar_url,
       (SELECT COUNT(*) FROM discussion_comments WHERE post_id = p.id AND deleted_at IS NULL) as comment_count,
       (SELECT CAST(COALESCE(SUM(v.vote), 0) AS INTEGER) FROM discussion_votes v WHERE v.post_id = p.id) as votes,
       CAST(COALESCE((SELECT v.vote FROM discussion_votes v WHERE v.post_id = p.id AND v.user_id = ?1), 0) AS INTEGER) as user_vote
FROM discussion_posts p
JOIN users u ON p.user_id = u.id
WHERE (
  lower(p.title) LIKE '%' || lower(?2) || '%' OR
  lower(p.body) LIKE '%' || lower(?2) || '%'
) AND p.deleted_at IS NULL
ORDER BY 
    p.pinned DESC,
    p.created_at DESC
LIMIT 10
`

type SearchDiscussionPostsParams struct {
	CurrentUserID *int64 `json:"current_user_id"`
	Query         string `json:"query"`
}

type SearchDiscussionPostsRow struct {
	ID            int64   `json:"id"`
	Title         string  `json:"title"`
	Body          string  `json:"body"`
	UserID        int64   `json:"user_id"`
	Pinned        int64   `json:"pinned"`
	Type          string  `json:"type"`
	EventDate     *string `json:"event_date"`
	Location      *string `json:"location"`
	ImageUrl      *string `json:"image_url"`
	CreatedAt     string  `json:"created_at"`
	UpdatedAt     string  `json:"updated_at"`
	DeletedAt     *string `json:"deleted_at"`
	UserName      string  `json:"user_name"`
	UserAvatarUrl string  `json:"user_avatar_url"`
	CommentCount  int64   `json:"comment_count"`
	Votes         int64   `json:"votes"`
	UserVote      int64   `json:"user_vote"`
}

func (q *Queries) SearchDiscussionPosts(ctx context.Context, arg SearchDiscussionPostsParams) ([]SearchDiscussionPostsRow, error) {
	rows, err := q.db.QueryContext(ctx, searchDiscussionPosts, arg.CurrentUserID, arg.Query)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchDiscussionPostsRow
	for rows.Next() {
		var i SearchDiscussionPostsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Body,
			&i.UserID,
			&i.Pinned,
			&i.Type,
			&i.EventDate,
			&i.Location,
			&i.ImageUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.UserName,
			&i.UserAvatarUrl,
			&i.CommentCount,
			&i.Votes,
			&i.UserVote,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDiscussionComment = `-- name: UpdateDiscussionComment :one
UPDATE discussion_comments
SET text = ?1
WHERE id = ?2 AND deleted_at IS NULL
RETURNING id, post_id, user_id, parent_id, text, created_at, updated_at, deleted_at
`

type UpdateDiscussionCommentParams struct {
	Text string `json:"text"`
	ID   int64  `json:"id"`
}

func (q *Queries) UpdateDiscussionComment(ctx context.Context, arg UpdateDiscussionCommentParams) (DiscussionComment, error) {
	row := q.db.QueryRowContext(ctx, updateDiscussionComment, arg.Text, arg.ID)
	var i DiscussionComment
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.UserID,
		&i.ParentID,
		&i.Text,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateDiscussionPost = `-- name: UpdateDiscussionPost :one
UPDATE discussion_posts
SET title = COALESCE(?1, title),
    body = COALESCE(?2, body),
    pinned = COALESCE(?3, pinned),
    event_date = COALESCE(?4, event_date),
    location = COALESCE(?5, location),
    image_url = COALESCE(?6, image_url)
WHERE id = ?7 AND deleted_at IS NULL
RETURNING id, title, body, user_id, pinned, type, event_date, location, image_url, created_at, updated_at, deleted_at
`

type UpdateDiscussionPostParams struct {
	Title     *string `json:"title"`
	Body      *string `json:"body"`
	Pinned    *int64  `json:"pinned"`
	EventDate *string `json:"event_date"`
	Location  *string `json:"location"`
	ImageUrl  *string `json:"image_url"`
	ID        int64   `json:"id"`
}

func (q *Queries) UpdateDiscussionPost(ctx context.Context, arg UpdateDiscussionPostParams) (DiscussionPost, error) {
	row := q.db.QueryRowContext(ctx, updateDiscussionPost,
		arg.Title,
		arg.Body,
		arg.Pinned,
		arg.EventDate,
		arg.Location,
		arg.ImageUrl,
		arg.ID,
	)
	var i DiscussionPost
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Body,
		&i.UserID,
		&i.Pinned,
		&i.Type,
		&i.EventDate,
		&i.Location,
		&i.ImageUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const upsertDiscussionCommentVote = `-- name: UpsertDiscussionCommentVote :one
INSERT INTO discussion_comment_votes (
    comment_id, user_id, vote
) VALUES (
    ?1, ?2, ?3
)
ON CONFLICT (comment_id, user_id) DO UPDATE SET
    vote = excluded.vote
RETURNING comment_id, user_id, vote
`

type UpsertDiscussionCommentVoteParams struct {
	CommentID int64 `json:"comment_id"`
	UserID    int64 `json:"user_id"`
	Vote      int64 `json:"vote"`
}

func (q *Queries) UpsertDiscussionCommentVote(ctx context.Context, arg UpsertDiscussionCommentVoteParams) (DiscussionCommentVote, error) {
	row := q.db.QueryRowContext(ctx, upsertDiscussionCommentVote, arg.CommentID, arg.UserID, arg.Vote)
	var i DiscussionCommentVote
	err := row.Scan(&i.CommentID, &i.UserID, &i.Vote)
	return i, err
}

const upsertDiscussionVote = `-- name: UpsertDiscussionVote :one
INSERT INTO discussion_votes (
    post_id, user_id, vote
) VALUES (
    ?1, ?2, ?3
)
ON CONFLICT (post_id, user_id) DO UPDATE SET
    vote = excluded.vote
RETURNING post_id, user_id, vote
`

type UpsertDiscussionVoteParams struct {
	PostID int64 `json:"post_id"`
	UserID int64 `json:"user_id"`
	Vote   int64 `json:"vote"`
}

func (q *Queries) UpsertDiscussionVote(ctx context.Context, arg UpsertDiscussionVoteParams) (DiscussionVote, error) {
	row := q.db.QueryRowContext(ctx, upsertDiscussionVote, arg.PostID, arg.UserID, arg.Vote)
	var i DiscussionVote
	err := row.Scan(&i.PostID, &i.UserID, &i.Vote)
	return i, err
}
