// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: events.sql

package database

import (
	"context"
)

const createEvent = `-- name: CreateEvent :one
INSERT INTO events (id, title, cover_path) VALUES (?1, ?2, ?3) RETURNING id, title, cover_path, created_at, updated_at, deleted_at
`

type CreateEventParams struct {
	ID        int64   `json:"id"`
	Title     string  `json:"title"`
	CoverPath *string `json:"cover_path"`
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error) {
	row := q.db.QueryRowContext(ctx, createEvent, arg.ID, arg.Title, arg.CoverPath)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.CoverPath,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createMedia = `-- name: CreateMedia :one
INSERT INTO media (
  id, event_id, user_id, title, description, 
  access_key, mime_type, nbytes
) VALUES (
  ?1, ?2, ?3, ?4, 
  ?5, ?6, ?7, ?8
) RETURNING id, event_id, user_id, title, description, access_key, mime_type, nbytes, created_at, updated_at, deleted_at
`

type CreateMediaParams struct {
	ID          int64   `json:"id"`
	EventID     int64   `json:"event_id"`
	UserID      int64   `json:"user_id"`
	Title       *string `json:"title"`
	Description *string `json:"description"`
	AccessKey   string  `json:"access_key"`
	MimeType    string  `json:"mime_type"`
	Nbytes      int64   `json:"nbytes"`
}

func (q *Queries) CreateMedia(ctx context.Context, arg CreateMediaParams) (Medium, error) {
	row := q.db.QueryRowContext(ctx, createMedia,
		arg.ID,
		arg.EventID,
		arg.UserID,
		arg.Title,
		arg.Description,
		arg.AccessKey,
		arg.MimeType,
		arg.Nbytes,
	)
	var i Medium
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.AccessKey,
		&i.MimeType,
		&i.Nbytes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteMedia = `-- name: DeleteMedia :exec
UPDATE media SET deleted_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now') WHERE id = ?1
`

func (q *Queries) DeleteMedia(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteMedia, id)
	return err
}

const getEvent = `-- name: GetEvent :one
SELECT id, title, cover_path, created_at, updated_at, deleted_at FROM events WHERE id = ?1 AND deleted_at IS NULL LIMIT 1
`

func (q *Queries) GetEvent(ctx context.Context, id int64) (Event, error) {
	row := q.db.QueryRowContext(ctx, getEvent, id)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.CoverPath,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getMedia = `-- name: GetMedia :one
SELECT m.id, m.event_id, m.user_id, m.title, m.description, m.access_key, m.mime_type, m.nbytes, m.created_at, m.updated_at, m.deleted_at, CAST(CASE WHEN u.private = 1 THEN 'Anonym' ELSE u.name END AS TEXT) as uploader_name 
FROM media m
JOIN users u ON m.user_id = u.id
WHERE m.id = ?1 AND m.deleted_at IS NULL LIMIT 1
`

type GetMediaRow struct {
	ID           int64   `json:"id"`
	EventID      int64   `json:"event_id"`
	UserID       int64   `json:"user_id"`
	Title        *string `json:"title"`
	Description  *string `json:"description"`
	AccessKey    string  `json:"access_key"`
	MimeType     string  `json:"mime_type"`
	Nbytes       int64   `json:"nbytes"`
	CreatedAt    string  `json:"created_at"`
	UpdatedAt    string  `json:"updated_at"`
	DeletedAt    *string `json:"deleted_at"`
	UploaderName string  `json:"uploader_name"`
}

func (q *Queries) GetMedia(ctx context.Context, id int64) (GetMediaRow, error) {
	row := q.db.QueryRowContext(ctx, getMedia, id)
	var i GetMediaRow
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.AccessKey,
		&i.MimeType,
		&i.Nbytes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.UploaderName,
	)
	return i, err
}

const listEvents = `-- name: ListEvents :many
SELECT id, title, cover_path, created_at, updated_at, deleted_at FROM events WHERE deleted_at IS NULL ORDER BY created_at DESC
`

func (q *Queries) ListEvents(ctx context.Context) ([]Event, error) {
	rows, err := q.db.QueryContext(ctx, listEvents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.CoverPath,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMediaByEvent = `-- name: ListMediaByEvent :many
SELECT m.id, m.event_id, m.user_id, m.title, m.description, m.access_key, m.mime_type, m.nbytes, m.created_at, m.updated_at, m.deleted_at, CAST(CASE WHEN u.private = 1 THEN 'Anonym' ELSE u.name END AS TEXT) as uploader_name 
FROM media m
JOIN users u ON m.user_id = u.id
WHERE event_id = ?1 AND m.deleted_at IS NULL
ORDER BY m.created_at DESC
`

type ListMediaByEventRow struct {
	ID           int64   `json:"id"`
	EventID      int64   `json:"event_id"`
	UserID       int64   `json:"user_id"`
	Title        *string `json:"title"`
	Description  *string `json:"description"`
	AccessKey    string  `json:"access_key"`
	MimeType     string  `json:"mime_type"`
	Nbytes       int64   `json:"nbytes"`
	CreatedAt    string  `json:"created_at"`
	UpdatedAt    string  `json:"updated_at"`
	DeletedAt    *string `json:"deleted_at"`
	UploaderName string  `json:"uploader_name"`
}

func (q *Queries) ListMediaByEvent(ctx context.Context, eventID int64) ([]ListMediaByEventRow, error) {
	rows, err := q.db.QueryContext(ctx, listMediaByEvent, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMediaByEventRow
	for rows.Next() {
		var i ListMediaByEventRow
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.UserID,
			&i.Title,
			&i.Description,
			&i.AccessKey,
			&i.MimeType,
			&i.Nbytes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.UploaderName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
