// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: exams.sql

package database

import (
	"context"
)

const createExam = `-- name: CreateExam :one
INSERT INTO exams (
  id, userid, programid, version, moduleid, exam_date, 
  accesskey, mime_type, nbytes, checksum, comment
) VALUES (
  ?1, ?2, ?3, ?4, 
  ?5, ?6, ?7, 
  ?8, ?9, ?10, ?11
) RETURNING id, userid, programid, version, moduleid, comment, exam_date, uploaded_at, accesskey, mime_type, nbytes, checksum
`

type CreateExamParams struct {
	ID        string  `json:"id"`
	Userid    string  `json:"userid"`
	Programid int64   `json:"programid"`
	Version   string  `json:"version"`
	Moduleid  *int64  `json:"moduleid"`
	ExamDate  string  `json:"exam_date"`
	Accesskey string  `json:"accesskey"`
	MimeType  string  `json:"mime_type"`
	Nbytes    int64   `json:"nbytes"`
	Checksum  string  `json:"checksum"`
	Comment   *string `json:"comment"`
}

func (q *Queries) CreateExam(ctx context.Context, arg CreateExamParams) (Exam, error) {
	row := q.db.QueryRowContext(ctx, createExam,
		arg.ID,
		arg.Userid,
		arg.Programid,
		arg.Version,
		arg.Moduleid,
		arg.ExamDate,
		arg.Accesskey,
		arg.MimeType,
		arg.Nbytes,
		arg.Checksum,
		arg.Comment,
	)
	var i Exam
	err := row.Scan(
		&i.ID,
		&i.Userid,
		&i.Programid,
		&i.Version,
		&i.Moduleid,
		&i.Comment,
		&i.ExamDate,
		&i.UploadedAt,
		&i.Accesskey,
		&i.MimeType,
		&i.Nbytes,
		&i.Checksum,
	)
	return i, err
}

const deleteExam = `-- name: DeleteExam :exec
DELETE FROM exams WHERE id = ?1
`

func (q *Queries) DeleteExam(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteExam, id)
	return err
}

const getExam = `-- name: GetExam :one
SELECT id, userid, programid, version, moduleid, comment, exam_date, uploaded_at, accesskey, mime_type, nbytes, checksum FROM exams WHERE id = ?1 LIMIT 1
`

func (q *Queries) GetExam(ctx context.Context, id string) (Exam, error) {
	row := q.db.QueryRowContext(ctx, getExam, id)
	var i Exam
	err := row.Scan(
		&i.ID,
		&i.Userid,
		&i.Programid,
		&i.Version,
		&i.Moduleid,
		&i.Comment,
		&i.ExamDate,
		&i.UploadedAt,
		&i.Accesskey,
		&i.MimeType,
		&i.Nbytes,
		&i.Checksum,
	)
	return i, err
}

const listExams = `-- name: ListExams :many
SELECT e.id, e.programid, e.version, e.exam_date, e.uploaded_at, e.moduleid, e.comment,
       m.name as module_name, u.name as uploader_name
FROM exams e
JOIN modules m ON e.moduleid = m.id
JOIN users u ON e.userid = u.id
WHERE (?1 IS NULL OR e.programid = ?1)
  AND (?2 IS NULL OR e.version = ?2)
  AND (?3 IS NULL OR e.moduleid = ?3)
ORDER BY e.exam_date DESC
`

type ListExamsParams struct {
	Programid interface{} `json:"programid"`
	Version   interface{} `json:"version"`
	Moduleid  interface{} `json:"moduleid"`
}

type ListExamsRow struct {
	ID           string  `json:"id"`
	Programid    int64   `json:"programid"`
	Version      string  `json:"version"`
	ExamDate     string  `json:"exam_date"`
	UploadedAt   string  `json:"uploaded_at"`
	Moduleid     *int64  `json:"moduleid"`
	Comment      *string `json:"comment"`
	ModuleName   string  `json:"module_name"`
	UploaderName string  `json:"uploader_name"`
}

func (q *Queries) ListExams(ctx context.Context, arg ListExamsParams) ([]ListExamsRow, error) {
	rows, err := q.db.QueryContext(ctx, listExams, arg.Programid, arg.Version, arg.Moduleid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListExamsRow
	for rows.Next() {
		var i ListExamsRow
		if err := rows.Scan(
			&i.ID,
			&i.Programid,
			&i.Version,
			&i.ExamDate,
			&i.UploadedAt,
			&i.Moduleid,
			&i.Comment,
			&i.ModuleName,
			&i.UploaderName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateExam = `-- name: UpdateExam :one
UPDATE exams
SET programid = ?1,
    version = ?2,
    moduleid = ?3,
    exam_date = ?4,
    comment = ?5
WHERE id = ?6
RETURNING id, userid, programid, version, moduleid, comment, exam_date, uploaded_at, accesskey, mime_type, nbytes, checksum
`

type UpdateExamParams struct {
	Programid int64   `json:"programid"`
	Version   string  `json:"version"`
	Moduleid  *int64  `json:"moduleid"`
	ExamDate  string  `json:"exam_date"`
	Comment   *string `json:"comment"`
	ID        string  `json:"id"`
}

func (q *Queries) UpdateExam(ctx context.Context, arg UpdateExamParams) (Exam, error) {
	row := q.db.QueryRowContext(ctx, updateExam,
		arg.Programid,
		arg.Version,
		arg.Moduleid,
		arg.ExamDate,
		arg.Comment,
		arg.ID,
	)
	var i Exam
	err := row.Scan(
		&i.ID,
		&i.Userid,
		&i.Programid,
		&i.Version,
		&i.Moduleid,
		&i.Comment,
		&i.ExamDate,
		&i.UploadedAt,
		&i.Accesskey,
		&i.MimeType,
		&i.Nbytes,
		&i.Checksum,
	)
	return i, err
}
