// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: forum.sql

package database

import (
	"context"
)

const countForumPosts = `-- name: CountForumPosts :one
SELECT COUNT(*) FROM forum_posts p
WHERE (?1 IS NULL OR p.type = ?1)
  AND (?2 IS NULL OR (lower(p.title) LIKE '%' || lower(?2) || '%' OR lower(p.body) LIKE '%' || lower(?2) || '%'))
  AND p.active = 1
`

type CountForumPostsParams struct {
	Type  interface{} `json:"type"`
	Query interface{} `json:"query"`
}

func (q *Queries) CountForumPosts(ctx context.Context, arg CountForumPostsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countForumPosts, arg.Type, arg.Query)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createForumComment = `-- name: CreateForumComment :one
INSERT INTO forum_comments (
    id, post_id, author_id, parent_id, text
) VALUES (
    ?1, ?2, ?3, ?4, ?5
)
RETURNING id, post_id, author_id, parent_id, text, created_at, updated_at, active
`

type CreateForumCommentParams struct {
	ID       string  `json:"id"`
	PostID   string  `json:"post_id"`
	AuthorID string  `json:"author_id"`
	ParentID *string `json:"parent_id"`
	Text     string  `json:"text"`
}

func (q *Queries) CreateForumComment(ctx context.Context, arg CreateForumCommentParams) (ForumComment, error) {
	row := q.db.QueryRowContext(ctx, createForumComment,
		arg.ID,
		arg.PostID,
		arg.AuthorID,
		arg.ParentID,
		arg.Text,
	)
	var i ForumComment
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.AuthorID,
		&i.ParentID,
		&i.Text,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Active,
	)
	return i, err
}

const createForumPost = `-- name: CreateForumPost :one
INSERT INTO forum_posts (
    id, title, body, author_id, type, pinned, event_date, location, programs, tags, image_url, links
) VALUES (
    ?1, ?2, ?3, ?4,
    COALESCE(?5, 'forum'),
    COALESCE(?6, 0),
    ?7,
    ?8,
    COALESCE(?9, '[]'),
    COALESCE(?10, '[]'),
    ?11,
    COALESCE(?12, '[]')
)
RETURNING id, title, body, author_id, created_at, updated_at, pinned, type, programs, tags, event_date, location, image_url, links, active
`

type CreateForumPostParams struct {
	ID        string      `json:"id"`
	Title     string      `json:"title"`
	Body      string      `json:"body"`
	AuthorID  string      `json:"author_id"`
	Type      interface{} `json:"type"`
	Pinned    interface{} `json:"pinned"`
	EventDate *string     `json:"event_date"`
	Location  *string     `json:"location"`
	Programs  interface{} `json:"programs"`
	Tags      interface{} `json:"tags"`
	ImageUrl  *string     `json:"image_url"`
	Links     interface{} `json:"links"`
}

func (q *Queries) CreateForumPost(ctx context.Context, arg CreateForumPostParams) (ForumPost, error) {
	row := q.db.QueryRowContext(ctx, createForumPost,
		arg.ID,
		arg.Title,
		arg.Body,
		arg.AuthorID,
		arg.Type,
		arg.Pinned,
		arg.EventDate,
		arg.Location,
		arg.Programs,
		arg.Tags,
		arg.ImageUrl,
		arg.Links,
	)
	var i ForumPost
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Body,
		&i.AuthorID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Pinned,
		&i.Type,
		&i.Programs,
		&i.Tags,
		&i.EventDate,
		&i.Location,
		&i.ImageUrl,
		&i.Links,
		&i.Active,
	)
	return i, err
}

const deleteForumComment = `-- name: DeleteForumComment :exec
UPDATE forum_comments
SET active = 0
WHERE id = ?1
`

func (q *Queries) DeleteForumComment(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteForumComment, id)
	return err
}

const deleteForumPost = `-- name: DeleteForumPost :exec
UPDATE forum_posts
SET active = 0
WHERE id = ?1
`

func (q *Queries) DeleteForumPost(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteForumPost, id)
	return err
}

const getForumComment = `-- name: GetForumComment :one
SELECT id, post_id, author_id, parent_id, text, created_at, updated_at, active FROM forum_comments WHERE id = ?1 LIMIT 1
`

func (q *Queries) GetForumComment(ctx context.Context, id string) (ForumComment, error) {
	row := q.db.QueryRowContext(ctx, getForumComment, id)
	var i ForumComment
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.AuthorID,
		&i.ParentID,
		&i.Text,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Active,
	)
	return i, err
}

const getForumPost = `-- name: GetForumPost :one
SELECT p.id, p.title, p.body, p.author_id, p.created_at, p.updated_at, p.pinned, p.type, p.programs, p.tags, p.event_date, p.location, p.image_url, p.links, p.active,
       CAST(CASE WHEN u.private = 1 THEN 'Anonym' ELSE u.name END AS TEXT) as author_name,
       CAST(COALESCE(u.avatar_url, '') AS TEXT) as author_avatar_url,
       (SELECT COUNT(*) FROM forum_comments WHERE post_id = p.id AND active = 1) as comment_count,
       (SELECT CAST(COALESCE(SUM(vote), 0) AS INTEGER) FROM forum_votes WHERE forum_votes.post_id = p.id) as votes,
       CAST(COALESCE((SELECT vote FROM forum_votes WHERE forum_votes.post_id = p.id AND forum_votes.user_id = ?1), 0) AS INTEGER) as user_vote
FROM forum_posts p
JOIN users u ON p.author_id = u.id
WHERE p.id = ?2
LIMIT 1
`

type GetForumPostParams struct {
	CurrentUserID *string `json:"current_user_id"`
	ID            string  `json:"id"`
}

type GetForumPostRow struct {
	ID              string  `json:"id"`
	Title           string  `json:"title"`
	Body            string  `json:"body"`
	AuthorID        string  `json:"author_id"`
	CreatedAt       string  `json:"created_at"`
	UpdatedAt       string  `json:"updated_at"`
	Pinned          int64   `json:"pinned"`
	Type            string  `json:"type"`
	Programs        string  `json:"programs"`
	Tags            string  `json:"tags"`
	EventDate       *string `json:"event_date"`
	Location        *string `json:"location"`
	ImageUrl        *string `json:"image_url"`
	Links           string  `json:"links"`
	Active          int64   `json:"active"`
	AuthorName      string  `json:"author_name"`
	AuthorAvatarUrl string  `json:"author_avatar_url"`
	CommentCount    int64   `json:"comment_count"`
	Votes           int64   `json:"votes"`
	UserVote        int64   `json:"user_vote"`
}

func (q *Queries) GetForumPost(ctx context.Context, arg GetForumPostParams) (GetForumPostRow, error) {
	row := q.db.QueryRowContext(ctx, getForumPost, arg.CurrentUserID, arg.ID)
	var i GetForumPostRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Body,
		&i.AuthorID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Pinned,
		&i.Type,
		&i.Programs,
		&i.Tags,
		&i.EventDate,
		&i.Location,
		&i.ImageUrl,
		&i.Links,
		&i.Active,
		&i.AuthorName,
		&i.AuthorAvatarUrl,
		&i.CommentCount,
		&i.Votes,
		&i.UserVote,
	)
	return i, err
}

const listForumComments = `-- name: ListForumComments :many
SELECT c.id, c.post_id, c.author_id, c.parent_id, c.text, c.created_at, c.updated_at, c.active,
       CAST(CASE WHEN u.private = 1 THEN 'Anonym' ELSE u.name END AS TEXT) as author_name,
       CAST(COALESCE(u.avatar_url, '') AS TEXT) as author_avatar_url,
       (SELECT CAST(COALESCE(SUM(vote), 0) AS INTEGER) FROM forum_comment_votes v WHERE v.comment_id = c.id) as votes,
       CAST(COALESCE((SELECT vote FROM forum_comment_votes v WHERE v.comment_id = c.id AND v.user_id = ?1), 0) AS INTEGER) as user_vote
FROM forum_comments c
JOIN users u ON c.author_id = u.id
WHERE c.post_id = ?2 AND c.active = 1
ORDER BY c.created_at ASC
`

type ListForumCommentsParams struct {
	CurrentUserID *string `json:"current_user_id"`
	PostID        string  `json:"post_id"`
}

type ListForumCommentsRow struct {
	ID              string  `json:"id"`
	PostID          string  `json:"post_id"`
	AuthorID        string  `json:"author_id"`
	ParentID        *string `json:"parent_id"`
	Text            string  `json:"text"`
	CreatedAt       string  `json:"created_at"`
	UpdatedAt       string  `json:"updated_at"`
	Active          int64   `json:"active"`
	AuthorName      string  `json:"author_name"`
	AuthorAvatarUrl string  `json:"author_avatar_url"`
	Votes           int64   `json:"votes"`
	UserVote        int64   `json:"user_vote"`
}

func (q *Queries) ListForumComments(ctx context.Context, arg ListForumCommentsParams) ([]ListForumCommentsRow, error) {
	rows, err := q.db.QueryContext(ctx, listForumComments, arg.CurrentUserID, arg.PostID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListForumCommentsRow
	for rows.Next() {
		var i ListForumCommentsRow
		if err := rows.Scan(
			&i.ID,
			&i.PostID,
			&i.AuthorID,
			&i.ParentID,
			&i.Text,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Active,
			&i.AuthorName,
			&i.AuthorAvatarUrl,
			&i.Votes,
			&i.UserVote,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listForumPosts = `-- name: ListForumPosts :many
SELECT p.id, p.title, p.body, p.author_id, p.created_at, p.updated_at, p.pinned, p.type, p.programs, p.tags, p.event_date, p.location, p.image_url, p.links, p.active,
       CAST(CASE WHEN u.private = 1 THEN 'Anonym' ELSE u.name END AS TEXT) as author_name,
       CAST(COALESCE(u.avatar_url, '') AS TEXT) as author_avatar_url,
       (SELECT COUNT(*) FROM forum_comments WHERE post_id = p.id AND active = 1) as comment_count,
       (SELECT CAST(COALESCE(SUM(v.vote), 0) AS INTEGER) FROM forum_votes v WHERE v.post_id = p.id) as votes,
       CAST(COALESCE((SELECT v.vote FROM forum_votes v WHERE v.post_id = p.id AND v.user_id = ?1), 0) AS INTEGER) as user_vote
FROM forum_posts p
JOIN users u ON p.author_id = u.id
WHERE (?2 IS NULL OR p.type = ?2)
  AND (?3 IS NULL OR (lower(p.title) LIKE '%' || lower(?3) || '%' OR lower(p.body) LIKE '%' || lower(?3) || '%'))
  AND p.active = 1
ORDER BY
    p.pinned DESC,
    p.created_at DESC
LIMIT ?5 OFFSET ?4
`

type ListForumPostsParams struct {
	CurrentUserID *string     `json:"current_user_id"`
	Type          interface{} `json:"type"`
	Query         interface{} `json:"query"`
	Offset        int64       `json:"offset"`
	Limit         int64       `json:"limit"`
}

type ListForumPostsRow struct {
	ID              string  `json:"id"`
	Title           string  `json:"title"`
	Body            string  `json:"body"`
	AuthorID        string  `json:"author_id"`
	CreatedAt       string  `json:"created_at"`
	UpdatedAt       string  `json:"updated_at"`
	Pinned          int64   `json:"pinned"`
	Type            string  `json:"type"`
	Programs        string  `json:"programs"`
	Tags            string  `json:"tags"`
	EventDate       *string `json:"event_date"`
	Location        *string `json:"location"`
	ImageUrl        *string `json:"image_url"`
	Links           string  `json:"links"`
	Active          int64   `json:"active"`
	AuthorName      string  `json:"author_name"`
	AuthorAvatarUrl string  `json:"author_avatar_url"`
	CommentCount    int64   `json:"comment_count"`
	Votes           int64   `json:"votes"`
	UserVote        int64   `json:"user_vote"`
}

func (q *Queries) ListForumPosts(ctx context.Context, arg ListForumPostsParams) ([]ListForumPostsRow, error) {
	rows, err := q.db.QueryContext(ctx, listForumPosts,
		arg.CurrentUserID,
		arg.Type,
		arg.Query,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListForumPostsRow
	for rows.Next() {
		var i ListForumPostsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Body,
			&i.AuthorID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Pinned,
			&i.Type,
			&i.Programs,
			&i.Tags,
			&i.EventDate,
			&i.Location,
			&i.ImageUrl,
			&i.Links,
			&i.Active,
			&i.AuthorName,
			&i.AuthorAvatarUrl,
			&i.CommentCount,
			&i.Votes,
			&i.UserVote,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listForumPostsTop = `-- name: ListForumPostsTop :many
SELECT p.id, p.title, p.body, p.author_id, p.created_at, p.updated_at, p.pinned, p.type, p.programs, p.tags, p.event_date, p.location, p.image_url, p.links, p.active,
       CAST(CASE WHEN u.private = 1 THEN 'Anonym' ELSE u.name END AS TEXT) as author_name,
       CAST(COALESCE(u.avatar_url, '') AS TEXT) as author_avatar_url,
       (SELECT COUNT(*) FROM forum_comments WHERE post_id = p.id AND active = 1) as comment_count,
       (SELECT CAST(COALESCE(SUM(v.vote), 0) AS INTEGER) FROM forum_votes v WHERE v.post_id = p.id) as votes,
       CAST(COALESCE((SELECT v.vote FROM forum_votes v WHERE v.post_id = p.id AND v.user_id = ?1), 0) AS INTEGER) as user_vote
FROM forum_posts p
JOIN users u ON p.author_id = u.id
WHERE (?2 IS NULL OR p.type = ?2)
  AND (?3 IS NULL OR (lower(p.title) LIKE '%' || lower(?3) || '%' OR lower(p.body) LIKE '%' || lower(?3) || '%'))
  AND p.active = 1
ORDER BY
    p.pinned DESC,
    votes DESC,
    p.created_at DESC
LIMIT ?5 OFFSET ?4
`

type ListForumPostsTopParams struct {
	CurrentUserID *string     `json:"current_user_id"`
	Type          interface{} `json:"type"`
	Query         interface{} `json:"query"`
	Offset        int64       `json:"offset"`
	Limit         int64       `json:"limit"`
}

type ListForumPostsTopRow struct {
	ID              string  `json:"id"`
	Title           string  `json:"title"`
	Body            string  `json:"body"`
	AuthorID        string  `json:"author_id"`
	CreatedAt       string  `json:"created_at"`
	UpdatedAt       string  `json:"updated_at"`
	Pinned          int64   `json:"pinned"`
	Type            string  `json:"type"`
	Programs        string  `json:"programs"`
	Tags            string  `json:"tags"`
	EventDate       *string `json:"event_date"`
	Location        *string `json:"location"`
	ImageUrl        *string `json:"image_url"`
	Links           string  `json:"links"`
	Active          int64   `json:"active"`
	AuthorName      string  `json:"author_name"`
	AuthorAvatarUrl string  `json:"author_avatar_url"`
	CommentCount    int64   `json:"comment_count"`
	Votes           int64   `json:"votes"`
	UserVote        int64   `json:"user_vote"`
}

func (q *Queries) ListForumPostsTop(ctx context.Context, arg ListForumPostsTopParams) ([]ListForumPostsTopRow, error) {
	rows, err := q.db.QueryContext(ctx, listForumPostsTop,
		arg.CurrentUserID,
		arg.Type,
		arg.Query,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListForumPostsTopRow
	for rows.Next() {
		var i ListForumPostsTopRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Body,
			&i.AuthorID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Pinned,
			&i.Type,
			&i.Programs,
			&i.Tags,
			&i.EventDate,
			&i.Location,
			&i.ImageUrl,
			&i.Links,
			&i.Active,
			&i.AuthorName,
			&i.AuthorAvatarUrl,
			&i.CommentCount,
			&i.Votes,
			&i.UserVote,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchForumPosts = `-- name: SearchForumPosts :many
SELECT p.id, p.title, p.body, p.author_id, p.created_at, p.updated_at, p.pinned, p.type, p.programs, p.tags, p.event_date, p.location, p.image_url, p.links, p.active,
       CAST(CASE WHEN u.private = 1 THEN 'Anonym' ELSE u.name END AS TEXT) as author_name,
       CAST(COALESCE(u.avatar_url, '') AS TEXT) as author_avatar_url,
       (SELECT COUNT(*) FROM forum_comments WHERE post_id = p.id AND active = 1) as comment_count,
       (SELECT CAST(COALESCE(SUM(v.vote), 0) AS INTEGER) FROM forum_votes v WHERE v.post_id = p.id) as votes,
       CAST(COALESCE((SELECT v.vote FROM forum_votes v WHERE v.post_id = p.id AND v.user_id = ?1), 0) AS INTEGER) as user_vote
FROM forum_posts p
JOIN users u ON p.author_id = u.id
WHERE (
  lower(p.title) LIKE '%' || lower(?2) || '%' OR
  lower(p.body) LIKE '%' || lower(?2) || '%'
) AND p.active = 1
ORDER BY 
    p.pinned DESC,
    p.created_at DESC
LIMIT 10
`

type SearchForumPostsParams struct {
	CurrentUserID *string `json:"current_user_id"`
	Query         string  `json:"query"`
}

type SearchForumPostsRow struct {
	ID              string  `json:"id"`
	Title           string  `json:"title"`
	Body            string  `json:"body"`
	AuthorID        string  `json:"author_id"`
	CreatedAt       string  `json:"created_at"`
	UpdatedAt       string  `json:"updated_at"`
	Pinned          int64   `json:"pinned"`
	Type            string  `json:"type"`
	Programs        string  `json:"programs"`
	Tags            string  `json:"tags"`
	EventDate       *string `json:"event_date"`
	Location        *string `json:"location"`
	ImageUrl        *string `json:"image_url"`
	Links           string  `json:"links"`
	Active          int64   `json:"active"`
	AuthorName      string  `json:"author_name"`
	AuthorAvatarUrl string  `json:"author_avatar_url"`
	CommentCount    int64   `json:"comment_count"`
	Votes           int64   `json:"votes"`
	UserVote        int64   `json:"user_vote"`
}

func (q *Queries) SearchForumPosts(ctx context.Context, arg SearchForumPostsParams) ([]SearchForumPostsRow, error) {
	rows, err := q.db.QueryContext(ctx, searchForumPosts, arg.CurrentUserID, arg.Query)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchForumPostsRow
	for rows.Next() {
		var i SearchForumPostsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Body,
			&i.AuthorID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Pinned,
			&i.Type,
			&i.Programs,
			&i.Tags,
			&i.EventDate,
			&i.Location,
			&i.ImageUrl,
			&i.Links,
			&i.Active,
			&i.AuthorName,
			&i.AuthorAvatarUrl,
			&i.CommentCount,
			&i.Votes,
			&i.UserVote,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateForumComment = `-- name: UpdateForumComment :one
UPDATE forum_comments
SET text = ?1,
    updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
WHERE id = ?2
RETURNING id, post_id, author_id, parent_id, text, created_at, updated_at, active
`

type UpdateForumCommentParams struct {
	Text string `json:"text"`
	ID   string `json:"id"`
}

func (q *Queries) UpdateForumComment(ctx context.Context, arg UpdateForumCommentParams) (ForumComment, error) {
	row := q.db.QueryRowContext(ctx, updateForumComment, arg.Text, arg.ID)
	var i ForumComment
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.AuthorID,
		&i.ParentID,
		&i.Text,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Active,
	)
	return i, err
}

const updateForumPost = `-- name: UpdateForumPost :one
UPDATE forum_posts
SET title = COALESCE(?1, title),
    body = COALESCE(?2, body),
    pinned = COALESCE(?3, pinned),
    event_date = COALESCE(?4, event_date),
    location = COALESCE(?5, location),
    image_url = COALESCE(?6, image_url),
    links = COALESCE(?7, links),
    programs = COALESCE(?8, programs),
    tags = COALESCE(?9, tags),
    updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
WHERE id = ?10
RETURNING id, title, body, author_id, created_at, updated_at, pinned, type, programs, tags, event_date, location, image_url, links, active
`

type UpdateForumPostParams struct {
	Title     *string `json:"title"`
	Body      *string `json:"body"`
	Pinned    *int64  `json:"pinned"`
	EventDate *string `json:"event_date"`
	Location  *string `json:"location"`
	ImageUrl  *string `json:"image_url"`
	Links     *string `json:"links"`
	Programs  *string `json:"programs"`
	Tags      *string `json:"tags"`
	ID        string  `json:"id"`
}

func (q *Queries) UpdateForumPost(ctx context.Context, arg UpdateForumPostParams) (ForumPost, error) {
	row := q.db.QueryRowContext(ctx, updateForumPost,
		arg.Title,
		arg.Body,
		arg.Pinned,
		arg.EventDate,
		arg.Location,
		arg.ImageUrl,
		arg.Links,
		arg.Programs,
		arg.Tags,
		arg.ID,
	)
	var i ForumPost
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Body,
		&i.AuthorID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Pinned,
		&i.Type,
		&i.Programs,
		&i.Tags,
		&i.EventDate,
		&i.Location,
		&i.ImageUrl,
		&i.Links,
		&i.Active,
	)
	return i, err
}

const upsertForumCommentVote = `-- name: UpsertForumCommentVote :one
INSERT INTO forum_comment_votes (
    comment_id, user_id, vote
) VALUES (
    ?1, ?2, ?3
)
ON CONFLICT (comment_id, user_id) DO UPDATE SET
    vote = excluded.vote
RETURNING comment_id, user_id, vote
`

type UpsertForumCommentVoteParams struct {
	CommentID string `json:"comment_id"`
	UserID    string `json:"user_id"`
	Vote      int64  `json:"vote"`
}

func (q *Queries) UpsertForumCommentVote(ctx context.Context, arg UpsertForumCommentVoteParams) (ForumCommentVote, error) {
	row := q.db.QueryRowContext(ctx, upsertForumCommentVote, arg.CommentID, arg.UserID, arg.Vote)
	var i ForumCommentVote
	err := row.Scan(&i.CommentID, &i.UserID, &i.Vote)
	return i, err
}

const upsertForumVote = `-- name: UpsertForumVote :one
INSERT INTO forum_votes (
    post_id, user_id, vote
) VALUES (
    ?1, ?2, ?3
)
ON CONFLICT (post_id, user_id) DO UPDATE SET
    vote = excluded.vote
RETURNING post_id, user_id, vote
`

type UpsertForumVoteParams struct {
	PostID string `json:"post_id"`
	UserID string `json:"user_id"`
	Vote   int64  `json:"vote"`
}

func (q *Queries) UpsertForumVote(ctx context.Context, arg UpsertForumVoteParams) (ForumVote, error) {
	row := q.db.QueryRowContext(ctx, upsertForumVote, arg.PostID, arg.UserID, arg.Vote)
	var i ForumVote
	err := row.Scan(&i.PostID, &i.UserID, &i.Vote)
	return i, err
}
