// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: media.sql

package database

import (
	"context"
)

const createEvent = `-- name: CreateEvent :one
INSERT INTO events (id, title, cover_path) VALUES (?, ?, ?) RETURNING id, title, cover_path, created_at
`

type CreateEventParams struct {
	ID        string  `json:"id"`
	Title     string  `json:"title"`
	CoverPath *string `json:"cover_path"`
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error) {
	row := q.db.QueryRowContext(ctx, createEvent, arg.ID, arg.Title, arg.CoverPath)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.CoverPath,
		&i.CreatedAt,
	)
	return i, err
}

const createMedia = `-- name: CreateMedia :one
INSERT INTO media (
  id, event_id, userid, title, description, 
  accesskey, mime_type, nbytes
) VALUES (
  ?, ?, ?, ?, ?, ?, ?, ?
) RETURNING id, event_id, userid, title, description, accesskey, mime_type, nbytes, uploaded_at
`

type CreateMediaParams struct {
	ID          string  `json:"id"`
	EventID     string  `json:"event_id"`
	Userid      string  `json:"userid"`
	Title       *string `json:"title"`
	Description *string `json:"description"`
	Accesskey   string  `json:"accesskey"`
	MimeType    string  `json:"mime_type"`
	Nbytes      int64   `json:"nbytes"`
}

func (q *Queries) CreateMedia(ctx context.Context, arg CreateMediaParams) (Medium, error) {
	row := q.db.QueryRowContext(ctx, createMedia,
		arg.ID,
		arg.EventID,
		arg.Userid,
		arg.Title,
		arg.Description,
		arg.Accesskey,
		arg.MimeType,
		arg.Nbytes,
	)
	var i Medium
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.Userid,
		&i.Title,
		&i.Description,
		&i.Accesskey,
		&i.MimeType,
		&i.Nbytes,
		&i.UploadedAt,
	)
	return i, err
}

const deleteMedia = `-- name: DeleteMedia :exec
DELETE FROM media WHERE id = ?
`

func (q *Queries) DeleteMedia(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteMedia, id)
	return err
}

const getEvent = `-- name: GetEvent :one
SELECT id, title, cover_path, created_at FROM events WHERE id = ? LIMIT 1
`

func (q *Queries) GetEvent(ctx context.Context, id string) (Event, error) {
	row := q.db.QueryRowContext(ctx, getEvent, id)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.CoverPath,
		&i.CreatedAt,
	)
	return i, err
}

const getMedia = `-- name: GetMedia :one
SELECT m.id, m.event_id, m.userid, m.title, m.description, m.accesskey, m.mime_type, m.nbytes, m.uploaded_at, CAST(CASE WHEN u.private = 1 THEN 'Anonym' ELSE u.name END AS TEXT) as uploader_name 
FROM media m
JOIN users u ON m.userid = u.id
WHERE m.id = ? LIMIT 1
`

type GetMediaRow struct {
	ID           string  `json:"id"`
	EventID      string  `json:"event_id"`
	Userid       string  `json:"userid"`
	Title        *string `json:"title"`
	Description  *string `json:"description"`
	Accesskey    string  `json:"accesskey"`
	MimeType     string  `json:"mime_type"`
	Nbytes       int64   `json:"nbytes"`
	UploadedAt   string  `json:"uploaded_at"`
	UploaderName string  `json:"uploader_name"`
}

func (q *Queries) GetMedia(ctx context.Context, id string) (GetMediaRow, error) {
	row := q.db.QueryRowContext(ctx, getMedia, id)
	var i GetMediaRow
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.Userid,
		&i.Title,
		&i.Description,
		&i.Accesskey,
		&i.MimeType,
		&i.Nbytes,
		&i.UploadedAt,
		&i.UploaderName,
	)
	return i, err
}

const listEvents = `-- name: ListEvents :many
SELECT id, title, cover_path, created_at FROM events ORDER BY created_at DESC
`

func (q *Queries) ListEvents(ctx context.Context) ([]Event, error) {
	rows, err := q.db.QueryContext(ctx, listEvents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.CoverPath,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMediaByEvent = `-- name: ListMediaByEvent :many
SELECT m.id, m.event_id, m.userid, m.title, m.description, m.accesskey, m.mime_type, m.nbytes, m.uploaded_at, CAST(CASE WHEN u.private = 1 THEN 'Anonym' ELSE u.name END AS TEXT) as uploader_name 
FROM media m
JOIN users u ON m.userid = u.id
WHERE event_id = ?
ORDER BY uploaded_at DESC
`

type ListMediaByEventRow struct {
	ID           string  `json:"id"`
	EventID      string  `json:"event_id"`
	Userid       string  `json:"userid"`
	Title        *string `json:"title"`
	Description  *string `json:"description"`
	Accesskey    string  `json:"accesskey"`
	MimeType     string  `json:"mime_type"`
	Nbytes       int64   `json:"nbytes"`
	UploadedAt   string  `json:"uploaded_at"`
	UploaderName string  `json:"uploader_name"`
}

func (q *Queries) ListMediaByEvent(ctx context.Context, eventID string) ([]ListMediaByEventRow, error) {
	rows, err := q.db.QueryContext(ctx, listMediaByEvent, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMediaByEventRow
	for rows.Next() {
		var i ListMediaByEventRow
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.Userid,
			&i.Title,
			&i.Description,
			&i.Accesskey,
			&i.MimeType,
			&i.Nbytes,
			&i.UploadedAt,
			&i.UploaderName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
