// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
)

type Comment struct {
	ID        string `json:"id"`
	Postid    string `json:"postid"`
	Userid    string `json:"userid"`
	Body      string `json:"body"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
}

type Exam struct {
	ID         string `json:"id"`
	Userid     string `json:"userid"`
	Programid  int64  `json:"programid"`
	Version    string `json:"version"`
	ExamDate   string `json:"exam_date"`
	UploadedAt string `json:"uploaded_at"`
	Accesskey  string `json:"accesskey"`
	MimeType   string `json:"mime_type"`
	Nbytes     int64  `json:"nbytes"`
	Checksum   string `json:"checksum"`
}

type Post struct {
	ID        string         `json:"id"`
	Userid    string         `json:"userid"`
	Title     string         `json:"title"`
	Body      string         `json:"body"`
	CreatedAt string         `json:"created_at"`
	UpdatedAt string         `json:"updated_at"`
	Deleted   sql.NullString `json:"deleted"`
}

type Program struct {
	ID        int64  `json:"id"`
	Name      string `json:"name"`
	CreatedAt string `json:"created_at"`
}

type ProgramVersion struct {
	Programid int64  `json:"programid"`
	Name      string `json:"name"`
}

type Session struct {
	ID        string `json:"id"`
	Userid    string `json:"userid"`
	CreatedAt string `json:"created_at"`
	LastSeen  string `json:"last_seen"`
	ExpiresAt string `json:"expires_at"`
}

type User struct {
	ID                string         `json:"id"`
	Email             string         `json:"email"`
	Name              string         `json:"name"`
	Password          string         `json:"password"`
	Role              string         `json:"role"`
	Active            int64          `json:"active"`
	Verified          int64          `json:"verified"`
	VerifiedAt        sql.NullString `json:"verified_at"`
	VerifiedUntil     sql.NullString `json:"verified_until"`
	Programid         int64          `json:"programid"`
	CreatedAt         string         `json:"created_at"`
	UpdatedAt         string         `json:"updated_at"`
	VerificationToken sql.NullString `json:"verification_token"`
}
