// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

type Activity struct {
	ID         int64   `json:"id"`
	UserID     int64   `json:"user_id"`
	Type       string  `json:"type"`
	TargetID   string  `json:"target_id"`
	TargetName *string `json:"target_name"`
	CreatedAt  string  `json:"created_at"`
	UpdatedAt  string  `json:"updated_at"`
	DeletedAt  *string `json:"deleted_at"`
}

type Archive struct {
	ID          int64   `json:"id"`
	GroupID     int64   `json:"group_id"`
	UserID      int64   `json:"user_id"`
	ModuleID    int64   `json:"module_id"`
	Version     string  `json:"version"`
	ExamDate    string  `json:"exam_date"`
	Comment     *string `json:"comment"`
	EditVersion int64   `json:"edit_version"`
	IsLatest    int64   `json:"is_latest"`
	AccessKey   string  `json:"access_key"`
	MimeType    string  `json:"mime_type"`
	Nbytes      int64   `json:"nbytes"`
	Checksum    string  `json:"checksum"`
	CreatedAt   string  `json:"created_at"`
	UpdatedAt   string  `json:"updated_at"`
	DeletedAt   *string `json:"deleted_at"`
}

type DiscussionComment struct {
	ID        int64   `json:"id"`
	PostID    int64   `json:"post_id"`
	UserID    int64   `json:"user_id"`
	ParentID  *int64  `json:"parent_id"`
	Text      string  `json:"text"`
	CreatedAt string  `json:"created_at"`
	UpdatedAt string  `json:"updated_at"`
	DeletedAt *string `json:"deleted_at"`
}

type DiscussionCommentVote struct {
	CommentID int64 `json:"comment_id"`
	UserID    int64 `json:"user_id"`
	Vote      int64 `json:"vote"`
}

type DiscussionPost struct {
	ID        int64   `json:"id"`
	Title     string  `json:"title"`
	Body      string  `json:"body"`
	UserID    int64   `json:"user_id"`
	Pinned    int64   `json:"pinned"`
	Type      string  `json:"type"`
	EventDate *string `json:"event_date"`
	Location  *string `json:"location"`
	ImageUrl  *string `json:"image_url"`
	CreatedAt string  `json:"created_at"`
	UpdatedAt string  `json:"updated_at"`
	DeletedAt *string `json:"deleted_at"`
}

type DiscussionPostLink struct {
	ID     int64   `json:"id"`
	PostID int64   `json:"post_id"`
	Url    string  `json:"url"`
	Label  *string `json:"label"`
}

type DiscussionPostProgram struct {
	PostID    int64 `json:"post_id"`
	ProgramID int64 `json:"program_id"`
}

type DiscussionPostTag struct {
	PostID int64  `json:"post_id"`
	Tag    string `json:"tag"`
}

type DiscussionVote struct {
	PostID int64 `json:"post_id"`
	UserID int64 `json:"user_id"`
	Vote   int64 `json:"vote"`
}

type Event struct {
	ID        int64   `json:"id"`
	Title     string  `json:"title"`
	CoverPath *string `json:"cover_path"`
	CreatedAt string  `json:"created_at"`
	UpdatedAt string  `json:"updated_at"`
	DeletedAt *string `json:"deleted_at"`
}

type GlobalConfig struct {
	ID             int64  `json:"id"`
	OfficeOccupied int64  `json:"office_occupied"`
	UpdatedAt      string `json:"updated_at"`
}

type Medium struct {
	ID          int64   `json:"id"`
	EventID     int64   `json:"event_id"`
	UserID      int64   `json:"user_id"`
	Title       *string `json:"title"`
	Description *string `json:"description"`
	AccessKey   string  `json:"access_key"`
	MimeType    string  `json:"mime_type"`
	Nbytes      int64   `json:"nbytes"`
	CreatedAt   string  `json:"created_at"`
	UpdatedAt   string  `json:"updated_at"`
	DeletedAt   *string `json:"deleted_at"`
}

type Module struct {
	ID        int64   `json:"id"`
	ProgramID int64   `json:"program_id"`
	Name      string  `json:"name"`
	Alias     *string `json:"alias"`
	CreatedAt string  `json:"created_at"`
	UpdatedAt string  `json:"updated_at"`
	DeletedAt *string `json:"deleted_at"`
}

type Notification struct {
	ID        int64   `json:"id"`
	UserID    int64   `json:"user_id"`
	Title     string  `json:"title"`
	Message   string  `json:"message"`
	Type      string  `json:"type"`
	Link      string  `json:"link"`
	Read      int64   `json:"read"`
	CreatedAt string  `json:"created_at"`
	UpdatedAt string  `json:"updated_at"`
	DeletedAt *string `json:"deleted_at"`
}

type Program struct {
	ID        int64   `json:"id"`
	Name      string  `json:"name"`
	CreatedAt string  `json:"created_at"`
	UpdatedAt string  `json:"updated_at"`
	DeletedAt *string `json:"deleted_at"`
}

type ProgramVersion struct {
	ProgramID int64  `json:"program_id"`
	Name      string `json:"name"`
}

type RefActivityType struct {
	Type string `json:"type"`
}

type RefDiscussionType struct {
	Type string `json:"type"`
}

type RefNotificationType struct {
	Type string `json:"type"`
}

type RefUserRole struct {
	Role string `json:"role"`
}

type Session struct {
	ID        string  `json:"id"`
	UserID    int64   `json:"user_id"`
	UserAgent *string `json:"user_agent"`
	IpAddress *string `json:"ip_address"`
	CreatedAt string  `json:"created_at"`
	LastSeen  string  `json:"last_seen"`
	ExpiresAt string  `json:"expires_at"`
}

type User struct {
	ID                int64   `json:"id"`
	Email             string  `json:"email"`
	Name              string  `json:"name"`
	Password          string  `json:"password"`
	Role              string  `json:"role"`
	Active            int64   `json:"active"`
	Verified          int64   `json:"verified"`
	VerifiedAt        *string `json:"verified_at"`
	VerificationToken *string `json:"verification_token"`
	ProgramID         *int64  `json:"program_id"`
	Theme             string  `json:"theme"`
	Private           int64   `json:"private"`
	AvatarUrl         *string `json:"avatar_url"`
	CreatedAt         string  `json:"created_at"`
	UpdatedAt         string  `json:"updated_at"`
	DeletedAt         *string `json:"deleted_at"`
}
