// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: modules.sql

package database

import (
	"context"
)

const createModule = `-- name: CreateModule :one
INSERT INTO modules (programid, name, alias) 
VALUES (?1, ?2, ?3) 
RETURNING id, programid, name, alias, created_at
`

type CreateModuleParams struct {
	Programid string  `json:"programid"`
	Name      string  `json:"name"`
	Alias     *string `json:"alias"`
}

func (q *Queries) CreateModule(ctx context.Context, arg CreateModuleParams) (Module, error) {
	row := q.db.QueryRowContext(ctx, createModule, arg.Programid, arg.Name, arg.Alias)
	var i Module
	err := row.Scan(
		&i.ID,
		&i.Programid,
		&i.Name,
		&i.Alias,
		&i.CreatedAt,
	)
	return i, err
}

const getModule = `-- name: GetModule :one
SELECT id, programid, name, alias, created_at FROM modules WHERE id = ?1 LIMIT 1
`

func (q *Queries) GetModule(ctx context.Context, id string) (Module, error) {
	row := q.db.QueryRowContext(ctx, getModule, id)
	var i Module
	err := row.Scan(
		&i.ID,
		&i.Programid,
		&i.Name,
		&i.Alias,
		&i.CreatedAt,
	)
	return i, err
}

const listModulesByProgram = `-- name: ListModulesByProgram :many
SELECT id, programid, name, alias, created_at FROM modules 
WHERE programid = ?1 
ORDER BY name
`

func (q *Queries) ListModulesByProgram(ctx context.Context, programid string) ([]Module, error) {
	rows, err := q.db.QueryContext(ctx, listModulesByProgram, programid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Module
	for rows.Next() {
		var i Module
		if err := rows.Scan(
			&i.ID,
			&i.Programid,
			&i.Name,
			&i.Alias,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
