// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: modules.sql

package database

import (
	"context"
)

const createModule = `-- name: CreateModule :one
INSERT INTO modules (programid, name) 
VALUES (?1, ?2) 
RETURNING id, programid, name, created_at
`

type CreateModuleParams struct {
	Programid int64  `json:"programid"`
	Name      string `json:"name"`
}

func (q *Queries) CreateModule(ctx context.Context, arg CreateModuleParams) (Module, error) {
	row := q.db.QueryRowContext(ctx, createModule, arg.Programid, arg.Name)
	var i Module
	err := row.Scan(
		&i.ID,
		&i.Programid,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const listModulesByProgram = `-- name: ListModulesByProgram :many
SELECT id, programid, name, created_at FROM modules 
WHERE programid = ?1 
ORDER BY name
`

func (q *Queries) ListModulesByProgram(ctx context.Context, programid int64) ([]Module, error) {
	rows, err := q.db.QueryContext(ctx, listModulesByProgram, programid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Module
	for rows.Next() {
		var i Module
		if err := rows.Scan(
			&i.ID,
			&i.Programid,
			&i.Name,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
