// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notifications.sql

package database

import (
	"context"
)

const countUnreadNotifications = `-- name: CountUnreadNotifications :one
SELECT COUNT(*) FROM notifications
WHERE userid = ?1 AND read = 0
`

func (q *Queries) CountUnreadNotifications(ctx context.Context, userid string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUnreadNotifications, userid)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createNotification = `-- name: CreateNotification :one
INSERT INTO notifications (
  id, userid, title, message, type, link
) VALUES (
  ?1, ?2, ?3, ?4, ?5, ?6
) RETURNING id, userid, title, message, type, link, read, created_at
`

type CreateNotificationParams struct {
	ID      string `json:"id"`
	Userid  string `json:"userid"`
	Title   string `json:"title"`
	Message string `json:"message"`
	Type    string `json:"type"`
	Link    string `json:"link"`
}

func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error) {
	row := q.db.QueryRowContext(ctx, createNotification,
		arg.ID,
		arg.Userid,
		arg.Title,
		arg.Message,
		arg.Type,
		arg.Link,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.Userid,
		&i.Title,
		&i.Message,
		&i.Type,
		&i.Link,
		&i.Read,
		&i.CreatedAt,
	)
	return i, err
}

const listNotifications = `-- name: ListNotifications :many
SELECT id, userid, title, message, type, link, read, created_at FROM notifications
WHERE userid = ?1 AND read = 0
ORDER BY created_at DESC
LIMIT 50
`

func (q *Queries) ListNotifications(ctx context.Context, userid string) ([]Notification, error) {
	rows, err := q.db.QueryContext(ctx, listNotifications, userid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Notification
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.Userid,
			&i.Title,
			&i.Message,
			&i.Type,
			&i.Link,
			&i.Read,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersForNotification = `-- name: ListUsersForNotification :many
SELECT id FROM users WHERE active = 1
`

func (q *Queries) ListUsersForNotification(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listUsersForNotification)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllNotificationsAsRead = `-- name: MarkAllNotificationsAsRead :exec
UPDATE notifications
SET read = 1
WHERE userid = ?1
`

func (q *Queries) MarkAllNotificationsAsRead(ctx context.Context, userid string) error {
	_, err := q.db.ExecContext(ctx, markAllNotificationsAsRead, userid)
	return err
}

const markNotificationAsRead = `-- name: MarkNotificationAsRead :one
UPDATE notifications
SET read = 1
WHERE id = ?1 AND userid = ?2
RETURNING id, userid, title, message, type, link, read, created_at
`

type MarkNotificationAsReadParams struct {
	ID     string `json:"id"`
	Userid string `json:"userid"`
}

func (q *Queries) MarkNotificationAsRead(ctx context.Context, arg MarkNotificationAsReadParams) (Notification, error) {
	row := q.db.QueryRowContext(ctx, markNotificationAsRead, arg.ID, arg.Userid)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.Userid,
		&i.Title,
		&i.Message,
		&i.Type,
		&i.Link,
		&i.Read,
		&i.CreatedAt,
	)
	return i, err
}
