// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: settings.sql

package database

import (
	"context"
)

const getConfig = `-- name: GetConfig :one
SELECT id, office_occupied, updated_at FROM global_config WHERE id = 1
`

func (q *Queries) GetConfig(ctx context.Context) (GlobalConfig, error) {
	row := q.db.QueryRowContext(ctx, getConfig)
	var i GlobalConfig
	err := row.Scan(&i.ID, &i.OfficeOccupied, &i.UpdatedAt)
	return i, err
}

const updateOfficeOccupied = `-- name: UpdateOfficeOccupied :exec
UPDATE global_config SET office_occupied = ? WHERE id = 1
`

func (q *Queries) UpdateOfficeOccupied(ctx context.Context, officeOccupied int64) error {
	_, err := q.db.ExecContext(ctx, updateOfficeOccupied, officeOccupied)
	return err
}
