// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package database

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
  id, email, name, password, role, active, verified, programid, verification_token, avatar_url
) VALUES (
  ?1, ?2, ?3, ?4,
  COALESCE(?5, 'user'),
  COALESCE(?6, 0),
  0,
  ?7,
  ?8,
  ?9
)
RETURNING id, email, name, password, role, active, verified, verified_at, verified_until, programid, created_at, updated_at, verification_token, theme, private, avatar_url
`

type CreateUserParams struct {
	ID                string      `json:"id"`
	Email             string      `json:"email"`
	Name              string      `json:"name"`
	Password          string      `json:"password"`
	Role              interface{} `json:"role"`
	Active            interface{} `json:"active"`
	Programid         int64       `json:"programid"`
	VerificationToken *string     `json:"verification_token"`
	AvatarUrl         *string     `json:"avatar_url"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.ID,
		arg.Email,
		arg.Name,
		arg.Password,
		arg.Role,
		arg.Active,
		arg.Programid,
		arg.VerificationToken,
		arg.AvatarUrl,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Password,
		&i.Role,
		&i.Active,
		&i.Verified,
		&i.VerifiedAt,
		&i.VerifiedUntil,
		&i.Programid,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.VerificationToken,
		&i.Theme,
		&i.Private,
		&i.AvatarUrl,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, email, name, password, role, active, verified, verified_at, verified_until, programid, created_at, updated_at, verification_token, theme, private, avatar_url
FROM users
WHERE id = ?1
LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Password,
		&i.Role,
		&i.Active,
		&i.Verified,
		&i.VerifiedAt,
		&i.VerifiedUntil,
		&i.Programid,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.VerificationToken,
		&i.Theme,
		&i.Private,
		&i.AvatarUrl,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, name, password, role, active, verified, verified_at, verified_until, programid, created_at, updated_at, verification_token, theme, private, avatar_url
FROM users
WHERE lower(email) = lower(?1)
LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Password,
		&i.Role,
		&i.Active,
		&i.Verified,
		&i.VerifiedAt,
		&i.VerifiedUntil,
		&i.Programid,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.VerificationToken,
		&i.Theme,
		&i.Private,
		&i.AvatarUrl,
	)
	return i, err
}

const getUserByVerificationToken = `-- name: GetUserByVerificationToken :one
SELECT id, email, name, password, role, active, verified, verified_at, verified_until, programid, created_at, updated_at, verification_token, theme, private, avatar_url
FROM users
WHERE verification_token = ?1
LIMIT 1
`

func (q *Queries) GetUserByVerificationToken(ctx context.Context, verificationToken *string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByVerificationToken, verificationToken)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Password,
		&i.Role,
		&i.Active,
		&i.Verified,
		&i.VerifiedAt,
		&i.VerifiedUntil,
		&i.Programid,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.VerificationToken,
		&i.Theme,
		&i.Private,
		&i.AvatarUrl,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, email, name, password, role, active, verified, verified_at, verified_until, programid, created_at, updated_at, verification_token, theme, private, avatar_url
FROM users
ORDER BY created_at DESC
LIMIT ?2 OFFSET ?1
`

type ListUsersParams struct {
	Offset int64 `json:"offset"`
	Limit  int64 `json:"limit"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUsers, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.Password,
			&i.Role,
			&i.Active,
			&i.Verified,
			&i.VerifiedAt,
			&i.VerifiedUntil,
			&i.Programid,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.VerificationToken,
			&i.Theme,
			&i.Private,
			&i.AvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchUsers = `-- name: SearchUsers :many
SELECT id, email, name, password, role, active, verified, verified_at, verified_until, programid, created_at, updated_at, verification_token, theme, private, avatar_url
FROM users
WHERE (
  lower(id) LIKE '%' || lower(?1) || '%' OR
  lower(name) LIKE '%' || lower(?1) || '%' OR
  lower(email) LIKE '%' || lower(?1) || '%'
) AND active = 1 AND private = 0
ORDER BY name ASC
LIMIT 10
`

func (q *Queries) SearchUsers(ctx context.Context, query string) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, searchUsers, query)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.Password,
			&i.Role,
			&i.Active,
			&i.Verified,
			&i.VerifiedAt,
			&i.VerifiedUntil,
			&i.Programid,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.VerificationToken,
			&i.Theme,
			&i.Private,
			&i.AvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setUserActive = `-- name: SetUserActive :one
UPDATE users
SET active = ?1
WHERE id = ?2
RETURNING id, email, name, password, role, active, verified, verified_at, verified_until, programid, created_at, updated_at, verification_token, theme, private, avatar_url
`

type SetUserActiveParams struct {
	Active int64  `json:"active"`
	ID     string `json:"id"`
}

func (q *Queries) SetUserActive(ctx context.Context, arg SetUserActiveParams) (User, error) {
	row := q.db.QueryRowContext(ctx, setUserActive, arg.Active, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Password,
		&i.Role,
		&i.Active,
		&i.Verified,
		&i.VerifiedAt,
		&i.VerifiedUntil,
		&i.Programid,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.VerificationToken,
		&i.Theme,
		&i.Private,
		&i.AvatarUrl,
	)
	return i, err
}

const setUserRole = `-- name: SetUserRole :one
UPDATE users
SET role = ?1
WHERE id = ?2
RETURNING id, email, name, password, role, active, verified, verified_at, verified_until, programid, created_at, updated_at, verification_token, theme, private, avatar_url
`

type SetUserRoleParams struct {
	Role string `json:"role"`
	ID   string `json:"id"`
}

func (q *Queries) SetUserRole(ctx context.Context, arg SetUserRoleParams) (User, error) {
	row := q.db.QueryRowContext(ctx, setUserRole, arg.Role, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Password,
		&i.Role,
		&i.Active,
		&i.Verified,
		&i.VerifiedAt,
		&i.VerifiedUntil,
		&i.Programid,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.VerificationToken,
		&i.Theme,
		&i.Private,
		&i.AvatarUrl,
	)
	return i, err
}

const sweepExpiredVerifications = `-- name: SweepExpiredVerifications :exec
UPDATE users
SET verified = 0
WHERE verified = 1
  AND verified_until IS NOT NULL
  AND verified_until < strftime('%Y-%m-%dT%H:%M:%fZ','now')
`

func (q *Queries) SweepExpiredVerifications(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, sweepExpiredVerifications)
	return err
}

const unverifyUser = `-- name: UnverifyUser :one
UPDATE users
SET verified = 0
WHERE id = ?1
RETURNING id, email, name, password, role, active, verified, verified_at, verified_until, programid, created_at, updated_at, verification_token, theme, private, avatar_url
`

func (q *Queries) UnverifyUser(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRowContext(ctx, unverifyUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Password,
		&i.Role,
		&i.Active,
		&i.Verified,
		&i.VerifiedAt,
		&i.VerifiedUntil,
		&i.Programid,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.VerificationToken,
		&i.Theme,
		&i.Private,
		&i.AvatarUrl,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET name = ?1,
    programid = ?2,
    theme = ?3,
    private = ?4,
    avatar_url = ?5,
    updated_at = strftime('%Y-%m-%dT%H:%M:%fZ','now')
WHERE id = ?6
RETURNING id, email, name, password, role, active, verified, verified_at, verified_until, programid, created_at, updated_at, verification_token, theme, private, avatar_url
`

type UpdateUserParams struct {
	Name      string  `json:"name"`
	Programid int64   `json:"programid"`
	Theme     string  `json:"theme"`
	Private   int64   `json:"private"`
	AvatarUrl *string `json:"avatar_url"`
	ID        string  `json:"id"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUser,
		arg.Name,
		arg.Programid,
		arg.Theme,
		arg.Private,
		arg.AvatarUrl,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Password,
		&i.Role,
		&i.Active,
		&i.Verified,
		&i.VerifiedAt,
		&i.VerifiedUntil,
		&i.Programid,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.VerificationToken,
		&i.Theme,
		&i.Private,
		&i.AvatarUrl,
	)
	return i, err
}

const updateUserAvatar = `-- name: UpdateUserAvatar :one
UPDATE users
SET avatar_url = ?1,
    updated_at = strftime('%Y-%m-%dT%H:%M:%fZ','now')
WHERE id = ?2
RETURNING id, email, name, password, role, active, verified, verified_at, verified_until, programid, created_at, updated_at, verification_token, theme, private, avatar_url
`

type UpdateUserAvatarParams struct {
	AvatarUrl *string `json:"avatar_url"`
	ID        string  `json:"id"`
}

func (q *Queries) UpdateUserAvatar(ctx context.Context, arg UpdateUserAvatarParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUserAvatar, arg.AvatarUrl, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Password,
		&i.Role,
		&i.Active,
		&i.Verified,
		&i.VerifiedAt,
		&i.VerifiedUntil,
		&i.Programid,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.VerificationToken,
		&i.Theme,
		&i.Private,
		&i.AvatarUrl,
	)
	return i, err
}

const updateUserToken = `-- name: UpdateUserToken :exec
UPDATE users
SET verification_token = ?1
WHERE id = ?2
`

type UpdateUserTokenParams struct {
	VerificationToken *string `json:"verification_token"`
	ID                string  `json:"id"`
}

func (q *Queries) UpdateUserToken(ctx context.Context, arg UpdateUserTokenParams) error {
	_, err := q.db.ExecContext(ctx, updateUserToken, arg.VerificationToken, arg.ID)
	return err
}

const updateUserVerificationWindow = `-- name: UpdateUserVerificationWindow :one
UPDATE users
SET verified_until = ?1
WHERE id = ?2
RETURNING id, email, name, password, role, active, verified, verified_at, verified_until, programid, created_at, updated_at, verification_token, theme, private, avatar_url
`

type UpdateUserVerificationWindowParams struct {
	VerifiedUntil *string `json:"verified_until"`
	ID            string  `json:"id"`
}

func (q *Queries) UpdateUserVerificationWindow(ctx context.Context, arg UpdateUserVerificationWindowParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUserVerificationWindow, arg.VerifiedUntil, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Password,
		&i.Role,
		&i.Active,
		&i.Verified,
		&i.VerifiedAt,
		&i.VerifiedUntil,
		&i.Programid,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.VerificationToken,
		&i.Theme,
		&i.Private,
		&i.AvatarUrl,
	)
	return i, err
}

const verifyUser = `-- name: VerifyUser :one
UPDATE users
SET verified = 1,
    verified_at = strftime('%Y-%m-%dT%H:%M:%fZ','now'),
    verified_until = ?1,
    verification_token = NULL
WHERE id = ?2
RETURNING id, email, name, password, role, active, verified, verified_at, verified_until, programid, created_at, updated_at, verification_token, theme, private, avatar_url
`

type VerifyUserParams struct {
	VerifiedUntil *string `json:"verified_until"`
	ID            string  `json:"id"`
}

func (q *Queries) VerifyUser(ctx context.Context, arg VerifyUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, verifyUser, arg.VerifiedUntil, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Password,
		&i.Role,
		&i.Active,
		&i.Verified,
		&i.VerifiedAt,
		&i.VerifiedUntil,
		&i.Programid,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.VerificationToken,
		&i.Theme,
		&i.Private,
		&i.AvatarUrl,
	)
	return i, err
}
