// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	CookieAuthScopes = "cookieAuth.Scopes"
)

// Defines values for UserActive.
const (
	UserActiveN0 UserActive = 0
	UserActiveN1 UserActive = 1
)

// Defines values for UserRole.
const (
	UserRoleAdmin  UserRole = "admin"
	UserRoleEditor UserRole = "editor"
	UserRoleUser   UserRole = "user"
)

// Defines values for UserVerified.
const (
	UserVerifiedN0 UserVerified = 0
	UserVerifiedN1 UserVerified = 1
)

// Error defines model for Error.
type Error struct {
	Error   string `json:"error"`
	Message string `json:"message"`
}

// ExamListEntry defines model for ExamListEntry.
type ExamListEntry struct {
	Comment      *string             `json:"comment,omitempty"`
	ExamDate     *openapi_types.Date `json:"exam_date,omitempty"`
	Id           *string             `json:"id,omitempty"`
	ModuleName   *string             `json:"module_name,omitempty"`
	Moduleid     *int                `json:"moduleid,omitempty"`
	Programid    *int                `json:"programid,omitempty"`
	UploadedAt   *time.Time          `json:"uploaded_at,omitempty"`
	UploaderName *string             `json:"uploader_name,omitempty"`
	Version      *string             `json:"version,omitempty"`
}

// Module defines model for Module.
type Module struct {
	Id        int    `json:"id"`
	Name      string `json:"name"`
	Programid int    `json:"programid"`
}

// Program defines model for Program.
type Program struct {
	Id   int    `json:"id"`
	Name string `json:"name"`

	// Versions List of valid POs for this program (e.g. PO2016, PO2023)
	Versions []string `json:"versions"`
}

// User defines model for User.
type User struct {
	Active    UserActive          `json:"active"`
	CreatedAt time.Time           `json:"created_at"`
	Email     openapi_types.Email `json:"email"`

	// Id Version 4 UUID
	Id            string       `json:"id"`
	Name          string       `json:"name"`
	Programid     int          `json:"programid"`
	Role          UserRole     `json:"role"`
	UpdatedAt     time.Time    `json:"updated_at"`
	Verified      UserVerified `json:"verified"`
	VerifiedAt    *time.Time   `json:"verified_at"`
	VerifiedUntil *time.Time   `json:"verified_until"`
}

// UserActive defines model for User.Active.
type UserActive int

// UserRole defines model for User.Role.
type UserRole string

// UserVerified defines model for User.Verified.
type UserVerified int

// UserLogin defines model for UserLogin.
type UserLogin struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
}

// UserRegister defines model for UserRegister.
type UserRegister struct {
	Email     openapi_types.Email `json:"email"`
	Name      string              `json:"name"`
	Password  string              `json:"password"`
	Programid int                 `json:"programid"`
}

// CsrfHeader defines model for CsrfHeader.
type CsrfHeader = string

// PostAuthLogoutParams defines parameters for PostAuthLogout.
type PostAuthLogoutParams struct {
	XCSRFToken CsrfHeader `json:"X-CSRF-Token"`
}

// GetAuthVerifyParams defines parameters for GetAuthVerify.
type GetAuthVerifyParams struct {
	Token string `form:"token" json:"token"`
}

// GetExamsParams defines parameters for GetExams.
type GetExamsParams struct {
	Programid *int    `form:"programid,omitempty" json:"programid,omitempty"`
	Version   *string `form:"version,omitempty" json:"version,omitempty"`
	Moduleid  *int    `form:"moduleid,omitempty" json:"moduleid,omitempty"`
}

// PostExamsMultipartBody defines parameters for PostExams.
type PostExamsMultipartBody struct {
	Comment   *string            `json:"comment,omitempty"`
	Date      openapi_types.Date `json:"date"`
	File      openapi_types.File `json:"file"`
	Moduleid  int                `json:"moduleid"`
	Programid int                `json:"programid"`
	Version   string             `json:"version"`
}

// PostExamsParams defines parameters for PostExams.
type PostExamsParams struct {
	XCSRFToken CsrfHeader `json:"X-CSRF-Token"`
}

// GetUsersParams defines parameters for GetUsers.
type GetUsersParams struct {
	Limit  *int `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}

// PostAuthLoginJSONRequestBody defines body for PostAuthLogin for application/json ContentType.
type PostAuthLoginJSONRequestBody = UserLogin

// PostAuthRegisterJSONRequestBody defines body for PostAuthRegister for application/json ContentType.
type PostAuthRegisterJSONRequestBody = UserRegister

// PostExamsMultipartRequestBody defines body for PostExams for multipart/form-data ContentType.
type PostExamsMultipartRequestBody PostExamsMultipartBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Issue a CSRF token
	// (GET /auth/csrf)
	GetAuthCsrf(w http.ResponseWriter, r *http.Request)
	// Log in
	// (POST /auth/login)
	PostAuthLogin(w http.ResponseWriter, r *http.Request)
	// Log out
	// (POST /auth/logout)
	PostAuthLogout(w http.ResponseWriter, r *http.Request, params PostAuthLogoutParams)
	// Get current user
	// (GET /auth/me)
	GetAuthMe(w http.ResponseWriter, r *http.Request)
	// Register a user
	// (POST /auth/register)
	PostAuthRegister(w http.ResponseWriter, r *http.Request)
	// Verify user email
	// (GET /auth/verify)
	GetAuthVerify(w http.ResponseWriter, r *http.Request, params GetAuthVerifyParams)
	// List exams
	// (GET /exams)
	GetExams(w http.ResponseWriter, r *http.Request, params GetExamsParams)
	// Upload an exam
	// (POST /exams)
	PostExams(w http.ResponseWriter, r *http.Request, params PostExamsParams)
	// Download exam file
	// (GET /exams/{id}/file)
	GetExamsFile(w http.ResponseWriter, r *http.Request, id string)
	// List all programs and their valid POs
	// (GET /programs)
	GetPrograms(w http.ResponseWriter, r *http.Request)
	// Get program by id
	// (GET /programs/{id})
	GetProgramsId(w http.ResponseWriter, r *http.Request, id int)
	// List modules for a program
	// (GET /programs/{id}/modules)
	GetProgramModules(w http.ResponseWriter, r *http.Request, id int)
	// List users (restricted)
	// (GET /users)
	GetUsers(w http.ResponseWriter, r *http.Request, params GetUsersParams)
	// Get user by id
	// (GET /users/{id})
	GetUsersId(w http.ResponseWriter, r *http.Request, id string)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Issue a CSRF token
// (GET /auth/csrf)
func (_ Unimplemented) GetAuthCsrf(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Log in
// (POST /auth/login)
func (_ Unimplemented) PostAuthLogin(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Log out
// (POST /auth/logout)
func (_ Unimplemented) PostAuthLogout(w http.ResponseWriter, r *http.Request, params PostAuthLogoutParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get current user
// (GET /auth/me)
func (_ Unimplemented) GetAuthMe(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Register a user
// (POST /auth/register)
func (_ Unimplemented) PostAuthRegister(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Verify user email
// (GET /auth/verify)
func (_ Unimplemented) GetAuthVerify(w http.ResponseWriter, r *http.Request, params GetAuthVerifyParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List exams
// (GET /exams)
func (_ Unimplemented) GetExams(w http.ResponseWriter, r *http.Request, params GetExamsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Upload an exam
// (POST /exams)
func (_ Unimplemented) PostExams(w http.ResponseWriter, r *http.Request, params PostExamsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Download exam file
// (GET /exams/{id}/file)
func (_ Unimplemented) GetExamsFile(w http.ResponseWriter, r *http.Request, id string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List all programs and their valid POs
// (GET /programs)
func (_ Unimplemented) GetPrograms(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get program by id
// (GET /programs/{id})
func (_ Unimplemented) GetProgramsId(w http.ResponseWriter, r *http.Request, id int) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List modules for a program
// (GET /programs/{id}/modules)
func (_ Unimplemented) GetProgramModules(w http.ResponseWriter, r *http.Request, id int) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List users (restricted)
// (GET /users)
func (_ Unimplemented) GetUsers(w http.ResponseWriter, r *http.Request, params GetUsersParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get user by id
// (GET /users/{id})
func (_ Unimplemented) GetUsersId(w http.ResponseWriter, r *http.Request, id string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetAuthCsrf operation middleware
func (siw *ServerInterfaceWrapper) GetAuthCsrf(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAuthCsrf(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostAuthLogin operation middleware
func (siw *ServerInterfaceWrapper) PostAuthLogin(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostAuthLogin(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostAuthLogout operation middleware
func (siw *ServerInterfaceWrapper) PostAuthLogout(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params PostAuthLogoutParams

	headers := r.Header

	// ------------- Required header parameter "X-CSRF-Token" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-CSRF-Token")]; found {
		var XCSRFToken CsrfHeader
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-CSRF-Token", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-CSRF-Token", valueList[0], &XCSRFToken, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-CSRF-Token", Err: err})
			return
		}

		params.XCSRFToken = XCSRFToken

	} else {
		err := fmt.Errorf("Header parameter X-CSRF-Token is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "X-CSRF-Token", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostAuthLogout(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAuthMe operation middleware
func (siw *ServerInterfaceWrapper) GetAuthMe(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAuthMe(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostAuthRegister operation middleware
func (siw *ServerInterfaceWrapper) PostAuthRegister(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostAuthRegister(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAuthVerify operation middleware
func (siw *ServerInterfaceWrapper) GetAuthVerify(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetAuthVerifyParams

	// ------------- Required query parameter "token" -------------

	if paramValue := r.URL.Query().Get("token"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "token"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "token", r.URL.Query(), &params.Token)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "token", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAuthVerify(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetExams operation middleware
func (siw *ServerInterfaceWrapper) GetExams(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetExamsParams

	// ------------- Optional query parameter "programid" -------------

	err = runtime.BindQueryParameter("form", true, false, "programid", r.URL.Query(), &params.Programid)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "programid", Err: err})
		return
	}

	// ------------- Optional query parameter "version" -------------

	err = runtime.BindQueryParameter("form", true, false, "version", r.URL.Query(), &params.Version)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "version", Err: err})
		return
	}

	// ------------- Optional query parameter "moduleid" -------------

	err = runtime.BindQueryParameter("form", true, false, "moduleid", r.URL.Query(), &params.Moduleid)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "moduleid", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetExams(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostExams operation middleware
func (siw *ServerInterfaceWrapper) PostExams(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params PostExamsParams

	headers := r.Header

	// ------------- Required header parameter "X-CSRF-Token" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-CSRF-Token")]; found {
		var XCSRFToken CsrfHeader
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-CSRF-Token", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-CSRF-Token", valueList[0], &XCSRFToken, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-CSRF-Token", Err: err})
			return
		}

		params.XCSRFToken = XCSRFToken

	} else {
		err := fmt.Errorf("Header parameter X-CSRF-Token is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "X-CSRF-Token", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostExams(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetExamsFile operation middleware
func (siw *ServerInterfaceWrapper) GetExamsFile(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetExamsFile(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetPrograms operation middleware
func (siw *ServerInterfaceWrapper) GetPrograms(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetPrograms(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetProgramsId operation middleware
func (siw *ServerInterfaceWrapper) GetProgramsId(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetProgramsId(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetProgramModules operation middleware
func (siw *ServerInterfaceWrapper) GetProgramModules(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetProgramModules(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetUsers operation middleware
func (siw *ServerInterfaceWrapper) GetUsers(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetUsersParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", r.URL.Query(), &params.Offset)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetUsers(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetUsersId operation middleware
func (siw *ServerInterfaceWrapper) GetUsersId(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetUsersId(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/auth/csrf", wrapper.GetAuthCsrf)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/login", wrapper.PostAuthLogin)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/logout", wrapper.PostAuthLogout)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/auth/me", wrapper.GetAuthMe)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/register", wrapper.PostAuthRegister)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/auth/verify", wrapper.GetAuthVerify)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/exams", wrapper.GetExams)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/exams", wrapper.PostExams)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/exams/{id}/file", wrapper.GetExamsFile)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/programs", wrapper.GetPrograms)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/programs/{id}", wrapper.GetProgramsId)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/programs/{id}/modules", wrapper.GetProgramModules)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/users", wrapper.GetUsers)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/users/{id}", wrapper.GetUsersId)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/9RZW2/bOBP9KwS/76EFlNi5bIH1226atsGm26DdFAsEQcCII5utRKoklcYo/N8XvOhm",
	"UbLcOGn7lFjiZWbOmZlD6huORZYLDlwrPPuGF0AoSPvvB9AnQnxmYH6oeAEZMf/pZQ54hpWWjM/xarWK",
	"cE4kyUD7eSdKJm/sMuYX43jmV8UR5iQzk//dO/nw/tXeP+IzcBxhCV8KJoHimZYFRMObuZd2p1Mphd0k",
	"lyIHqRnYx1A+Xpsd4QyUInMIrdy04sovUU+4jsoJ4vYTxNosdnpPsnOm9CnXctm1IhZZBlwH7YB7kt1Q",
	"oq0liZAZ0XiG7YOoO5rRsDOCFincuJD2vm9NZlzDHKR5m0sxlyTre13kqSAU6A3RHRv3NMuChvpJst+m",
	"O5CKCR4GoBPht9aDbmj7jO7ddtDZNegZxc0JftUQAS7coB3Y58NiJ1NQsWS5tmHChmBIJOiOpIyii3cK",
	"JUIivWAKeRvRM9if76OLd4fTgxeR/Xt49BxHmGnIVHA7/4BISZZh/62lDbtC7l8qCCQfiTW7s14CLzI8",
	"u5pGB/XsRjBiCURvSTDICEtbw92T3qRpB/Ojcwcdo8vLs5ehWd/HoAhL4XhKISFFagwrlC14PgjVT8q0",
	"LSyEZow3wtpMIrp1XO5AsoQBHRH2cujQ+rxIU3JrPHL1uHe/m4LrNUC2WCdEvBJPT0Ab16gkVcPRdoo2",
	"uNQKYB9tz8Wc8UDjGE+vnCj1VUg6opX4JaoZfUa9hzlTOpRTW9hVEjhj/Bz4XC/w7GCD+c2hL6KHFc81",
	"+Kptmqt0/TddHeJCMr38YLp72UCN+PijMIZ5HeEe1Tri5uaNUHpPgbJdpa5sOfsLlk4vMJ4IaznTqX+H",
	"G40IT/cP9qfGT5EDNy9n+Gh/un9kzdcLa8qEFHoxiZVMzK852NQxCBFTWc4onuHXoI2pRvxYRaNywZVz",
	"5HA6df5w7QUByfOUxXby5JNy/bAWPWs6wu86zDI7KhDZVbRWA43wQtoIL8SUKmwqtUXfXq36/i8hwTP8",
	"v0ktEid+8KSWh6tVE0E8u7qOsCqyjBhZhM/MLoigemODE5krY7ZF99pMdyFOq8QUKhDkC6FslF3+ugiA",
	"0n8KutwqwiG/vK6c1PVh1Q6yqWGrB0K7aeMQYudiPgeKrMMPRyrCx9ODndnsFHjA6DPuFEssgQLXjKQK",
	"272PHn/vU1OEEBcaVe1iiKDnYu6CO0BKUehRrDTj2uehq7AT9ZBJ47y0uu7w6zigCR0h3F6/DCP+FhqZ",
	"cBo2xKZBr4PSrvhX16sOSs7jPphc4xsqzm8B/4D8PSmkBK6RlYC/SLRfg0Zx0+7+sMumbBnMj0rgPF7h",
	"rrYYVbsPHh178xx5deqwnz5d7c3J0pzH3b6/P1XdJakEQpcI7pnSarDylmghsolktpAvN+X3RzeqU4Ct",
	"dvxSgFzW0lFvffd0vVNZN3gVtVHFuVCX7Q2pIo5BqaRI0+WT08xFcghnh4vFGFUnly7ScE/chUUfxqd2",
	"wCh4m6fDDqSN00t4dnk6GKJDz9Tq1m1w34dyqbrbGUSudUHZvffpKk1/2eSA+FWEgTEaPDNKVjmmXJvT",
	"a29L6mHTtmqtr5FlRapZTqSemFP7HiWaDB7zBq6LR98UJyxtD7xlnFh27vZ2ePAat3kstQa172rq3Gqk",
	"inUofHx9uia+li+BqntPMlTejD/ZceaVkLeM0m6NHc6LS2snItwmRyA3qpI7+cboalJyZ7D4vvJ4Bgpw",
	"TvSiLoMW1cfqrTlN2nHdyPdAVFkKqFzfQnn8NKUuEQXfssS9FF+5BdPAhXxOheD0eTbYRC/KMU/RgspP",
	"JFs0n8qHwTO7GUzStBqNCKdIL4DJ+lNJI0iV0+04WeaPCdYZ3SHrdycDRoW+G+oGKj+W9p0zZ/lN63aJ",
	"bCzH4DdxfWQM6d/6kT8jlqPyyX8R3SKdyuBszCY/0H5fJCUQIQjK77IlGEbWDwb/0g4YJdtTljHdks7V",
	"F7Wjwwhn5J5lRYZnh7+9iHDGuPt1EI1W9iJJFPTsMG0sOY1+EMKX/pZoLL4u+j+5FrHGWkvRMwmmKcca",
	"6PMGuxxHGoTaWJrtjJ3W5Z2d9L/3puhn1yGmQttD/Hp5rtDbtNrqvwAAAP//fvvxIHAkAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
