// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package api

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	CookieAuthScopes = "cookieAuth.Scopes"
)

// Defines values for UserActive.
const (
	UserActiveN0 UserActive = 0
	UserActiveN1 UserActive = 1
)

// Defines values for UserRole.
const (
	UserRoleAdmin  UserRole = "admin"
	UserRoleEditor UserRole = "editor"
	UserRoleUser   UserRole = "user"
)

// Defines values for UserVerified.
const (
	UserVerifiedN0 UserVerified = 0
	UserVerifiedN1 UserVerified = 1
)

// Error defines model for Error.
type Error struct {
	Error   string `json:"error"`
	Message string `json:"message"`
}

// User defines model for User.
type User struct {
	Active       UserActive          `json:"active"`
	Campusid     int                 `json:"campusid"`
	CreatedAt    time.Time           `json:"created_at"`
	Disciplineid int                 `json:"disciplineid"`
	Email        openapi_types.Email `json:"email"`

	// Id Version 4 UUID
	Id            string       `json:"id"`
	Name          string       `json:"name"`
	Role          UserRole     `json:"role"`
	UpdatedAt     time.Time    `json:"updated_at"`
	Verified      UserVerified `json:"verified"`
	VerifiedAt    *time.Time   `json:"verified_at"`
	VerifiedUntil *time.Time   `json:"verified_until"`
}

// UserActive defines model for User.Active.
type UserActive int

// UserRole defines model for User.Role.
type UserRole string

// UserVerified defines model for User.Verified.
type UserVerified int

// UserLogin defines model for UserLogin.
type UserLogin struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
}

// UserRegister defines model for UserRegister.
type UserRegister struct {
	Campusid     int                 `json:"campusid"`
	Disciplineid int                 `json:"disciplineid"`
	Email        openapi_types.Email `json:"email"`
	Name         string              `json:"name"`
	Password     string              `json:"password"`
}

// CsrfHeader defines model for CsrfHeader.
type CsrfHeader = string

// PostAuthLogoutParams defines parameters for PostAuthLogout.
type PostAuthLogoutParams struct {
	XCSRFToken CsrfHeader `json:"X-CSRF-Token"`
}

// GetUsersParams defines parameters for GetUsers.
type GetUsersParams struct {
	Limit  *int `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}

// PostAuthLoginJSONRequestBody defines body for PostAuthLogin for application/json ContentType.
type PostAuthLoginJSONRequestBody = UserLogin

// PostAuthRegisterJSONRequestBody defines body for PostAuthRegister for application/json ContentType.
type PostAuthRegisterJSONRequestBody = UserRegister
