// This file is auto-generated by @hey-api/openapi-ts

import { type Client, formDataBodySerializer, type Options as Options2, type TDataShape } from './client';
import { client } from './client.gen';
import type { DeleteExamsIdData, DeleteExamsIdResponses, GetAuthCsrfData, GetAuthCsrfResponses, GetAuthMeData, GetAuthMeResponses, GetAuthVerifyData, GetExamsData, GetExamsErrors, GetExamsFileData, GetExamsFileResponses, GetExamsResponses, GetExamVersionsData, GetExamVersionsResponses, GetProgramModulesData, GetProgramModulesErrors, GetProgramModulesResponses, GetProgramsData, GetProgramsErrors, GetProgramsIdData, GetProgramsIdErrors, GetProgramsIdResponses, GetProgramsResponses, GetUsersByIdData, GetUsersByIdResponses, GetUsersData, GetUsersResponses, PostAuthLoginData, PostAuthLoginErrors, PostAuthLoginResponses, PostAuthLogoutData, PostAuthLogoutResponses, PostAuthRegisterData, PostAuthRegisterErrors, PostAuthRegisterResponses, PostExamsData, PostExamsErrors, PostExamsResponses, PutExamsIdData, PutExamsIdResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Issue CSRF token
 */
export const getAuthCsrf = <ThrowOnError extends boolean = false>(options?: Options<GetAuthCsrfData, ThrowOnError>) => (options?.client ?? client).get<GetAuthCsrfResponses, unknown, ThrowOnError>({ url: '/auth/csrf', ...options });

/**
 * Log in
 */
export const postAuthLogin = <ThrowOnError extends boolean = false>(options: Options<PostAuthLoginData, ThrowOnError>) => (options.client ?? client).post<PostAuthLoginResponses, PostAuthLoginErrors, ThrowOnError>({
    url: '/auth/login',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Log out
 */
export const postAuthLogout = <ThrowOnError extends boolean = false>(options: Options<PostAuthLogoutData, ThrowOnError>) => (options.client ?? client).post<PostAuthLogoutResponses, unknown, ThrowOnError>({ url: '/auth/logout', ...options });

/**
 * Get current user
 */
export const getAuthMe = <ThrowOnError extends boolean = false>(options?: Options<GetAuthMeData, ThrowOnError>) => (options?.client ?? client).get<GetAuthMeResponses, unknown, ThrowOnError>({ url: '/auth/me', ...options });

/**
 * Register a user
 */
export const postAuthRegister = <ThrowOnError extends boolean = false>(options: Options<PostAuthRegisterData, ThrowOnError>) => (options.client ?? client).post<PostAuthRegisterResponses, PostAuthRegisterErrors, ThrowOnError>({
    url: '/auth/register',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Verify user email
 */
export const getAuthVerify = <ThrowOnError extends boolean = false>(options: Options<GetAuthVerifyData, ThrowOnError>) => (options.client ?? client).get<unknown, unknown, ThrowOnError>({ url: '/auth/verify', ...options });

/**
 * List exams
 */
export const getExams = <ThrowOnError extends boolean = false>(options?: Options<GetExamsData, ThrowOnError>) => (options?.client ?? client).get<GetExamsResponses, GetExamsErrors, ThrowOnError>({ url: '/exams', ...options });

/**
 * Upload exam
 *
 * Upload a PDF and assign it to one or more modules
 */
export const postExams = <ThrowOnError extends boolean = false>(options: Options<PostExamsData, ThrowOnError>) => (options.client ?? client).post<PostExamsResponses, PostExamsErrors, ThrowOnError>({
    ...formDataBodySerializer,
    url: '/exams',
    ...options,
    headers: {
        'Content-Type': null,
        ...options.headers
    }
});

/**
 * Delete exam
 */
export const deleteExamsId = <ThrowOnError extends boolean = false>(options: Options<DeleteExamsIdData, ThrowOnError>) => (options.client ?? client).delete<DeleteExamsIdResponses, unknown, ThrowOnError>({ url: '/exams/{id}', ...options });

/**
 * Update exam
 */
export const putExamsId = <ThrowOnError extends boolean = false>(options: Options<PutExamsIdData, ThrowOnError>) => (options.client ?? client).put<PutExamsIdResponses, unknown, ThrowOnError>({
    url: '/exams/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Download file
 */
export const getExamsFile = <ThrowOnError extends boolean = false>(options: Options<GetExamsFileData, ThrowOnError>) => (options.client ?? client).get<GetExamsFileResponses, unknown, ThrowOnError>({ url: '/exams/{id}/file', ...options });

/**
 * List exam versions
 */
export const getExamVersions = <ThrowOnError extends boolean = false>(options: Options<GetExamVersionsData, ThrowOnError>) => (options.client ?? client).get<GetExamVersionsResponses, unknown, ThrowOnError>({ url: '/exams/versions/{groupId}', ...options });

/**
 * List all programs
 *
 * Returns a list of study programs and their valid PO versions
 */
export const getPrograms = <ThrowOnError extends boolean = false>(options?: Options<GetProgramsData, ThrowOnError>) => (options?.client ?? client).get<GetProgramsResponses, GetProgramsErrors, ThrowOnError>({ url: '/programs', ...options });

/**
 * Get program by ID
 */
export const getProgramsId = <ThrowOnError extends boolean = false>(options: Options<GetProgramsIdData, ThrowOnError>) => (options.client ?? client).get<GetProgramsIdResponses, GetProgramsIdErrors, ThrowOnError>({ url: '/programs/{id}', ...options });

/**
 * List modules for a program
 */
export const getProgramModules = <ThrowOnError extends boolean = false>(options: Options<GetProgramModulesData, ThrowOnError>) => (options.client ?? client).get<GetProgramModulesResponses, GetProgramModulesErrors, ThrowOnError>({ url: '/programs/{id}/modules', ...options });

/**
 * List users
 */
export const getUsers = <ThrowOnError extends boolean = false>(options?: Options<GetUsersData, ThrowOnError>) => (options?.client ?? client).get<GetUsersResponses, unknown, ThrowOnError>({ url: '/users', ...options });

/**
 * Get user by ID
 */
export const getUsersById = <ThrowOnError extends boolean = false>(options: Options<GetUsersByIdData, ThrowOnError>) => (options.client ?? client).get<GetUsersByIdResponses, unknown, ThrowOnError>({ url: '/users/{id}', ...options });
