// This file is auto-generated by @hey-api/openapi-ts

import { type Client, formDataBodySerializer, type Options as Options2, type TDataShape } from './client';
import { client } from './client.gen';
import type { DeleteExamsIdData, DeleteExamsIdErrors, DeleteExamsIdResponses, GetAuthCsrfData, GetAuthCsrfResponses, GetAuthMeData, GetAuthMeErrors, GetAuthMeResponses, GetAuthVerifyData, GetAuthVerifyErrors, GetAuthVerifyResponses, GetExamsData, GetExamsErrors, GetExamsFileData, GetExamsFileErrors, GetExamsFileResponses, GetExamsResponses, GetProgramModulesData, GetProgramModulesResponses, GetProgramsData, GetProgramsIdData, GetProgramsIdErrors, GetProgramsIdResponses, GetProgramsResponses, GetUsersData, GetUsersErrors, GetUsersIdData, GetUsersIdErrors, GetUsersIdResponses, GetUsersResponses, PostAuthLoginData, PostAuthLoginErrors, PostAuthLoginResponses, PostAuthLogoutData, PostAuthLogoutErrors, PostAuthLogoutResponses, PostAuthRegisterData, PostAuthRegisterErrors, PostAuthRegisterResponses, PostExamsData, PostExamsErrors, PostExamsResponses, PutExamsIdData, PutExamsIdErrors, PutExamsIdResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Issue a CSRF token
 */
export const getAuthCsrf = <ThrowOnError extends boolean = false>(options?: Options<GetAuthCsrfData, ThrowOnError>) => (options?.client ?? client).get<GetAuthCsrfResponses, unknown, ThrowOnError>({ url: '/auth/csrf', ...options });

/**
 * Register a user
 */
export const postAuthRegister = <ThrowOnError extends boolean = false>(options: Options<PostAuthRegisterData, ThrowOnError>) => (options.client ?? client).post<PostAuthRegisterResponses, PostAuthRegisterErrors, ThrowOnError>({
    url: '/auth/register',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Verify user email
 */
export const getAuthVerify = <ThrowOnError extends boolean = false>(options: Options<GetAuthVerifyData, ThrowOnError>) => (options.client ?? client).get<GetAuthVerifyResponses, GetAuthVerifyErrors, ThrowOnError>({ url: '/auth/verify', ...options });

/**
 * Log in
 */
export const postAuthLogin = <ThrowOnError extends boolean = false>(options: Options<PostAuthLoginData, ThrowOnError>) => (options.client ?? client).post<PostAuthLoginResponses, PostAuthLoginErrors, ThrowOnError>({
    url: '/auth/login',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Log out
 */
export const postAuthLogout = <ThrowOnError extends boolean = false>(options: Options<PostAuthLogoutData, ThrowOnError>) => (options.client ?? client).post<PostAuthLogoutResponses, PostAuthLogoutErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: '__Host-session',
            type: 'apiKey'
        }],
    url: '/auth/logout',
    ...options
});

/**
 * Get current user
 */
export const getAuthMe = <ThrowOnError extends boolean = false>(options?: Options<GetAuthMeData, ThrowOnError>) => (options?.client ?? client).get<GetAuthMeResponses, GetAuthMeErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: '__Host-session',
            type: 'apiKey'
        }],
    url: '/auth/me',
    ...options
});

/**
 * Get user by id
 */
export const getUsersId = <ThrowOnError extends boolean = false>(options: Options<GetUsersIdData, ThrowOnError>) => (options.client ?? client).get<GetUsersIdResponses, GetUsersIdErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: '__Host-session',
            type: 'apiKey'
        }],
    url: '/users/{id}',
    ...options
});

/**
 * List users (restricted)
 */
export const getUsers = <ThrowOnError extends boolean = false>(options?: Options<GetUsersData, ThrowOnError>) => (options?.client ?? client).get<GetUsersResponses, GetUsersErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: '__Host-session',
            type: 'apiKey'
        }],
    url: '/users',
    ...options
});

/**
 * List all programs and their valid POs
 */
export const getPrograms = <ThrowOnError extends boolean = false>(options?: Options<GetProgramsData, ThrowOnError>) => (options?.client ?? client).get<GetProgramsResponses, unknown, ThrowOnError>({ url: '/programs', ...options });

/**
 * Get program by id
 */
export const getProgramsId = <ThrowOnError extends boolean = false>(options: Options<GetProgramsIdData, ThrowOnError>) => (options.client ?? client).get<GetProgramsIdResponses, GetProgramsIdErrors, ThrowOnError>({ url: '/programs/{id}', ...options });

/**
 * List modules for a program
 */
export const getProgramModules = <ThrowOnError extends boolean = false>(options: Options<GetProgramModulesData, ThrowOnError>) => (options.client ?? client).get<GetProgramModulesResponses, unknown, ThrowOnError>({ url: '/programs/{id}/modules', ...options });

/**
 * List exams
 */
export const getExams = <ThrowOnError extends boolean = false>(options?: Options<GetExamsData, ThrowOnError>) => (options?.client ?? client).get<GetExamsResponses, GetExamsErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: '__Host-session',
            type: 'apiKey'
        }],
    url: '/exams',
    ...options
});

/**
 * Upload an exam
 */
export const postExams = <ThrowOnError extends boolean = false>(options: Options<PostExamsData, ThrowOnError>) => (options.client ?? client).post<PostExamsResponses, PostExamsErrors, ThrowOnError>({
    ...formDataBodySerializer,
    security: [{
            in: 'cookie',
            name: '__Host-session',
            type: 'apiKey'
        }],
    url: '/exams',
    ...options,
    headers: {
        'Content-Type': null,
        ...options.headers
    }
});

/**
 * Delete an exam
 */
export const deleteExamsId = <ThrowOnError extends boolean = false>(options: Options<DeleteExamsIdData, ThrowOnError>) => (options.client ?? client).delete<DeleteExamsIdResponses, DeleteExamsIdErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: '__Host-session',
            type: 'apiKey'
        }],
    url: '/exams/{id}',
    ...options
});

/**
 * Update an exam assignment
 */
export const putExamsId = <ThrowOnError extends boolean = false>(options: Options<PutExamsIdData, ThrowOnError>) => (options.client ?? client).put<PutExamsIdResponses, PutExamsIdErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: '__Host-session',
            type: 'apiKey'
        }],
    url: '/exams/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Download exam file
 */
export const getExamsFile = <ThrowOnError extends boolean = false>(options: Options<GetExamsFileData, ThrowOnError>) => (options.client ?? client).get<GetExamsFileResponses, GetExamsFileErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: '__Host-session',
            type: 'apiKey'
        }],
    url: '/exams/{id}/file',
    ...options
});
