// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { GetAuthCsrfData, GetAuthCsrfResponses, GetAuthMeData, GetAuthMeErrors, GetAuthMeResponses, GetAuthVerifyData, GetAuthVerifyErrors, GetAuthVerifyResponses, GetProgramsData, GetProgramsIdData, GetProgramsIdErrors, GetProgramsIdResponses, GetProgramsResponses, GetUsersData, GetUsersErrors, GetUsersIdData, GetUsersIdErrors, GetUsersIdResponses, GetUsersResponses, PostAuthLoginData, PostAuthLoginErrors, PostAuthLoginResponses, PostAuthLogoutData, PostAuthLogoutErrors, PostAuthLogoutResponses, PostAuthRegisterData, PostAuthRegisterErrors, PostAuthRegisterResponses } from './types.gen';
import { zGetAuthCsrfData, zGetAuthCsrfResponse, zGetAuthMeData, zGetAuthMeResponse, zGetAuthVerifyData, zGetAuthVerifyResponse, zGetProgramsData, zGetProgramsIdData, zGetProgramsIdResponse, zGetProgramsResponse, zGetUsersData, zGetUsersIdData, zGetUsersIdResponse, zGetUsersResponse, zPostAuthLoginData, zPostAuthLoginResponse, zPostAuthLogoutData, zPostAuthLogoutResponse, zPostAuthRegisterData, zPostAuthRegisterResponse } from './zod.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Issue a CSRF token
 */
export const getAuthCsrf = <ThrowOnError extends boolean = false>(options?: Options<GetAuthCsrfData, ThrowOnError>) => (options?.client ?? client).get<GetAuthCsrfResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => await zGetAuthCsrfData.parseAsync(data),
    responseValidator: async (data) => await zGetAuthCsrfResponse.parseAsync(data),
    url: '/auth/csrf',
    ...options
});

/**
 * Register a user
 */
export const postAuthRegister = <ThrowOnError extends boolean = false>(options: Options<PostAuthRegisterData, ThrowOnError>) => (options.client ?? client).post<PostAuthRegisterResponses, PostAuthRegisterErrors, ThrowOnError>({
    requestValidator: async (data) => await zPostAuthRegisterData.parseAsync(data),
    responseValidator: async (data) => await zPostAuthRegisterResponse.parseAsync(data),
    url: '/auth/register',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Verify user email
 */
export const getAuthVerify = <ThrowOnError extends boolean = false>(options: Options<GetAuthVerifyData, ThrowOnError>) => (options.client ?? client).get<GetAuthVerifyResponses, GetAuthVerifyErrors, ThrowOnError>({
    requestValidator: async (data) => await zGetAuthVerifyData.parseAsync(data),
    responseValidator: async (data) => await zGetAuthVerifyResponse.parseAsync(data),
    url: '/auth/verify',
    ...options
});

/**
 * Log in
 */
export const postAuthLogin = <ThrowOnError extends boolean = false>(options: Options<PostAuthLoginData, ThrowOnError>) => (options.client ?? client).post<PostAuthLoginResponses, PostAuthLoginErrors, ThrowOnError>({
    requestValidator: async (data) => await zPostAuthLoginData.parseAsync(data),
    responseValidator: async (data) => await zPostAuthLoginResponse.parseAsync(data),
    url: '/auth/login',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Log out
 */
export const postAuthLogout = <ThrowOnError extends boolean = false>(options: Options<PostAuthLogoutData, ThrowOnError>) => (options.client ?? client).post<PostAuthLogoutResponses, PostAuthLogoutErrors, ThrowOnError>({
    requestValidator: async (data) => await zPostAuthLogoutData.parseAsync(data),
    responseValidator: async (data) => await zPostAuthLogoutResponse.parseAsync(data),
    security: [{
            in: 'cookie',
            name: '__Host-session',
            type: 'apiKey'
        }],
    url: '/auth/logout',
    ...options
});

/**
 * Get current user
 */
export const getAuthMe = <ThrowOnError extends boolean = false>(options?: Options<GetAuthMeData, ThrowOnError>) => (options?.client ?? client).get<GetAuthMeResponses, GetAuthMeErrors, ThrowOnError>({
    requestValidator: async (data) => await zGetAuthMeData.parseAsync(data),
    responseValidator: async (data) => await zGetAuthMeResponse.parseAsync(data),
    security: [{
            in: 'cookie',
            name: '__Host-session',
            type: 'apiKey'
        }],
    url: '/auth/me',
    ...options
});

/**
 * Get user by id
 */
export const getUsersId = <ThrowOnError extends boolean = false>(options: Options<GetUsersIdData, ThrowOnError>) => (options.client ?? client).get<GetUsersIdResponses, GetUsersIdErrors, ThrowOnError>({
    requestValidator: async (data) => await zGetUsersIdData.parseAsync(data),
    responseValidator: async (data) => await zGetUsersIdResponse.parseAsync(data),
    security: [{
            in: 'cookie',
            name: '__Host-session',
            type: 'apiKey'
        }],
    url: '/users/{id}',
    ...options
});

/**
 * List users (restricted)
 */
export const getUsers = <ThrowOnError extends boolean = false>(options?: Options<GetUsersData, ThrowOnError>) => (options?.client ?? client).get<GetUsersResponses, GetUsersErrors, ThrowOnError>({
    requestValidator: async (data) => await zGetUsersData.parseAsync(data),
    responseValidator: async (data) => await zGetUsersResponse.parseAsync(data),
    security: [{
            in: 'cookie',
            name: '__Host-session',
            type: 'apiKey'
        }],
    url: '/users',
    ...options
});

/**
 * List all programs and their valid POs
 */
export const getPrograms = <ThrowOnError extends boolean = false>(options?: Options<GetProgramsData, ThrowOnError>) => (options?.client ?? client).get<GetProgramsResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => await zGetProgramsData.parseAsync(data),
    responseValidator: async (data) => await zGetProgramsResponse.parseAsync(data),
    url: '/programs',
    ...options
});

/**
 * Get program by id
 */
export const getProgramsId = <ThrowOnError extends boolean = false>(options: Options<GetProgramsIdData, ThrowOnError>) => (options.client ?? client).get<GetProgramsIdResponses, GetProgramsIdErrors, ThrowOnError>({
    requestValidator: async (data) => await zGetProgramsIdData.parseAsync(data),
    responseValidator: async (data) => await zGetProgramsIdResponse.parseAsync(data),
    url: '/programs/{id}',
    ...options
});
