// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type _Error = {
    error: string;
    message: string;
};

export type Program = {
    id: number;
    name: string;
    /**
     * List of valid POs for this program (e.g. PO2016, PO2023)
     */
    versions: Array<string>;
};

export type Module = {
    id: number;
    programid: number;
    name: string;
};

export type ExamListEntry = {
    id?: string;
    programid?: number;
    version?: string;
    moduleid?: number;
    module_name?: string;
    exam_date?: string;
    uploaded_at?: string;
    uploader_name?: string;
    comment?: string;
};

export type User = {
    /**
     * Version 4 UUID
     */
    id: string;
    email: string;
    name: string;
    role: 'user' | 'editor' | 'admin';
    active: 0 | 1;
    verified: 0 | 1;
    verified_at?: string | null;
    verified_until?: string | null;
    programid: number;
    created_at: string;
    updated_at: string;
};

export type UserRegister = {
    email: string;
    name: string;
    password: string;
    programid: number;
};

export type UserLogin = {
    email: string;
    password: string;
};

export type Session = {
    /**
     * opaque
     */
    id: string;
    userid: string;
    created_at: string;
    last_seen: string;
    expires_at: string;
};

export type CsrfHeader = string;

export type GetAuthCsrfData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/csrf';
};

export type GetAuthCsrfResponses = {
    /**
     * CSRF token issued
     */
    200: {
        csrf: string;
    };
};

export type GetAuthCsrfResponse = GetAuthCsrfResponses[keyof GetAuthCsrfResponses];

export type PostAuthRegisterData = {
    body: UserRegister;
    path?: never;
    query?: never;
    url: '/auth/register';
};

export type PostAuthRegisterErrors = {
    /**
     * Invalid payload
     */
    400: _Error;
    /**
     * Email already exists
     */
    409: _Error;
};

export type PostAuthRegisterError = PostAuthRegisterErrors[keyof PostAuthRegisterErrors];

export type PostAuthRegisterResponses = {
    /**
     * User created
     */
    201: User;
};

export type PostAuthRegisterResponse = PostAuthRegisterResponses[keyof PostAuthRegisterResponses];

export type GetAuthVerifyData = {
    body?: never;
    path?: never;
    query: {
        token: string;
    };
    url: '/auth/verify';
};

export type GetAuthVerifyErrors = {
    /**
     * Invalid token
     */
    400: _Error;
};

export type GetAuthVerifyError = GetAuthVerifyErrors[keyof GetAuthVerifyErrors];

export type GetAuthVerifyResponses = {
    /**
     * Email verified successfully
     */
    200: {
        message?: string;
    };
};

export type GetAuthVerifyResponse = GetAuthVerifyResponses[keyof GetAuthVerifyResponses];

export type PostAuthLoginData = {
    body: UserLogin;
    path?: never;
    query?: never;
    url: '/auth/login';
};

export type PostAuthLoginErrors = {
    /**
     * Invalid credentials
     */
    401: _Error;
    /**
     * Email not verified
     */
    403: _Error;
};

export type PostAuthLoginError = PostAuthLoginErrors[keyof PostAuthLoginErrors];

export type PostAuthLoginResponses = {
    /**
     * Logged in
     */
    200: User;
};

export type PostAuthLoginResponse = PostAuthLoginResponses[keyof PostAuthLoginResponses];

export type PostAuthLogoutData = {
    body?: never;
    headers: {
        'X-CSRF-Token': string;
    };
    path?: never;
    query?: never;
    url: '/auth/logout';
};

export type PostAuthLogoutErrors = {
    /**
     * Not authenticated
     */
    401: _Error;
};

export type PostAuthLogoutError = PostAuthLogoutErrors[keyof PostAuthLogoutErrors];

export type PostAuthLogoutResponses = {
    /**
     * Logged out
     */
    204: void;
};

export type PostAuthLogoutResponse = PostAuthLogoutResponses[keyof PostAuthLogoutResponses];

export type GetAuthMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/me';
};

export type GetAuthMeErrors = {
    /**
     * Not authenticated
     */
    401: _Error;
};

export type GetAuthMeError = GetAuthMeErrors[keyof GetAuthMeErrors];

export type GetAuthMeResponses = {
    /**
     * Current user
     */
    200: User;
};

export type GetAuthMeResponse = GetAuthMeResponses[keyof GetAuthMeResponses];

export type GetUsersIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/users/{id}';
};

export type GetUsersIdErrors = {
    /**
     * Not found
     */
    404: _Error;
};

export type GetUsersIdError = GetUsersIdErrors[keyof GetUsersIdErrors];

export type GetUsersIdResponses = {
    /**
     * User
     */
    200: User;
};

export type GetUsersIdResponse = GetUsersIdResponses[keyof GetUsersIdResponses];

export type GetUsersData = {
    body?: never;
    path?: never;
    query?: {
        limit?: number;
        offset?: number;
    };
    url: '/users';
};

export type GetUsersErrors = {
    /**
     * Forbidden
     */
    403: _Error;
};

export type GetUsersError = GetUsersErrors[keyof GetUsersErrors];

export type GetUsersResponses = {
    /**
     * List of users
     */
    200: Array<User>;
};

export type GetUsersResponse = GetUsersResponses[keyof GetUsersResponses];

export type GetProgramsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/programs';
};

export type GetProgramsResponses = {
    /**
     * List of programs
     */
    200: Array<Program>;
};

export type GetProgramsResponse = GetProgramsResponses[keyof GetProgramsResponses];

export type GetProgramsIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/programs/{id}';
};

export type GetProgramsIdErrors = {
    /**
     * Not found
     */
    404: _Error;
};

export type GetProgramsIdError = GetProgramsIdErrors[keyof GetProgramsIdErrors];

export type GetProgramsIdResponses = {
    /**
     * Program
     */
    200: Program;
};

export type GetProgramsIdResponse = GetProgramsIdResponses[keyof GetProgramsIdResponses];

export type GetProgramModulesData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/programs/{id}/modules';
};

export type GetProgramModulesResponses = {
    /**
     * List of modules
     */
    200: Array<Module>;
};

export type GetProgramModulesResponse = GetProgramModulesResponses[keyof GetProgramModulesResponses];

export type GetExamsData = {
    body?: never;
    path?: never;
    query?: {
        programid?: number;
        version?: string;
        moduleid?: number;
    };
    url: '/exams';
};

export type GetExamsErrors = {
    /**
     * Not authenticated
     */
    401: _Error;
};

export type GetExamsError = GetExamsErrors[keyof GetExamsErrors];

export type GetExamsResponses = {
    /**
     * List of exams
     */
    200: Array<ExamListEntry>;
};

export type GetExamsResponse = GetExamsResponses[keyof GetExamsResponses];

export type PostExamsData = {
    body: {
        file: Blob | File;
        date: string;
        /**
         * JSON string of list of {programid, version, moduleid}
         */
        assignments: string;
        comment?: string;
    };
    headers: {
        'X-CSRF-Token': string;
    };
    path?: never;
    query?: never;
    url: '/exams';
};

export type PostExamsErrors = {
    /**
     * Forbidden
     */
    403: _Error;
};

export type PostExamsError = PostExamsErrors[keyof PostExamsErrors];

export type PostExamsResponses = {
    /**
     * Exam uploaded
     */
    201: ExamListEntry;
};

export type PostExamsResponse = PostExamsResponses[keyof PostExamsResponses];

export type DeleteExamsIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/exams/{id}';
};

export type DeleteExamsIdErrors = {
    /**
     * Not found
     */
    404: _Error;
};

export type DeleteExamsIdError = DeleteExamsIdErrors[keyof DeleteExamsIdErrors];

export type DeleteExamsIdResponses = {
    /**
     * Exam deleted
     */
    204: void;
};

export type DeleteExamsIdResponse = DeleteExamsIdResponses[keyof DeleteExamsIdResponses];

export type PutExamsIdData = {
    body: {
        programid: number;
        version: string;
        moduleid: number;
        date: string;
        comment?: string;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/exams/{id}';
};

export type PutExamsIdErrors = {
    /**
     * Not found
     */
    404: _Error;
};

export type PutExamsIdError = PutExamsIdErrors[keyof PutExamsIdErrors];

export type PutExamsIdResponses = {
    /**
     * Exam updated
     */
    200: ExamListEntry;
};

export type PutExamsIdResponse = PutExamsIdResponses[keyof PutExamsIdResponses];

export type GetExamsFileData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/exams/{id}/file';
};

export type GetExamsFileErrors = {
    /**
     * Not found
     */
    404: _Error;
};

export type GetExamsFileError = GetExamsFileErrors[keyof GetExamsFileErrors];

export type GetExamsFileResponses = {
    /**
     * File content
     */
    200: Blob | File;
};

export type GetExamsFileResponse = GetExamsFileResponses[keyof GetExamsFileResponses];
