// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}/api` | (string & {});
};

export type AuthCommentRequest = {
    parent_id?: string;
    text?: string;
};

export type AuthCommentResponse = {
    active?: number;
    author_avatar_url?: string;
    author_id?: string;
    author_name?: string;
    created_at?: string;
    id?: string;
    parent_id?: string;
    post_id?: string;
    text?: string;
    updated_at?: string;
    user_vote?: number;
    votes?: number;
};

export type AuthCreatePostRequest = {
    body?: string;
    event_date?: string;
    image_url?: string;
    links?: Array<string>;
    location?: string;
    pinned?: number;
    programs?: Array<string>;
    tags?: Array<string>;
    title?: string;
    type?: string;
};

export type AuthCsrfResponse = {
    csrf?: string;
};

export type AuthErrorResponse = {
    error?: string;
    message?: string;
};

/**
 * Exam details
 */
export type AuthExamResponse = {
    comment?: string;
    edit_version?: number;
    exam_date?: string;
    group_id?: string;
    id?: string;
    is_latest?: number;
    module_name?: string;
    moduleid?: number;
    programid?: number;
    uploaded_at?: string;
    uploader_name?: string;
    version?: string;
};

export type AuthLoginRequest = {
    email?: string;
    password?: string;
};

/**
 * A study module
 */
export type AuthModuleResponse = {
    alias?: string;
    id?: number;
    name?: string;
    programid?: number;
};

export type AuthNotificationResponse = {
    created_at?: string;
    id?: string;
    link?: string;
    message?: string;
    read?: boolean;
    title?: string;
    type?: string;
};

export type AuthPostResponse = {
    active?: number;
    author_avatar_url?: string;
    author_id?: string;
    author_name?: string;
    body?: string;
    comment_count?: number;
    created_at?: string;
    event_date?: string;
    id?: string;
    image_url?: string;
    links?: string;
    location?: string;
    pinned?: number;
    programs?: string;
    tags?: string;
    title?: string;
    type?: string;
    updated_at?: string;
    user_vote?: number;
    votes?: number;
};

/**
 * A study program including valid PO versions
 */
export type AuthProgramResponse = {
    id?: number;
    name?: string;
    versions?: Array<string>;
};

export type AuthPublicUserResponse = {
    active?: number;
    avatar_url?: string;
    created_at?: string;
    id?: string;
    name?: string;
    private?: number;
    programid?: number;
    role?: string;
    theme?: string;
    verified?: number;
};

export type AuthRegisterRequest = {
    email?: string;
    name?: string;
    password?: string;
    programid?: number;
};

export type AuthSearchResult = {
    id?: string;
    subtitle?: string;
    title?: string;
    /**
     * "exam" or "module"
     */
    type?: string;
    url?: string;
};

export type AuthUpdateExamRequest = {
    comment?: string;
    date?: string;
    moduleid?: number;
    programid?: number;
    version?: string;
};

export type AuthUpdateProfileRequest = {
    name?: string;
    private?: boolean;
    programid?: number;
    theme?: string;
};

/**
 * User account information
 */
export type AuthUserResponse = {
    active?: number;
    avatar_url?: string;
    created_at?: string;
    email?: string;
    id?: string;
    name?: string;
    password?: string;
    private?: number;
    programid?: number;
    role?: string;
    theme?: string;
    updated_at?: string;
    verification_token?: string;
    verified?: number;
    verified_at?: string;
    verified_until?: string;
};

export type AuthVoteRequest = {
    /**
     * 1 or -1
     */
    vote?: number;
};

export type DatabaseActivity = {
    created_at?: string;
    id?: string;
    target_id?: string;
    target_name?: string;
    type?: string;
    user_id?: string;
};

export type DatabaseForumComment = {
    active?: number;
    author_id?: string;
    created_at?: string;
    id?: string;
    parent_id?: string;
    post_id?: string;
    text?: string;
    updated_at?: string;
};

export type DatabaseForumPost = {
    active?: number;
    author_id?: string;
    body?: string;
    created_at?: string;
    event_date?: string;
    id?: string;
    image_url?: string;
    links?: string;
    location?: string;
    pinned?: number;
    programs?: string;
    tags?: string;
    title?: string;
    type?: string;
    updated_at?: string;
};

export type GetActivitiesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Limit
         */
        limit?: number;
        /**
         * Offset
         */
        offset?: number;
    };
    url: '/activities';
};

export type GetActivitiesResponses = {
    /**
     * OK
     */
    200: Array<DatabaseActivity>;
};

export type GetActivitiesResponse = GetActivitiesResponses[keyof GetActivitiesResponses];

export type GetAuthAvatarsByUserIdByFilenameData = {
    body?: never;
    path: {
        /**
         * User ID
         */
        userId: string;
        /**
         * Filename
         */
        filename: string;
    };
    query?: never;
    url: '/auth/avatars/{userId}/{filename}';
};

export type GetAuthAvatarsByUserIdByFilenameResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetAuthCsrfData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/csrf';
};

export type GetAuthCsrfResponses = {
    /**
     * OK
     */
    200: AuthCsrfResponse;
};

export type GetAuthCsrfResponse = GetAuthCsrfResponses[keyof GetAuthCsrfResponses];

export type PostAuthLoginData = {
    /**
     * Login Credentials
     */
    body: AuthLoginRequest;
    path?: never;
    query?: never;
    url: '/auth/login';
};

export type PostAuthLoginErrors = {
    /**
     * Unauthorized
     */
    401: AuthErrorResponse;
};

export type PostAuthLoginError = PostAuthLoginErrors[keyof PostAuthLoginErrors];

export type PostAuthLoginResponses = {
    /**
     * OK
     */
    200: AuthUserResponse;
};

export type PostAuthLoginResponse = PostAuthLoginResponses[keyof PostAuthLoginResponses];

export type PostAuthLogoutData = {
    body?: never;
    headers: {
        /**
         * CSRF Token
         */
        'X-CSRF-Token': string;
    };
    path?: never;
    query?: never;
    url: '/auth/logout';
};

export type PostAuthLogoutResponses = {
    /**
     * No Content
     */
    204: unknown;
};

export type GetAuthMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/me';
};

export type GetAuthMeResponses = {
    /**
     * OK
     */
    200: AuthUserResponse;
};

export type GetAuthMeResponse = GetAuthMeResponses[keyof GetAuthMeResponses];

export type PutAuthMeData = {
    /**
     * Update Profile Info
     */
    body: AuthUpdateProfileRequest;
    path?: never;
    query?: never;
    url: '/auth/me';
};

export type PutAuthMeErrors = {
    /**
     * Unauthorized
     */
    401: AuthErrorResponse;
};

export type PutAuthMeError = PutAuthMeErrors[keyof PutAuthMeErrors];

export type PutAuthMeResponses = {
    /**
     * OK
     */
    200: AuthUserResponse;
};

export type PutAuthMeResponse = PutAuthMeResponses[keyof PutAuthMeResponses];

export type PostAuthMeAvatarGenerateData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/me/avatar/generate';
};

export type PostAuthMeAvatarGenerateErrors = {
    /**
     * Unauthorized
     */
    401: AuthErrorResponse;
};

export type PostAuthMeAvatarGenerateError = PostAuthMeAvatarGenerateErrors[keyof PostAuthMeAvatarGenerateErrors];

export type PostAuthMeAvatarGenerateResponses = {
    /**
     * No Content
     */
    204: unknown;
};

export type GetAuthNotificationsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/notifications';
};

export type GetAuthNotificationsErrors = {
    /**
     * Unauthorized
     */
    401: AuthErrorResponse;
};

export type GetAuthNotificationsError = GetAuthNotificationsErrors[keyof GetAuthNotificationsErrors];

export type GetAuthNotificationsResponses = {
    /**
     * OK
     */
    200: Array<AuthNotificationResponse>;
};

export type GetAuthNotificationsResponse = GetAuthNotificationsResponses[keyof GetAuthNotificationsResponses];

export type PutAuthNotificationsIdReadData = {
    body?: never;
    path: {
        /**
         * Notification ID
         */
        id: string;
    };
    query?: never;
    url: '/auth/notifications/{id}/read';
};

export type PutAuthNotificationsIdReadErrors = {
    /**
     * Unauthorized
     */
    401: AuthErrorResponse;
    /**
     * Not Found
     */
    404: AuthErrorResponse;
};

export type PutAuthNotificationsIdReadError = PutAuthNotificationsIdReadErrors[keyof PutAuthNotificationsIdReadErrors];

export type PutAuthNotificationsIdReadResponses = {
    /**
     * OK
     */
    200: AuthNotificationResponse;
};

export type PutAuthNotificationsIdReadResponse = PutAuthNotificationsIdReadResponses[keyof PutAuthNotificationsIdReadResponses];

export type PutAuthNotificationsReadAllData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/notifications/read-all';
};

export type PutAuthNotificationsReadAllErrors = {
    /**
     * Unauthorized
     */
    401: AuthErrorResponse;
};

export type PutAuthNotificationsReadAllError = PutAuthNotificationsReadAllErrors[keyof PutAuthNotificationsReadAllErrors];

export type PutAuthNotificationsReadAllResponses = {
    /**
     * No Content
     */
    204: unknown;
};

export type PostAuthRegisterData = {
    /**
     * Registration Info
     */
    body: AuthRegisterRequest;
    path?: never;
    query?: never;
    url: '/auth/register';
};

export type PostAuthRegisterErrors = {
    /**
     * Bad Request
     */
    400: AuthErrorResponse;
};

export type PostAuthRegisterError = PostAuthRegisterErrors[keyof PostAuthRegisterErrors];

export type PostAuthRegisterResponses = {
    /**
     * Created
     */
    201: AuthUserResponse;
};

export type PostAuthRegisterResponse = PostAuthRegisterResponses[keyof PostAuthRegisterResponses];

export type GetAuthVerifyData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Verification Token
         */
        token: string;
    };
    url: '/auth/verify';
};

export type GetExamsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Program ID
         */
        programid?: number;
        /**
         * Version
         */
        version?: string;
        /**
         * Module ID
         */
        moduleid?: number;
    };
    url: '/exams';
};

export type GetExamsErrors = {
    /**
     * Unauthorized
     */
    401: AuthErrorResponse;
};

export type GetExamsError = GetExamsErrors[keyof GetExamsErrors];

export type GetExamsResponses = {
    /**
     * OK
     */
    200: Array<AuthExamResponse>;
};

export type GetExamsResponse = GetExamsResponses[keyof GetExamsResponses];

export type PostExamsData = {
    body: {
        /**
         * Exam PDF
         */
        file: Blob | File;
        /**
         * Exam Date (YYYY-MM-DD)
         */
        date: string;
        /**
         * JSON array of assignments: [{'programid':1, 'version':'PO2016', 'moduleid':10}]
         */
        assignments: string;
        /**
         * Optional comment
         */
        comment?: string;
    };
    headers: {
        /**
         * CSRF Token
         */
        'X-CSRF-Token': string;
    };
    path?: never;
    query?: never;
    url: '/exams';
};

export type PostExamsErrors = {
    /**
     * Bad Request
     */
    400: AuthErrorResponse;
    /**
     * Forbidden
     */
    403: AuthErrorResponse;
};

export type PostExamsError = PostExamsErrors[keyof PostExamsErrors];

export type PostExamsResponses = {
    /**
     * Created
     */
    201: {
        [key: string]: string;
    };
};

export type PostExamsResponse = PostExamsResponses[keyof PostExamsResponses];

export type DeleteExamsIdData = {
    body?: never;
    path: {
        /**
         * Exam ID
         */
        id: string;
    };
    query?: never;
    url: '/exams/{id}';
};

export type DeleteExamsIdResponses = {
    /**
     * No Content
     */
    204: unknown;
};

export type GetExamsIdData = {
    body?: never;
    path: {
        /**
         * Exam ID
         */
        id: string;
    };
    query?: never;
    url: '/exams/{id}';
};

export type GetExamsIdErrors = {
    /**
     * Not Found
     */
    404: AuthErrorResponse;
};

export type GetExamsIdError = GetExamsIdErrors[keyof GetExamsIdErrors];

export type GetExamsIdResponses = {
    /**
     * OK
     */
    200: AuthExamResponse;
};

export type GetExamsIdResponse = GetExamsIdResponses[keyof GetExamsIdResponses];

export type PutExamsIdData = {
    /**
     * Update Data
     */
    body: AuthUpdateExamRequest;
    path: {
        /**
         * Exam ID
         */
        id: string;
    };
    query?: never;
    url: '/exams/{id}';
};

export type PutExamsIdResponses = {
    /**
     * OK
     */
    200: AuthExamResponse;
};

export type PutExamsIdResponse = PutExamsIdResponses[keyof PutExamsIdResponses];

export type GetExamsFileData = {
    body?: never;
    path: {
        /**
         * Exam ID
         */
        id: string;
    };
    query?: never;
    url: '/exams/{id}/file';
};

export type GetExamsFileResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetExamVersionsData = {
    body?: never;
    path: {
        /**
         * Exam Group ID
         */
        groupId: string;
    };
    query?: never;
    url: '/exams/versions/{groupId}';
};

export type GetExamVersionsErrors = {
    /**
     * Unauthorized
     */
    401: AuthErrorResponse;
};

export type GetExamVersionsError = GetExamVersionsErrors[keyof GetExamVersionsErrors];

export type GetExamVersionsResponses = {
    /**
     * OK
     */
    200: Array<AuthExamResponse>;
};

export type GetExamVersionsResponse = GetExamVersionsResponses[keyof GetExamVersionsResponses];

export type PutForumCommentsByIdData = {
    /**
     * Comment Content
     */
    body: AuthCommentRequest;
    path: {
        /**
         * Comment ID
         */
        id: string;
    };
    query?: never;
    url: '/forum/comments/{id}';
};

export type PutForumCommentsByIdResponses = {
    /**
     * OK
     */
    200: DatabaseForumComment;
};

export type PutForumCommentsByIdResponse = PutForumCommentsByIdResponses[keyof PutForumCommentsByIdResponses];

export type PostForumCommentsByIdVoteData = {
    /**
     * Vote Value
     */
    body: AuthVoteRequest;
    path: {
        /**
         * Comment ID
         */
        id: string;
    };
    query?: never;
    url: '/forum/comments/{id}/vote';
};

export type PostForumCommentsByIdVoteResponses = {
    /**
     * No Content
     */
    204: unknown;
};

export type GetForumPostsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Post type (forum, news, event)
         */
        type?: string;
        /**
         * Limit
         */
        limit?: number;
        /**
         * Offset
         */
        offset?: number;
    };
    url: '/forum/posts';
};

export type GetForumPostsResponses = {
    /**
     * OK
     */
    200: Array<AuthPostResponse>;
};

export type GetForumPostsResponse = GetForumPostsResponses[keyof GetForumPostsResponses];

export type PostForumPostsData = {
    /**
     * Post Content
     */
    body: AuthCreatePostRequest;
    path?: never;
    query?: never;
    url: '/forum/posts';
};

export type PostForumPostsResponses = {
    /**
     * Created
     */
    201: DatabaseForumPost;
};

export type PostForumPostsResponse = PostForumPostsResponses[keyof PostForumPostsResponses];

export type DeleteForumPostsByIdData = {
    body?: never;
    path: {
        /**
         * Post ID
         */
        id: string;
    };
    query?: never;
    url: '/forum/posts/{id}';
};

export type DeleteForumPostsByIdResponses = {
    /**
     * No Content
     */
    204: unknown;
};

export type GetForumPostsByIdData = {
    body?: never;
    path: {
        /**
         * Post ID
         */
        id: string;
    };
    query?: never;
    url: '/forum/posts/{id}';
};

export type GetForumPostsByIdResponses = {
    /**
     * OK
     */
    200: AuthPostResponse;
};

export type GetForumPostsByIdResponse = GetForumPostsByIdResponses[keyof GetForumPostsByIdResponses];

export type PutForumPostsByIdData = {
    /**
     * Post Content
     */
    body: AuthCreatePostRequest;
    path: {
        /**
         * Post ID
         */
        id: string;
    };
    query?: never;
    url: '/forum/posts/{id}';
};

export type PutForumPostsByIdResponses = {
    /**
     * OK
     */
    200: DatabaseForumPost;
};

export type PutForumPostsByIdResponse = PutForumPostsByIdResponses[keyof PutForumPostsByIdResponses];

export type GetForumPostsByIdCommentsData = {
    body?: never;
    path: {
        /**
         * Post ID
         */
        id: string;
    };
    query?: never;
    url: '/forum/posts/{id}/comments';
};

export type GetForumPostsByIdCommentsResponses = {
    /**
     * OK
     */
    200: Array<AuthCommentResponse>;
};

export type GetForumPostsByIdCommentsResponse = GetForumPostsByIdCommentsResponses[keyof GetForumPostsByIdCommentsResponses];

export type PostForumPostsByIdCommentsData = {
    /**
     * Comment Content
     */
    body: AuthCommentRequest;
    path: {
        /**
         * Post ID
         */
        id: string;
    };
    query?: never;
    url: '/forum/posts/{id}/comments';
};

export type PostForumPostsByIdCommentsResponses = {
    /**
     * Created
     */
    201: DatabaseForumComment;
};

export type PostForumPostsByIdCommentsResponse = PostForumPostsByIdCommentsResponses[keyof PostForumPostsByIdCommentsResponses];

export type PostForumPostsByIdVoteData = {
    /**
     * Vote Value
     */
    body: AuthVoteRequest;
    path: {
        /**
         * Post ID
         */
        id: string;
    };
    query?: never;
    url: '/forum/posts/{id}/vote';
};

export type PostForumPostsByIdVoteResponses = {
    /**
     * No Content
     */
    204: unknown;
};

export type GetProgramsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/programs';
};

export type GetProgramsErrors = {
    /**
     * Internal Server Error
     */
    500: AuthErrorResponse;
};

export type GetProgramsError = GetProgramsErrors[keyof GetProgramsErrors];

export type GetProgramsResponses = {
    /**
     * OK
     */
    200: Array<AuthProgramResponse>;
};

export type GetProgramsResponse = GetProgramsResponses[keyof GetProgramsResponses];

export type GetProgramsIdData = {
    body?: never;
    path: {
        /**
         * Program ID
         */
        id: number;
    };
    query?: never;
    url: '/programs/{id}';
};

export type GetProgramsIdErrors = {
    /**
     * Not Found
     */
    404: AuthErrorResponse;
    /**
     * Internal Server Error
     */
    500: AuthErrorResponse;
};

export type GetProgramsIdError = GetProgramsIdErrors[keyof GetProgramsIdErrors];

export type GetProgramsIdResponses = {
    /**
     * OK
     */
    200: AuthProgramResponse;
};

export type GetProgramsIdResponse = GetProgramsIdResponses[keyof GetProgramsIdResponses];

export type GetProgramModulesData = {
    body?: never;
    path: {
        /**
         * Program ID
         */
        id: number;
    };
    query?: never;
    url: '/programs/{id}/modules';
};

export type GetProgramModulesErrors = {
    /**
     * Internal Server Error
     */
    500: AuthErrorResponse;
};

export type GetProgramModulesError = GetProgramModulesErrors[keyof GetProgramModulesErrors];

export type GetProgramModulesResponses = {
    /**
     * OK
     */
    200: Array<AuthModuleResponse>;
};

export type GetProgramModulesResponse = GetProgramModulesResponses[keyof GetProgramModulesResponses];

export type GetSearchData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Search query
         */
        q: string;
    };
    url: '/search';
};

export type GetSearchResponses = {
    /**
     * OK
     */
    200: Array<AuthSearchResult>;
};

export type GetSearchResponse = GetSearchResponses[keyof GetSearchResponses];

export type GetUsersData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Limit
         */
        limit?: number;
        /**
         * Offset
         */
        offset?: number;
    };
    url: '/users';
};

export type GetUsersResponses = {
    /**
     * OK
     */
    200: Array<AuthUserResponse>;
};

export type GetUsersResponse = GetUsersResponses[keyof GetUsersResponses];

export type GetUsersByIdData = {
    body?: never;
    path: {
        /**
         * User ID
         */
        id: string;
    };
    query?: never;
    url: '/users/{id}';
};

export type GetUsersByIdResponses = {
    /**
     * OK
     */
    200: AuthPublicUserResponse;
};

export type GetUsersByIdResponse = GetUsersByIdResponses[keyof GetUsersByIdResponses];

export type GetUsersByIdActivitiesData = {
    body?: never;
    path: {
        /**
         * User ID
         */
        id: string;
    };
    query?: {
        /**
         * Limit
         */
        limit?: number;
        /**
         * Offset
         */
        offset?: number;
    };
    url: '/users/{id}/activities';
};

export type GetUsersByIdActivitiesResponses = {
    /**
     * OK
     */
    200: Array<DatabaseActivity>;
};

export type GetUsersByIdActivitiesResponse = GetUsersByIdActivitiesResponses[keyof GetUsersByIdActivitiesResponses];
