// This file is auto-generated by @hey-api/openapi-ts

import { z } from 'zod';

export const zDtoActivityResponse = z.object({
    created_at: z.optional(z.string()),
    id: z.optional(z.string()),
    target_id: z.optional(z.string()),
    target_name: z.optional(z.string()),
    type: z.optional(z.string()),
    user_id: z.optional(z.string()),
    user_name: z.optional(z.string())
});

export const zDtoCommentRequest = z.object({
    parent_id: z.optional(z.string()),
    text: z.string().min(1).max(2000)
});

export const zDtoCommentResponse = z.object({
    author_avatar_url: z.optional(z.string()),
    author_id: z.optional(z.string()),
    author_name: z.optional(z.string()),
    created_at: z.optional(z.string()),
    id: z.optional(z.string()),
    parent_id: z.optional(z.string()),
    post_id: z.optional(z.string()),
    text: z.optional(z.string()),
    updated_at: z.optional(z.string()),
    user_vote: z.optional(z.int()),
    votes: z.optional(z.int())
});

export const zDtoCreatePostRequest = z.object({
    body: z.string().min(10).max(10000),
    event_date: z.optional(z.string()),
    image_url: z.optional(z.string()),
    links: z.optional(z.array(z.string())),
    location: z.optional(z.string()),
    pinned: z.optional(z.int()),
    programs: z.optional(z.array(z.string())),
    tags: z.optional(z.array(z.string())),
    title: z.string().min(3).max(255),
    type: z.optional(z.enum([
        'forum',
        'news',
        'event'
    ]))
});

export const zDtoCsrfResponse = z.object({
    csrf: z.optional(z.string())
});

export const zDtoErrorResponse = z.object({
    error: z.optional(z.string()),
    message: z.optional(z.string())
});

export const zDtoEventResponse = z.object({
    cover_path: z.optional(z.string()),
    created_at: z.optional(z.string()),
    id: z.optional(z.string()),
    title: z.optional(z.string())
});

export const zDtoExamResponse = z.object({
    comment: z.optional(z.string()),
    edit_version: z.optional(z.int()),
    exam_date: z.optional(z.string()),
    group_id: z.optional(z.string()),
    id: z.optional(z.string()),
    is_latest: z.optional(z.int()),
    module_name: z.optional(z.string()),
    moduleid: z.optional(z.string()),
    programid: z.optional(z.string()),
    uploaded_at: z.optional(z.string()),
    uploader_name: z.optional(z.string()),
    version: z.optional(z.string())
});

export const zDtoLoginRequest = z.object({
    email: z.string(),
    password: z.string().min(8).max(72),
    remember: z.optional(z.boolean())
});

export const zDtoMediaResponse = z.object({
    description: z.optional(z.string()),
    event_id: z.optional(z.string()),
    id: z.optional(z.string()),
    mime_type: z.optional(z.string()),
    title: z.optional(z.string()),
    uploaded_at: z.optional(z.string()),
    uploader_name: z.optional(z.string())
});

export const zDtoModuleResponse = z.object({
    alias: z.optional(z.string()),
    id: z.optional(z.string()),
    name: z.optional(z.string()),
    programid: z.optional(z.string())
});

export const zDtoNotificationResponse = z.object({
    created_at: z.optional(z.string()),
    id: z.optional(z.string()),
    link: z.optional(z.string()),
    message: z.optional(z.string()),
    read: z.optional(z.boolean()),
    title: z.optional(z.string()),
    type: z.optional(z.string())
});

export const zDtoPostResponse = z.object({
    active: z.optional(z.int()),
    author_avatar_url: z.optional(z.string()),
    author_id: z.optional(z.string()),
    author_name: z.optional(z.string()),
    body: z.optional(z.string()),
    comment_count: z.optional(z.int()),
    created_at: z.optional(z.string()),
    event_date: z.optional(z.string()),
    id: z.optional(z.string()),
    image_url: z.optional(z.string()),
    links: z.optional(z.array(z.string())),
    location: z.optional(z.string()),
    pinned: z.optional(z.int()),
    programs: z.optional(z.array(z.string())),
    tags: z.optional(z.array(z.string())),
    title: z.optional(z.string()),
    type: z.optional(z.string()),
    updated_at: z.optional(z.string()),
    user_vote: z.optional(z.int()),
    votes: z.optional(z.int())
});

export const zDtoProgramResponse = z.object({
    id: z.optional(z.string()),
    name: z.optional(z.string()),
    versions: z.optional(z.array(z.string()))
});

export const zDtoPublicUserResponse = z.object({
    active: z.optional(z.int()),
    avatar_url: z.optional(z.string()),
    created_at: z.optional(z.string()),
    id: z.optional(z.string()),
    name: z.optional(z.string()),
    private: z.optional(z.int()),
    programid: z.optional(z.string()),
    role: z.optional(z.string()),
    theme: z.optional(z.string()),
    verified: z.optional(z.int())
});

export const zDtoRegisterRequest = z.object({
    email: z.string(),
    name: z.string().min(2).max(64),
    password: z.string().min(8).max(72),
    programid: z.string()
});

export const zDtoSearchResult = z.object({
    id: z.optional(z.string()),
    subtitle: z.optional(z.string()),
    title: z.optional(z.string()),
    type: z.optional(z.string()),
    url: z.optional(z.string())
});

export const zDtoUpdateExamRequest = z.object({
    comment: z.optional(z.string().max(1000)),
    date: z.string(),
    moduleid: z.string(),
    programid: z.string(),
    version: z.string().min(2).max(32)
});

export const zDtoUpdateProfileRequest = z.object({
    name: z.string().min(2).max(64),
    private: z.optional(z.boolean()),
    programid: z.string(),
    theme: z.enum([
        'light',
        'dark',
        'system'
    ])
});

export const zDtoUserResponse = z.object({
    active: z.optional(z.int()),
    avatar_url: z.optional(z.string()),
    created_at: z.optional(z.string()),
    email: z.optional(z.string()),
    id: z.optional(z.string()),
    name: z.optional(z.string()),
    private: z.optional(z.int()),
    programid: z.optional(z.string()),
    role: z.optional(z.string()),
    theme: z.optional(z.string()),
    verified: z.optional(z.int())
});

export const zDtoVoteRequest = z.object({
    vote: z.optional(z.union([
        z.literal(1),
        z.literal(-1),
        z.literal(0)
    ]))
});

export const zGetActivitiesData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.object({
        limit: z.optional(z.int()),
        offset: z.optional(z.int())
    }))
});

/**
 * OK
 */
export const zGetActivitiesResponse = z.array(zDtoActivityResponse);

export const zGetAuthAvatarsByUserIdByFilenameData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        userId: z.string(),
        filename: z.string()
    }),
    query: z.optional(z.never())
});

export const zGetAuthCsrfData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zGetAuthCsrfResponse = zDtoCsrfResponse;

export const zPostAuthLoginData = z.object({
    body: zDtoLoginRequest,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zPostAuthLoginResponse = zDtoUserResponse;

export const zPostAuthLogoutData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never()),
    headers: z.object({
        'X-CSRF-Token': z.string()
    })
});

export const zGetAuthMeData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zGetAuthMeResponse = zDtoUserResponse;

export const zPutAuthMeData = z.object({
    body: zDtoUpdateProfileRequest,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zPutAuthMeResponse = zDtoUserResponse;

export const zGetAuthNotificationsData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zGetAuthNotificationsResponse = z.array(zDtoNotificationResponse);

export const zPutAuthNotificationsIdReadData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        id: z.string()
    }),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zPutAuthNotificationsIdReadResponse = zDtoNotificationResponse;

export const zPutAuthNotificationsReadAllData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export const zPostAuthRegisterData = z.object({
    body: zDtoRegisterRequest,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * Created
 */
export const zPostAuthRegisterResponse = zDtoUserResponse;

export const zGetAuthVerifyData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.object({
        token: z.string()
    })
});

export const zGetEventsData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zGetEventsResponse = z.array(zDtoEventResponse);

export const zPostEventsData = z.object({
    body: z.object({
        title: z.string(),
        file: z.optional(z.string())
    }),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * Created
 */
export const zPostEventsResponse = zDtoEventResponse;

export const zGetEventsByIdCoverData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        id: z.string()
    }),
    query: z.optional(z.never())
});

export const zGetExamsData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.object({
        programid: z.optional(z.string()),
        version: z.optional(z.string()),
        moduleid: z.optional(z.string())
    }))
});

/**
 * OK
 */
export const zGetExamsResponse = z.array(zDtoExamResponse);

export const zPostExamsData = z.object({
    body: z.object({
        file: z.string(),
        date: z.string(),
        assignments: z.string(),
        comment: z.optional(z.string())
    }),
    path: z.optional(z.never()),
    query: z.optional(z.never()),
    headers: z.object({
        'X-CSRF-Token': z.string()
    })
});

/**
 * Created
 */
export const zPostExamsResponse = z.record(z.string(), z.string());

export const zDeleteExamsIdData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        id: z.string()
    }),
    query: z.optional(z.never())
});

export const zGetExamsIdData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        id: z.string()
    }),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zGetExamsIdResponse = zDtoExamResponse;

export const zPutExamsIdData = z.object({
    body: zDtoUpdateExamRequest,
    path: z.object({
        id: z.string()
    }),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zPutExamsIdResponse = zDtoExamResponse;

export const zGetExamsFileData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        id: z.string()
    }),
    query: z.optional(z.never())
});

export const zGetExamVersionsData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        groupId: z.string()
    }),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zGetExamVersionsResponse = z.array(zDtoExamResponse);

export const zPutForumCommentsByIdData = z.object({
    body: zDtoCommentRequest,
    path: z.object({
        id: z.string()
    }),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zPutForumCommentsByIdResponse = zDtoCommentResponse;

export const zPostForumCommentsByIdVoteData = z.object({
    body: zDtoVoteRequest,
    path: z.object({
        id: z.string()
    }),
    query: z.optional(z.never())
});

export const zGetForumPostsData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.object({
        type: z.optional(z.string()),
        query: z.optional(z.string()),
        sort: z.optional(z.string()),
        limit: z.optional(z.int()),
        offset: z.optional(z.int())
    }))
});

/**
 * OK
 */
export const zGetForumPostsResponse = z.array(zDtoPostResponse);

export const zPostForumPostsData = z.object({
    body: zDtoCreatePostRequest,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * Created
 */
export const zPostForumPostsResponse = zDtoPostResponse;

export const zDeleteForumPostsByIdData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        id: z.string()
    }),
    query: z.optional(z.never())
});

export const zGetForumPostsByIdData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        id: z.string()
    }),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zGetForumPostsByIdResponse = zDtoPostResponse;

export const zPutForumPostsByIdData = z.object({
    body: zDtoCreatePostRequest,
    path: z.object({
        id: z.string()
    }),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zPutForumPostsByIdResponse = zDtoPostResponse;

export const zGetForumPostsByIdCommentsData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        id: z.string()
    }),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zGetForumPostsByIdCommentsResponse = z.array(zDtoCommentResponse);

export const zPostForumPostsByIdCommentsData = z.object({
    body: zDtoCommentRequest,
    path: z.object({
        id: z.string()
    }),
    query: z.optional(z.never())
});

/**
 * Created
 */
export const zPostForumPostsByIdCommentsResponse = zDtoCommentResponse;

export const zPostForumPostsByIdVoteData = z.object({
    body: zDtoVoteRequest,
    path: z.object({
        id: z.string()
    }),
    query: z.optional(z.never())
});

export const zGetMediaData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.object({
        event_id: z.string()
    })
});

/**
 * OK
 */
export const zGetMediaResponse = z.array(zDtoMediaResponse);

export const zPostMediaData = z.object({
    body: z.object({
        event_id: z.string(),
        title: z.optional(z.string()),
        description: z.optional(z.string()),
        file: z.string()
    }),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * Created
 */
export const zPostMediaResponse = z.record(z.string(), z.string());

export const zGetMediaByIdData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        id: z.string()
    }),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zGetMediaByIdResponse = zDtoMediaResponse;

export const zGetMediaByIdFileData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        id: z.string()
    }),
    query: z.optional(z.never())
});

export const zGetMediaByIdPreviewData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        id: z.string()
    }),
    query: z.optional(z.never())
});

export const zGetProgramsData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zGetProgramsResponse = z.array(zDtoProgramResponse);

export const zGetProgramsIdData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        id: z.int()
    }),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zGetProgramsIdResponse = zDtoProgramResponse;

export const zGetProgramModulesData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        id: z.string()
    }),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zGetProgramModulesResponse = z.array(zDtoModuleResponse);

export const zGetSearchData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.object({
        q: z.string()
    })
});

/**
 * OK
 */
export const zGetSearchResponse = z.array(zDtoSearchResult);

export const zGetUsersData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.object({
        limit: z.optional(z.int()),
        offset: z.optional(z.int())
    }))
});

/**
 * OK
 */
export const zGetUsersResponse = z.array(zDtoUserResponse);

export const zGetUsersByIdData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        id: z.string()
    }),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zGetUsersByIdResponse = zDtoPublicUserResponse;

export const zGetUsersByIdActivitiesData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        id: z.string()
    }),
    query: z.optional(z.object({
        limit: z.optional(z.int()),
        offset: z.optional(z.int())
    }))
});

/**
 * OK
 */
export const zGetUsersByIdActivitiesResponse = z.array(zDtoActivityResponse);
