// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

export const zDtoActivityResponse = z.object({
    created_at: z.string().optional(),
    id: z.string().optional(),
    target_id: z.string().optional(),
    target_name: z.string().optional(),
    type: z.string().optional(),
    user_id: z.string().optional(),
    user_name: z.string().optional()
});

export const zDtoAdminStatsResponse = z.object({
    activity_count: z.int().optional(),
    archive_count: z.int().optional(),
    event_count: z.int().optional(),
    module_count: z.int().optional(),
    post_count: z.int().optional(),
    program_count: z.int().optional(),
    session_count: z.int().optional(),
    user_count: z.int().optional()
});

export const zDtoArchiveEntryResponse = z.object({
    comment: z.string().optional(),
    created_at: z.string().optional(),
    edit_version: z.int().optional(),
    exam_date: z.string().optional(),
    file_id: z.string().optional(),
    id: z.string().optional(),
    module_id: z.string().optional(),
    module_name: z.string().optional(),
    program_id: z.string().optional(),
    uploader_name: z.string().optional(),
    version: z.string().optional()
});

export const zDtoDashboardTrendItem = z.object({
    count: z.int().optional(),
    date: z.string().optional()
});

export const zDtoDiscussionCommentRequest = z.object({
    parent_id: z.string().optional(),
    text: z.string().min(1).max(2000)
});

export const zDtoDiscussionCommentResponse = z.object({
    created_at: z.string().optional(),
    id: z.string().optional(),
    parent_id: z.string().optional(),
    post_id: z.string().optional(),
    text: z.string().optional(),
    updated_at: z.string().optional(),
    user_avatar_url: z.string().optional(),
    user_id: z.string().optional(),
    user_name: z.string().optional(),
    user_vote: z.int().optional(),
    votes: z.int().optional()
});

export const zDtoErrorResponse = z.object({
    error: z.string().optional(),
    message: z.string().optional()
});

export const zDtoEventResponse = z.object({
    cover_path: z.string().optional(),
    created_at: z.string().optional(),
    id: z.string().optional(),
    title: z.string().optional()
});

export const zDtoForgotPasswordRequest = z.object({
    email: z.string()
});

export const zDtoLink = z.object({
    label: z.string().optional(),
    url: z.string().optional()
});

export const zDtoCreateDiscussionPostRequest = z.object({
    body: z.string().min(10).max(10000),
    event_date: z.string().optional(),
    image_url: z.string().optional(),
    links: z.array(zDtoLink).optional(),
    location: z.string().optional(),
    pinned: z.boolean().optional(),
    programs: z.array(z.string()).optional(),
    tags: z.array(z.string()).optional(),
    title: z.string().min(3).max(255),
    type: z.enum([
        'discussion',
        'news',
        'event'
    ]).optional()
});

export const zDtoLoginRequest = z.object({
    email: z.string(),
    password: z.string().min(8).max(72),
    remember: z.boolean().optional()
});

export const zDtoMediaResponse = z.object({
    created_at: z.string().optional(),
    description: z.string().optional(),
    event_id: z.string().optional(),
    id: z.string().optional(),
    mime_type: z.string().optional(),
    title: z.string().optional(),
    uploader_name: z.string().optional()
});

export const zDtoModuleResponse = z.object({
    alias: z.string().optional(),
    id: z.string().optional(),
    name: z.string().optional(),
    program_id: z.string().optional()
});

export const zDtoNotificationResponse = z.object({
    created_at: z.string().optional(),
    id: z.string().optional(),
    link: z.string().optional(),
    message: z.string().optional(),
    read: z.boolean().optional(),
    title: z.string().optional(),
    type: z.string().optional(),
    user_id: z.string().optional()
});

export const zDtoOfficeStatusResponse = z.object({
    occupied: z.boolean().optional()
});

export const zDtoPostProgramResponse = z.object({
    id: z.string().optional(),
    name: z.string().optional()
});

export const zDtoDiscussionPostResponse = z.object({
    body: z.string().optional(),
    comment_count: z.int().optional(),
    created_at: z.string().optional(),
    event_date: z.string().optional(),
    id: z.string().optional(),
    image_url: z.string().optional(),
    links: z.array(zDtoLink).optional(),
    location: z.string().optional(),
    pinned: z.int().optional(),
    programs: z.array(zDtoPostProgramResponse).optional(),
    tags: z.array(z.string()).optional(),
    title: z.string().optional(),
    type: z.string().optional(),
    updated_at: z.string().optional(),
    user_avatar_url: z.string().optional(),
    user_id: z.string().optional(),
    user_name: z.string().optional(),
    user_vote: z.int().optional(),
    votes: z.int().optional()
});

export const zDtoProgramDistributionItem = z.object({
    name: z.string().optional(),
    value: z.int().optional()
});

export const zDtoAdminDashboardResponse = z.object({
    activity_trend: z.array(zDtoDashboardTrendItem).optional(),
    discussion_growth_trend: z.array(zDtoDashboardTrendItem).optional(),
    exam_growth_trend: z.array(zDtoDashboardTrendItem).optional(),
    module_growth_trend: z.array(zDtoDashboardTrendItem).optional(),
    program_distribution: z.array(zDtoProgramDistributionItem).optional(),
    program_growth_trend: z.array(zDtoDashboardTrendItem).optional(),
    recent_activities: z.array(zDtoActivityResponse).optional(),
    session_trend: z.array(zDtoDashboardTrendItem).optional(),
    stats: zDtoAdminStatsResponse.optional(),
    user_growth_trend: z.array(zDtoDashboardTrendItem).optional()
});

export const zDtoProgramResponse = z.object({
    id: z.string().optional(),
    name: z.string().optional(),
    versions: z.array(z.string()).optional()
});

export const zDtoPublicUserResponse = z.object({
    active: z.int().optional(),
    avatar_url: z.string().optional(),
    created_at: z.string().optional(),
    id: z.string().optional(),
    name: z.string().optional(),
    private: z.int().optional(),
    program_id: z.string().optional(),
    role: z.string().optional(),
    theme: z.string().optional(),
    verified: z.int().optional()
});

export const zDtoRegisterRequest = z.object({
    email: z.string(),
    name: z.string().min(2).max(64),
    password: z.string().min(8).max(72),
    program_id: z.string().optional()
});

export const zDtoResetPasswordRequest = z.object({
    password: z.string().min(8).max(72),
    token: z.string()
});

export const zDtoSearchResult = z.object({
    id: z.string().optional(),
    subtitle: z.string().optional(),
    title: z.string().optional(),
    type: z.string().optional(),
    url: z.string().optional()
});

export const zDtoUpdateArchiveEntryRequest = z.object({
    comment: z.string().max(1000).optional(),
    date: z.string(),
    module_id: z.string(),
    version: z.string().min(2).max(32)
});

export const zDtoUpdateOfficeStatusRequest = z.object({
    occupied: z.boolean().optional()
});

export const zDtoUpdateProfileRequest = z.object({
    name: z.string().min(2).max(64),
    private: z.boolean().optional(),
    program_id: z.string().optional(),
    theme: z.enum([
        'light',
        'dark',
        'system'
    ])
});

export const zDtoUserResponse = z.object({
    active: z.int().optional(),
    avatar_url: z.string().optional(),
    created_at: z.string().optional(),
    email: z.string().optional(),
    id: z.string().optional(),
    name: z.string().optional(),
    private: z.int().optional(),
    program_id: z.string().optional(),
    role: z.string().optional(),
    theme: z.string().optional(),
    verified: z.int().optional()
});

export const zDtoVoteRequest = z.object({
    vote: z.union([
        z.literal(1),
        z.literal(-1),
        z.literal(0)
    ]).optional()
});

export const zGetActivitiesData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.object({
        limit: z.int().optional(),
        offset: z.int().optional()
    }).optional()
});

/**
 * OK
 */
export const zGetActivitiesResponse = z.array(zDtoActivityResponse);

export const zGetAdminDashboardData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.never().optional()
});

/**
 * OK
 */
export const zGetAdminDashboardResponse = zDtoAdminDashboardResponse;

export const zPostAdminModulesData = z.object({
    body: zDtoModuleResponse,
    path: z.never().optional(),
    query: z.never().optional()
});

/**
 * Created
 */
export const zPostAdminModulesResponse = zDtoModuleResponse;

export const zPostAdminProgramsData = z.object({
    body: zDtoProgramResponse,
    path: z.never().optional(),
    query: z.never().optional()
});

/**
 * Created
 */
export const zPostAdminProgramsResponse = zDtoProgramResponse;

export const zGetAdminRefDiscussionTypesData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.never().optional()
});

/**
 * OK
 */
export const zGetAdminRefDiscussionTypesResponse = z.array(z.string());

export const zGetAdminRefRolesData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.never().optional()
});

/**
 * OK
 */
export const zGetAdminRefRolesResponse = z.array(z.string());

export const zGetAdminStatsData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.never().optional()
});

/**
 * OK
 */
export const zGetAdminStatsResponse = zDtoAdminStatsResponse;

export const zGetArchiveData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.object({
        program_id: z.string().optional(),
        version: z.string().optional(),
        module_id: z.string().optional()
    }).optional()
});

/**
 * OK
 */
export const zGetArchiveResponse = z.array(zDtoArchiveEntryResponse);

export const zPostArchiveData = z.object({
    body: z.object({
        file: z.string(),
        date: z.string().optional(),
        module_id: z.string().optional(),
        version: z.string().optional(),
        group_id: z.string().optional(),
        comment: z.string().optional()
    }),
    path: z.never().optional(),
    query: z.never().optional(),
    headers: z.object({
        'X-CSRF-Token': z.string()
    })
});

/**
 * Created
 */
export const zPostArchiveResponse = zDtoArchiveEntryResponse;

export const zDeleteArchiveIdData = z.object({
    body: z.never().optional(),
    path: z.object({
        entryId: z.string()
    }),
    query: z.never().optional()
});

export const zGetArchiveIdData = z.object({
    body: z.never().optional(),
    path: z.object({
        entryId: z.string()
    }),
    query: z.never().optional()
});

/**
 * OK
 */
export const zGetArchiveIdResponse = zDtoArchiveEntryResponse;

export const zPutArchiveIdData = z.object({
    body: zDtoUpdateArchiveEntryRequest,
    path: z.object({
        entryId: z.string()
    }),
    query: z.never().optional()
});

/**
 * OK
 */
export const zPutArchiveIdResponse = zDtoArchiveEntryResponse;

export const zGetArchiveFileData = z.object({
    body: z.never().optional(),
    path: z.object({
        entryId: z.string()
    }),
    query: z.object({
        file_id: z.string().optional()
    }).optional()
});

export const zGetArchiveVersionsData = z.object({
    body: z.never().optional(),
    path: z.object({
        entryId: z.string()
    }),
    query: z.never().optional()
});

/**
 * OK
 */
export const zGetArchiveVersionsResponse = z.array(zDtoArchiveEntryResponse);

export const zDeleteArchiveFileData = z.object({
    body: z.never().optional(),
    path: z.object({
        fileId: z.string()
    }),
    query: z.never().optional()
});

export const zGetAuthAvatarsByUserIdByFilenameData = z.object({
    body: z.never().optional(),
    path: z.object({
        userId: z.string(),
        filename: z.string()
    }),
    query: z.object({
        size: z.int().optional()
    }).optional()
});

export const zPostAuthForgotData = z.object({
    body: zDtoForgotPasswordRequest,
    path: z.never().optional(),
    query: z.never().optional()
});

export const zPostAuthLoginData = z.object({
    body: zDtoLoginRequest,
    path: z.never().optional(),
    query: z.never().optional()
});

/**
 * OK
 */
export const zPostAuthLoginResponse = zDtoUserResponse;

export const zGetAuthMeData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.never().optional()
});

/**
 * OK
 */
export const zGetAuthMeResponse = zDtoUserResponse;

export const zPutAuthMeData = z.object({
    body: zDtoUpdateProfileRequest,
    path: z.never().optional(),
    query: z.never().optional()
});

/**
 * OK
 */
export const zPutAuthMeResponse = zDtoUserResponse;

export const zPostAuthMeAvatarData = z.object({
    body: z.object({
        file: z.string()
    }),
    path: z.never().optional(),
    query: z.never().optional()
});

/**
 * OK
 */
export const zPostAuthMeAvatarResponse = zDtoUserResponse;

export const zGetAuthNotificationsData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.never().optional()
});

/**
 * OK
 */
export const zGetAuthNotificationsResponse = z.array(zDtoNotificationResponse);

export const zPutAuthNotificationsIdReadData = z.object({
    body: z.never().optional(),
    path: z.object({
        notificationId: z.string()
    }),
    query: z.never().optional()
});

/**
 * OK
 */
export const zPutAuthNotificationsIdReadResponse = zDtoNotificationResponse;

export const zPutAuthNotificationsReadAllData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.never().optional()
});

export const zPostAuthRegisterData = z.object({
    body: zDtoRegisterRequest,
    path: z.never().optional(),
    query: z.never().optional()
});

/**
 * Created
 */
export const zPostAuthRegisterResponse = zDtoUserResponse;

export const zPostAuthResetData = z.object({
    body: zDtoResetPasswordRequest,
    path: z.never().optional(),
    query: z.never().optional()
});

/**
 * OK
 */
export const zPostAuthResetResponse = zDtoUserResponse;

export const zGetAuthVerifyData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.object({
        token: z.string()
    })
});

export const zGetDiscussionsData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.object({
        type: z.string().optional(),
        program_id: z.string().optional(),
        query: z.string().optional(),
        sort: z.string().optional(),
        limit: z.int().optional(),
        offset: z.int().optional()
    }).optional()
});

/**
 * OK
 */
export const zGetDiscussionsResponse = z.array(zDtoDiscussionPostResponse);

export const zPostDiscussionsData = z.object({
    body: zDtoCreateDiscussionPostRequest,
    path: z.never().optional(),
    query: z.never().optional()
});

/**
 * Created
 */
export const zPostDiscussionsResponse = zDtoDiscussionPostResponse;

export const zDeleteDiscussionsByPostIdData = z.object({
    body: z.never().optional(),
    path: z.object({
        id: z.string()
    }),
    query: z.never().optional()
});

export const zGetDiscussionsByPostIdData = z.object({
    body: z.never().optional(),
    path: z.object({
        id: z.string()
    }),
    query: z.never().optional()
});

/**
 * OK
 */
export const zGetDiscussionsByPostIdResponse = zDtoDiscussionPostResponse;

export const zPutDiscussionsByPostIdData = z.object({
    body: zDtoCreateDiscussionPostRequest,
    path: z.object({
        id: z.string()
    }),
    query: z.never().optional()
});

/**
 * OK
 */
export const zPutDiscussionsByPostIdResponse = zDtoDiscussionPostResponse;

export const zGetDiscussionsByPostIdCommentsData = z.object({
    body: z.never().optional(),
    path: z.object({
        id: z.string()
    }),
    query: z.never().optional()
});

/**
 * OK
 */
export const zGetDiscussionsByPostIdCommentsResponse = z.array(zDtoDiscussionCommentResponse);

export const zPostDiscussionsByPostIdCommentsData = z.object({
    body: zDtoDiscussionCommentRequest,
    path: z.object({
        id: z.string()
    }),
    query: z.never().optional()
});

/**
 * Created
 */
export const zPostDiscussionsByPostIdCommentsResponse = zDtoDiscussionCommentResponse;

export const zPostDiscussionsByPostIdVoteData = z.object({
    body: zDtoVoteRequest,
    path: z.object({
        id: z.string()
    }),
    query: z.never().optional()
});

export const zPutDiscussionsCommentsByCommentIdData = z.object({
    body: zDtoDiscussionCommentRequest,
    path: z.object({
        id: z.string()
    }),
    query: z.never().optional()
});

/**
 * OK
 */
export const zPutDiscussionsCommentsByCommentIdResponse = zDtoDiscussionCommentResponse;

export const zPostDiscussionsCommentsByCommentIdVoteData = z.object({
    body: zDtoVoteRequest,
    path: z.object({
        id: z.string()
    }),
    query: z.never().optional()
});

export const zGetEventsData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.never().optional()
});

/**
 * OK
 */
export const zGetEventsResponse = z.array(zDtoEventResponse);

export const zPostEventsData = z.object({
    body: z.object({
        title: z.string(),
        file: z.string().optional()
    }),
    path: z.never().optional(),
    query: z.never().optional()
});

/**
 * Created
 */
export const zPostEventsResponse = zDtoEventResponse;

export const zGetEventsByEventIdData = z.object({
    body: z.never().optional(),
    path: z.object({
        eventId: z.string()
    }),
    query: z.never().optional()
});

/**
 * OK
 */
export const zGetEventsByEventIdResponse = zDtoEventResponse;

export const zGetEventsByEventIdCoverData = z.object({
    body: z.never().optional(),
    path: z.object({
        eventId: z.string()
    }),
    query: z.object({
        size: z.int().optional()
    }).optional()
});

export const zGetEventsByEventIdMediaData = z.object({
    body: z.never().optional(),
    path: z.object({
        eventId: z.string()
    }),
    query: z.never().optional()
});

/**
 * OK
 */
export const zGetEventsByEventIdMediaResponse = z.array(zDtoMediaResponse);

export const zPostEventsByEventIdMediaData = z.object({
    body: z.object({
        title: z.string().optional(),
        description: z.string().optional(),
        file: z.string()
    }),
    path: z.object({
        eventId: z.string()
    }),
    query: z.never().optional()
});

/**
 * Created
 */
export const zPostEventsByEventIdMediaResponse = zDtoMediaResponse;

export const zGetMediaByMediaIdData = z.object({
    body: z.never().optional(),
    path: z.object({
        mediaId: z.string()
    }),
    query: z.never().optional()
});

/**
 * OK
 */
export const zGetMediaByMediaIdResponse = zDtoMediaResponse;

export const zGetMediaByMediaIdFileData = z.object({
    body: z.never().optional(),
    path: z.object({
        mediaId: z.string()
    }),
    query: z.never().optional()
});

export const zGetMediaByMediaIdPreviewData = z.object({
    body: z.never().optional(),
    path: z.object({
        mediaId: z.string()
    }),
    query: z.object({
        size: z.int().optional()
    }).optional()
});

export const zGetOfficeStatusData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.never().optional()
});

/**
 * OK
 */
export const zGetOfficeStatusResponse = zDtoOfficeStatusResponse;

export const zPutOfficeStatusData = z.object({
    body: zDtoUpdateOfficeStatusRequest,
    path: z.never().optional(),
    query: z.never().optional()
});

/**
 * OK
 */
export const zPutOfficeStatusResponse = zDtoOfficeStatusResponse;

export const zGetProgramsData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.never().optional()
});

/**
 * OK
 */
export const zGetProgramsResponse = z.array(zDtoProgramResponse);

export const zGetProgramsIdData = z.object({
    body: z.never().optional(),
    path: z.object({
        programId: z.string()
    }),
    query: z.never().optional()
});

/**
 * OK
 */
export const zGetProgramsIdResponse = zDtoProgramResponse;

export const zGetProgramModulesData = z.object({
    body: z.never().optional(),
    path: z.object({
        programId: z.string()
    }),
    query: z.never().optional()
});

/**
 * OK
 */
export const zGetProgramModulesResponse = z.array(zDtoModuleResponse);

export const zGetSearchData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.object({
        q: z.string()
    })
});

/**
 * OK
 */
export const zGetSearchResponse = z.array(zDtoSearchResult);

export const zGetUsersData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.object({
        limit: z.int().optional(),
        offset: z.int().optional()
    }).optional()
});

/**
 * OK
 */
export const zGetUsersResponse = z.array(zDtoUserResponse);

export const zGetUsersByUserIdData = z.object({
    body: z.never().optional(),
    path: z.object({
        userId: z.string()
    }),
    query: z.never().optional()
});

/**
 * OK
 */
export const zGetUsersByUserIdResponse = zDtoPublicUserResponse;

export const zGetUsersByUserIdActivitiesData = z.object({
    body: z.never().optional(),
    path: z.object({
        userId: z.string()
    }),
    query: z.object({
        limit: z.int().optional(),
        offset: z.int().optional()
    }).optional()
});

/**
 * OK
 */
export const zGetUsersByUserIdActivitiesResponse = z.array(zDtoActivityResponse);
