// This file is auto-generated by @hey-api/openapi-ts

import { z } from 'zod';

export const zAuthCsrfResponse = z.object({
    csrf: z.optional(z.string())
});

export const zAuthErrorResponse = z.object({
    error: z.optional(z.string()),
    message: z.optional(z.string())
});

/**
 * Exam details
 */
export const zAuthExamResponse = z.object({
    comment: z.optional(z.string()),
    edit_version: z.optional(z.int()),
    exam_date: z.optional(z.iso.date()),
    group_id: z.optional(z.string()),
    id: z.optional(z.string()),
    is_latest: z.optional(z.int()),
    module_name: z.optional(z.string()),
    moduleid: z.optional(z.int()),
    programid: z.optional(z.int()),
    uploaded_at: z.optional(z.string()),
    uploader_name: z.optional(z.string()),
    version: z.optional(z.string())
});

export const zAuthLoginRequest = z.object({
    email: z.optional(z.string()),
    password: z.optional(z.string())
});

/**
 * A study module
 */
export const zAuthModuleResponse = z.object({
    alias: z.optional(z.string()),
    id: z.optional(z.int()),
    name: z.optional(z.string()),
    programid: z.optional(z.int())
});

/**
 * A study program including valid PO versions
 */
export const zAuthProgramResponse = z.object({
    id: z.optional(z.int()),
    name: z.optional(z.string()),
    versions: z.optional(z.array(z.string()))
});

export const zAuthPublicUserResponse = z.object({
    active: z.optional(z.int()),
    created_at: z.optional(z.string()),
    id: z.optional(z.string()),
    name: z.optional(z.string()),
    programid: z.optional(z.int()),
    role: z.optional(z.string()),
    theme: z.optional(z.string()),
    verified: z.optional(z.int())
});

export const zAuthRegisterRequest = z.object({
    email: z.optional(z.string()),
    name: z.optional(z.string()),
    password: z.optional(z.string()),
    programid: z.optional(z.int())
});

export const zAuthUpdateExamRequest = z.object({
    comment: z.optional(z.string()),
    date: z.optional(z.string()),
    moduleid: z.optional(z.int()),
    programid: z.optional(z.int()),
    version: z.optional(z.string())
});

export const zAuthUpdateProfileRequest = z.object({
    name: z.optional(z.string()),
    programid: z.optional(z.int()),
    theme: z.optional(z.string())
});

/**
 * User account information
 */
export const zAuthUserResponse = z.object({
    active: z.optional(z.int()),
    created_at: z.optional(z.string()),
    email: z.optional(z.string()),
    id: z.optional(z.string()),
    name: z.optional(z.string()),
    password: z.optional(z.string()),
    programid: z.optional(z.int()),
    role: z.optional(z.string()),
    theme: z.optional(z.string()),
    updated_at: z.optional(z.string()),
    verification_token: z.optional(z.string()),
    verified: z.optional(z.int()),
    verified_at: z.optional(z.string()),
    verified_until: z.optional(z.string())
});

export const zGetAuthCsrfData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zGetAuthCsrfResponse = zAuthCsrfResponse;

export const zPostAuthLoginData = z.object({
    body: zAuthLoginRequest,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zPostAuthLoginResponse = zAuthUserResponse;

export const zPostAuthLogoutData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never()),
    headers: z.object({
        'X-CSRF-Token': z.string()
    })
});

export const zGetAuthMeData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zGetAuthMeResponse = zAuthUserResponse;

export const zPutAuthMeData = z.object({
    body: zAuthUpdateProfileRequest,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zPutAuthMeResponse = zAuthUserResponse;

export const zPostAuthRegisterData = z.object({
    body: zAuthRegisterRequest,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * Created
 */
export const zPostAuthRegisterResponse = zAuthUserResponse;

export const zGetAuthVerifyData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.object({
        token: z.string()
    })
});

export const zGetExamsData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.object({
        programid: z.optional(z.int()),
        version: z.optional(z.string()),
        moduleid: z.optional(z.int())
    }))
});

/**
 * OK
 */
export const zGetExamsResponse = z.array(zAuthExamResponse);

export const zPostExamsData = z.object({
    body: z.object({
        file: z.string(),
        date: z.string(),
        assignments: z.string(),
        comment: z.optional(z.string())
    }),
    path: z.optional(z.never()),
    query: z.optional(z.never()),
    headers: z.object({
        'X-CSRF-Token': z.string()
    })
});

/**
 * Created
 */
export const zPostExamsResponse = z.record(z.string(), z.string());

export const zDeleteExamsIdData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        id: z.string()
    }),
    query: z.optional(z.never())
});

export const zPutExamsIdData = z.object({
    body: zAuthUpdateExamRequest,
    path: z.object({
        id: z.string()
    }),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zPutExamsIdResponse = zAuthExamResponse;

export const zGetExamsFileData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        id: z.string()
    }),
    query: z.optional(z.never())
});

export const zGetExamVersionsData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        groupId: z.string()
    }),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zGetExamVersionsResponse = z.array(zAuthExamResponse);

export const zGetProgramsData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zGetProgramsResponse = z.array(zAuthProgramResponse);

export const zGetProgramsIdData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        id: z.int()
    }),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zGetProgramsIdResponse = zAuthProgramResponse;

export const zGetProgramModulesData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        id: z.int()
    }),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zGetProgramModulesResponse = z.array(zAuthModuleResponse);

export const zGetUsersData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.object({
        limit: z.optional(z.int()),
        offset: z.optional(z.int())
    }))
});

/**
 * OK
 */
export const zGetUsersResponse = z.array(zAuthUserResponse);

export const zGetUsersByIdData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        id: z.string()
    }),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zGetUsersByIdResponse = zAuthPublicUserResponse;
