// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
)

type Campuse struct {
	ID       int64          `json:"id"`
	Name     string         `json:"name"`
	Location sql.NullString `json:"location"`
	Created  string         `json:"created"`
}

type Comment struct {
	ID      string         `json:"id"`
	Postid  string         `json:"postid"`
	Userid  string         `json:"userid"`
	Body    string         `json:"body"`
	Created string         `json:"created"`
	Updated string         `json:"updated"`
	Deleted sql.NullString `json:"deleted"`
}

type Discipline struct {
	ID      int64  `json:"id"`
	Name    string `json:"name"`
	Degree  string `json:"degree"`
	Created string `json:"created"`
}

type Exam struct {
	ID           string         `json:"id"`
	Userid       string         `json:"userid"`
	Disciplineid int64          `json:"disciplineid"`
	Campusid     sql.NullInt64  `json:"campusid"`
	Examdate     string         `json:"examdate"`
	Uploaded     string         `json:"uploaded"`
	Accesskey    string         `json:"accesskey"`
	Mimetype     string         `json:"mimetype"`
	Sz           sql.NullInt64  `json:"sz"`
	Checksum     sql.NullString `json:"checksum"`
}

type Post struct {
	ID      string         `json:"id"`
	Userid  string         `json:"userid"`
	Title   string         `json:"title"`
	Body    string         `json:"body"`
	Created string         `json:"created"`
	Updated string         `json:"updated"`
	Deleted sql.NullString `json:"deleted"`
}

type Session struct {
	ID       string `json:"id"`
	Userid   string `json:"userid"`
	Created  string `json:"created"`
	Lastseen string `json:"lastseen"`
	Expires  string `json:"expires"`
}

type User struct {
	ID           string `json:"id"`
	Email        string `json:"email"`
	Password     string `json:"password"`
	Name         string `json:"name"`
	Role         string `json:"role"`
	Active       int64  `json:"active"`
	Campusid     int64  `json:"campusid"`
	Disciplineid int64  `json:"disciplineid"`
	Created      string `json:"created"`
	Updated      string `json:"updated"`
}
