// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	CleanupExpiredSessions(ctx context.Context) error
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	DeleteSession(ctx context.Context, id string) error
	DeleteUserSessions(ctx context.Context, userid string) error
	GetSession(ctx context.Context, id string) (Session, error)
	GetUser(ctx context.Context, id string) (GetUserRow, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]ListUsersRow, error)
	SlideSession(ctx context.Context, arg SlideSessionParams) (Session, error)
	TouchSession(ctx context.Context, id string) (Session, error)
}

var _ Querier = (*Queries)(nil)
